/* ============================================================
   SMR News data — single source for SMR-news.html
   Auto-updated by scripts/track-news.mjs (GitHub Actions); changes land via PR.
   Schema: date, title, summary, cat(인허가|계약|투자|기술|정책),
           type(General|PWR|BWR|SFR|HTGR|FHR|MSR|Micro), dev, region, source, url, k(internal dedup key)
   Optional: summaryLong (2~3문장 — 홈 피처드 카드에서 summary 대신 표시)
   ============================================================ */
window.SMR_NEWS = [
  {
    "date": "2026-06-11",
    "title": "DOE, Oklo Aurora 원자로 예비안전분석 승인",
    "summary": "미국 에너지부가 Oklo의 Aurora 원자로에 대한 예비안전분석(PDSA)을 승인했으며, 이는 아이다호 국립연구소 건설을 향한 인허가 과정의 중요한 이정표이다.",
    "summaryLong": "Oklo는 미국 에너지부(DOE)로부터 Aurora 소형모듈원자로의 예비안전분석(Preliminary Documented Safety Analysis) 승인을 획득했다. 이는 아이다호 국립연구소(INL)에 건설될 Aurora 프로젝트의 인허가 경로상 주요 단계로, 설계인증 진행을 위한 기반을 마련했다.",
    "cat": "인허가",
    "type": "Micro",
    "dev": "Oklo",
    "region": "US",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/doe-approval-milestone-for-oklo-reactor",
    "k": "doe approval milestone for oklo reactor"
  },
  {
    "date": "2026-06-11",
    "title": "Trump 행정부 EPA 청장, SMR 확대 지지 발표",
    "summary": "Trump 행정부의 EPA 청장 Lee Zeldin이 소형모듈원자로 확대를 지지하면서 SMR 관련 기업들의 주가가 상승했다.",
    "summaryLong": "Trump 행정부의 EPA 청장 Lee Zeldin이 소형모듈원자로(SMR) 확대에 대한 공식적 지지 입장을 표명했다. 이러한 정부 차원의 지지 발표는 SMR 기술의 상용화 전망을 긍정적으로 평가하는 신호로 작용하면서, 관련 기업들의 주가를 상승시키는 시장 반응을 촉발했다. SMR은 전통적 원자력 발전소보다 건설 비용과 기간이 적게 들어 탈탄소 에너지 전환의 주요 수단으로 주목받고 있으며, 미국 행정부의 정책적 지원은 이 분야의 투자와 개발 확대에 긍정적 영향을 미칠 것으로 예상된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxPT3hLRkpXUXhmbzRlVC1JYUtOaDk1Y3l2Zm5FdVZZNnNFTWNwTjJpLWkwanhwUG9xUjBFNjFLU2p4VzJGZkd1cGI4dDZTSkRNX25UaXNhNnBOTjZPQ1pPaFI4QUVodXplTlVfNmFXRkQwaEJQREFUR0hramduNWNDZ0JGZ0FXbWYzdkYtdGh5cTBuNy1yYXhiMHhUVFYtLThnSjE0TklIRlIzTXZLV3ZxbGo5VVh6d2piNGdjM3JRTGpFV244a0NueVZlNHA5MmRLU3lv?oc=5",
    "k": "smr nne oklo gain after trump s epa chief lee zeldin touts small modular reactor buildout"
  },
  {
    "date": "2026-06-11",
    "title": "대한민국 첫 i-SMR, 경주 유치 주장",
    "summary": "국내 첫 혁신형 SMR(i-SMR) 구축 후보지로 경주를 제안하는 기고문이다.",
    "summaryLong": "국내 첫 혁신형 소형모듈원자로(i-SMR) 구축의 후보 입지로 경주 지역을 제안하는 기고가 발표되었다. 경주는 월성원자력발전소 등 원자력 인프라와 전문 인력, 지역 경제 기반이 갖춰져 있어 i-SMR 프로젝트 추진에 유리한 입지로 평가되고 있다. 한국의 i-SMR 기술은 세계적 경쟁력을 갖춘 기술로, 국내 첫 실증 사업은 기술 검증과 상용화 경험 축적의 중요한 기회가 될 것으로 전망된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "KR",
    "source": "\"SMR 원자력\" - Google 뉴스",
    "url": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE1IS0hoUmhURFJtNWxEbm9kTVJnTXNnQ1R6Y2YzWWNnZ1R2NENBRDRadnN6ajNNWFlkOWIxOW1QeDJFeEl6WVB1akp1SFl0bFJuOW1FTlJPYTA?oc=5",
    "k": "황대욱 특별기고 대한민국 첫 i smr 답은 경주다"
  },
  {
    "date": "2026-06-11",
    "title": "용융염 원자로 탑재 선박 개념설계 승인",
    "summary": "Lloyd's Register와 American Bureau of Shipping이 용융염 원자로 기반 선박 추진 시스템의 개념설계를 승인했다.",
    "summaryLong": "Lloyd's Register가 용융염 원자로를 탑재한 자동차운반선의 개념설계에 대한 원칙적 승인(AIP)을 부여했으며, American Bureau of Shipping도 화물선 추진시스템에 원자로를 통합하는 설계에 대한 AIP를 발급했다. 이는 해양 분야의 원자력 추진 기술 발전을 보여주는 사례이다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/nuclear-powered-ship-conceptual-designs-approved",
    "k": "nuclear powered ship conceptual designs approved"
  },
  {
    "date": "2026-06-11",
    "title": "네덜란드 오버레이설주 SMR 입지 후보지 식별",
    "summary": "오버레이설주가 Tractebel과 함께 소형모듈원자로 건설 적지를 파악하는 초기 연구를 완료했다.",
    "summaryLong": "네덜란드 오버레이설주가 컨설팅 회사 Tractebel과 협력하여 소형모듈원자로 건설에 적합한 입지 후보지를 식별하는 초기 연구를 완료했다. 이 연구는 유럽의 에너지 안보 강화와 탄소 감축 목표 달성을 위해 SMR 도입을 추진하려는 네덜란드 정부의 정책 의지를 반영한다. 오버레이설주의 이 같은 움직임은 유럽 내 SMR 도입의 구체적 진전을 보여주는 사례이며, 향후 사업화 단계로의 진전이 기대된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "EU",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/study-identifies-potential-smr-sites-in-dutch-province",
    "k": "study identifies potential smr sites in dutch province"
  },
  {
    "date": "2026-06-11",
    "title": "소형모듈원자로, 항만 전력 공급 방안 검토",
    "summary": "소형모듈원자로를 항만 시설의 전력 공급원으로 활용하는 방안이 연구되고 있다.",
    "summaryLong": "소형모듈원자로를 항만·항구 시설의 전력 공급원으로 활용하는 방안에 대한 연구가 진행 중이다. 항만은 해수 냉각 등 풍부한 자원을 보유하고 있고 높은 전력 수요를 가지고 있어 SMR의 배치 입지로서 장점이 있다. 이는 해양 산업의 탈탄소화와 에너지 독립성 강화를 동시에 추구할 수 있는 혁신적 방안으로, 항만 운영 효율성 증대와 환경 규제 대응에도 긍정적 기여를 할 것으로 평가된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMibkFVX3lxTFBWb3RfcUdSUWRCOU9uNmZSVlNEUkJtby1uTXZKYkplQm52SGowd1dmYWt2aDBMU05IZGQ0SXNkTlUtbzBqeW1KaE9ONWZoMzhyN01ncTF1Y3doREh6ME5hTHcwOXhYZG5sWWd6blBB?oc=5",
    "k": "smr studied to power ports"
  },
  {
    "date": "2026-06-11",
    "title": "우즈베키스탄, 첫 소형모듈원자로 NPP 프로젝트 착수",
    "summary": "우즈베키스탄이 첫 소형모듈원자로 발전소 프로젝트를 공식 착수했다.",
    "summaryLong": "우즈베키스탄이 국내 첫 소형모듈원자로 발전소 프로젝트를 공식적으로 착수했다. 이는 중앙아시아 지역의 에너지 안보 확보와 환경 친화적 전력 생산을 목표로 하는 중요한 사업으로, 해당 국가의 에너지 정책 전환을 보여주는 사례이다. SMR 기술의 도입을 통해 우즈베키스탄은 소규모 분산 발전 체계를 구축할 수 있을 것으로 기대되며, 이는 지역 에너지 자급률 향상과 경제 발전에 기여할 것으로 전망된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "EU",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxQZGVPYXlHMzNVVHZHMC1UaXZtQVFVWlA3Qkx4MUFsLXN6ZTE5MmtfdkRBR2pCWmRQMWRMMWEyQ2dLZFFWMkwzUExYdlNZdE0zTF9lak1Zc2pza0FuaDlxcTdrN3VhNlJLNmNJVFg2YVFmYU4tV0RhSndNTkstYkl5Z08wX0d2N2NFWDRpdzh5M0lLbURzank2QzU1ejlsWEdR?oc=5",
    "k": "uk media uzbekistan launches first small modular reactor npp project"
  },
  {
    "date": "2026-06-10",
    "title": "Holtec, Oyster Creek 부지에 4기 SMR 검토",
    "summary": "Holtec International이 뉴저지주 Oyster Creek 폐지에 4기의 소형모듈원자로 건설을 검토하고 있다.",
    "summaryLong": "미국의 원자력 기업 Holtec International이 뉴저지주의 폐기된 Oyster Creek 발전소 부지에 4기의 소형모듈원자로 건설을 검토 중이다. 이 프로젝트는 유휴 원자력 시설의 재활용과 지역 전력 공급의 현대화를 동시에 추진하는 전략으로, 기존 인프라의 활용으로 개발 기간과 비용을 절감할 수 있는 장점을 가지고 있다. Holtec의 이러한 움직임은 미국 내 SMR 상용화 추진의 구체적 진전을 시사하며, 추후 인허가 과정을 통한 사업 진행이 기대된다.",
    "cat": "기술",
    "type": "General",
    "dev": "Holtec",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMivAFBVV95cUxNWnJIaTk3Y0cxaW5YR2Nxa0RpRDVDdkNtckQxX1hoMjZRZVpwbTUyNUNXdEl6V2dkc05yZU9KZHVUZE40QXg2am9IeVM0dXdxUzJxaXFGWkZmNk5NaVNCMzFIbVh6VDRCRFo5V2hfWkdfdk1kdENHLXJVTmlJQXJqOWE1NlRCc2FIcXVxUlRrbHFsRzZrdmMwNy1nenR4YjBFemtkUnFlMkJZRzd3azQzcVlSc3J0SXROYTU0NA?oc=5",
    "k": "holtec considers 4 nuclear reactors for oyster creek site in lacey"
  },
  {
    "date": "2026-06-10",
    "title": "BN-1200 고속로, 2027년 건설 착수 목표",
    "summary": "러시아의 나트륨냉각 고속중성자로(BN-1200)가 벨로야르스크에서 2027년 건설 착수를 목표로 진행 중이다.",
    "summaryLong": "러시아의 나트륨냉각 고속중성자로(BN-1200)가 벨로야르스크 지역에서 2027년의 건설 착수를 목표로 진행 중이다. BN-1200은 고급 핵연료 사이클과 우수한 안전 성능을 갖춘 차세대 원자로로, 러시아의 원자력 기술 고도화 전략을 나타낸다. 이 프로젝트의 추진은 장기적으로 전 세계 고속로 기술 개발에 영향을 미칠 것으로 예상되며, 지속 가능한 핵에너지 이용을 위한 국제적 협력 강화의 필요성을 강조한다.",
    "cat": "기술",
    "type": "SFR",
    "dev": "",
    "region": "EU",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/bn-1200-targeted-for-construction-start-in-2027",
    "k": "bn 1200 targeted for construction start in 2027"
  },
  {
    "date": "2026-06-10",
    "title": "일본-카자흐, 고속로 협력 확대",
    "summary": "일본원자력연구개발기구와 카자흐스탄 국가핵심센터가 고속로 핵심 안전 실험의 새로운 협력 단계에 합의했다.",
    "summaryLong": "일본원자력연구개발기구와 카자흐스탄 국가핵심센터가 고속로의 핵심 안전 실험 분야에서 새로운 협력 단계에 합의했다. 이 협력은 고속로 기술의 안전성 검증과 국제적 표준화를 추진하려는 양국의 전략적 의도를 보여주며, 아시아-중앙아시아 지역의 원자력 기술 네트워크 강화에 기여한다. 고속로는 원자력의 지속 가능성을 크게 향상시킬 수 있는 핵심 기술로 평가되고 있으며, 한·일·러 등 주요국의 기술 협력은 향후 상용화 가속화를 위한 중요한 밑거름이 될 것으로 기대된다.",
    "cat": "기술",
    "type": "SFR",
    "dev": "",
    "region": "JP",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/japan-kazakhstan-extend-cooperation-on-fast-reactors",
    "k": "japan kazakhstan extend cooperation on fast reactors"
  },
  {
    "date": "2026-06-10",
    "title": "Deep Fission, IPO 앞두고 공모 규모 72% 축소",
    "summary": "소형모듈원자로 개발사 Deep Fission이 4,300만 달러 규모 IPO를 앞두고 공모 규모를 대폭 줄였다.",
    "summaryLong": "소형모듈원자로(SMR) 개발업체인 Deep Fission이 공개상장(IPO)을 앞두고 공모 규모를 당초 계획에서 72% 감축하여 4,300만 달러 규모로 축소했다. 이는 글로벌 자본시장의 금리 환경 변화와 신흥 원자력 기술 기업들에 대한 투자심리 냉각을 반영한 것으로 보인다. Deep Fission을 비롯한 SMR 개발사들은 높은 자본소요와 장기간의 개발 기간으로 인해 자금 조달에 어려움을 겪고 있다. 이번 사례는 혁신적인 원자력 기술이 상용화되기까지 투자자들의 신뢰 구축과 실적 증명이 얼마나 중요한지를 보여준다.",
    "cat": "투자",
    "type": "General",
    "dev": "Deep Fission",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMizgFBVV95cUxPcHJiMkc2YndWcElGdnM1bjJtMmpYNklTanB2Z0Y4azVLeDd6V2RhSm0wRncySE5SR25NbnZoUG95cDNzZFBMTHk5TDhhRkw1OUJmdkc3OWZFMDJhMWl0VHF6cmFObm9ZYldjZmp4Vk8ySkNuVy0wbTFYZlRTMENwLTg0N3N0Y3Z5M040UXluM0RrbEM4WkxFaHdoZU5WUzdfVkhyNlg1U2dZNjc2Y3hJbDZMNVJCSkhXS0prU3JoRzZfMjNZVEdJejVkVldZQQ?oc=5",
    "k": "small modular nuclear reactor developer deep fission slashes deal size by 72 ahead of 43 million ipo"
  },
  {
    "date": "2026-06-09",
    "title": "루마니아 항만, SMR 도입 타당성 검토",
    "summary": "아랍에미리트 DP World가 루마니아 콘스탄차 항만의 에너지 수요 충족을 위해 SMR 기술 도입 가능성을 검토하고 있다.",
    "summaryLong": "물류기업 DP World가 프랑스 원자력청(CEA)·TerraWater Institute와 루마니아 콘스탄차 항만의 SMR 도입 타당성조사 협약을 체결했다. 2030~2050년 에너지 수요 전망을 바탕으로 원자력 기반 솔루션의 기술적·경제적 타당성과 안전기준·지역사회 영향을 평가한다. DP World는 별도로 영국 London Gateway 항만에 20MWe 마이크로원자로를 2030년 가동 목표로 추진 중이다.",
    "cat": "기술",
    "type": "General",
    "dev": "DP World",
    "region": "EU",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/smrs-to-be-considered-at-romanian-port"
  },
  {
    "date": "2026-06-08",
    "title": "글로벌 SMR 시장, 첨단 원자력 기술 주도로 성장",
    "summary": "글로벌 소형모듈원자로 시장이 첨단 원자력 기술 개발에 힘입어 확대되고 있다.",
    "summaryLong": "글로벌 소형모듈원자로 시장이 차세대 원자력 기술 개발과 혁신을 통해 지속적인 성장을 이루고 있다. 원자력 업계에서는 탄소중립과 에너지 안보 확보를 위한 핵심 기술로 SMR을 주목하면서 투자와 개발을 확대하고 있다. 각국 정부와 민간 기업들이 협력하여 안전성 강화, 비용 절감, 설계 최적화 등 첨단 원자력 기술을 경쟁적으로 추진 중이다. 이러한 기술 진전은 향후 SMR의 상용화 시기 단축과 시장 진입 확대로 이어질 것으로 예상된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxPdHBSQ0oxbUhYYWc2cXMxM2hOTHJTUDZuOEZ5VHBDcGJDUnZQb3IxazdNa1h0TW40R1BoeWVZV25Xb1gxLVNIUWc3V3ljQzdTRWxIUUk3ZWFPOFJRb19pRm1zUlQyVEM1SldXQy03Y1lVeFNLdENkQ3JOX1JHNGhoYmc3RTJkcEZnSnBWZHA3T3dQU2MteXFnOHdER3kwQ2ZRZHcwalIwaThRdnpSam9rNVE1WjVIQVdzM0VrcUk0ZlI0dnREdUw00gHHAUFVX3lxTE90cFJDSjFtSFhhZzZxczEzaE5MclNQNm44RnlUcENwYkNSdlBvcjFrN01rWHRNbjRHUGh5ZVlXbldvWDEtU0hRZzdXeWNDN1NFbEhRSTdlYU84UlFvX2lGbXNSVDJUQzVKV1dDLTdjWVV4U0t0Q2RDck5fUkc0aGhiZzdFMmRwRmdKcFZkcDdPd1BTYy15cWc4d0RHeTBDZlFkdzBqUjBpOFF2elJqb2s1UTVaNUhBV3MzRWtxSTRmUjR2dER1TDQ?oc=5",
    "k": "global small modular reactor market growth driven by advanced nuclear technologies"
  },
  {
    "date": "2026-06-05",
    "title": "우즈베키스탄 첫 SMR 착공식 개최",
    "summary": "우즈베키스탄에서 첫 소형모듈원자로의 첫 콘크리트 타설 기념식이 열려 본격 건설이 시작되었다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/ceremony-to-mark-first-concrete-for-uzbekistan-smr",
    "summaryLong": "우즈베키스탄에서 처음으로 소형모듈원자로의 콘크리트 타설 기념식을 개최하여 본격적인 건설이 시작되었다. 이는 중앙아시아 지역의 에너지 전환과 탄소중립 목표 달성을 위한 우즈베키스탄의 전략적 결정을 의미한다. SMR 기술 도입을 통해 지역의 전력 공급 안정성을 높이고 대규모 원전 건설의 부담을 경감할 수 있을 것으로 기대된다. 이번 착공은 개발도상국들이 SMR을 새로운 에너지 솔루션으로 채택하는 추세를 보여주는 중요한 신호이다."
  },
  {
    "date": "2026-06-05",
    "title": "미국 마이크로원자로, 임계 달성 첫 사례",
    "summary": "앤터러스 뉴클리어의 Mark-0 마이크로원자로가 영점 전력 임계에 도달해 DOE 프로그램에서 첫 임계 달성 사례가 되었다.",
    "cat": "기술",
    "type": "General",
    "dev": "Antares Nuclear",
    "region": "US",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/first-criticality-for-us-microreactor-under-doe-programme",
    "summaryLong": "미국의 앤터러스 뉴클리어가 개발한 Mark-0 마이크로원자로가 영점 전력 임계(zero-power criticality)에 도달하여 미 에너지부(DOE) 지원 프로그램에서 첫 임계 달성 사례가 되었다. 이는 마이크로원자로 기술의 실증 단계에서 중요한 이정표로, 노심 물리 특성이 예측대로 작동함을 입증한 것이다. 임계 달성을 통해 설계의 타당성이 검증되었으며, 향후 출력 상향 시운전과 상용화 진행이 가능해졌다. 이 성과는 미국의 차세대 원자력 에너지 전략 실현과 DOE 프로그램의 성공 사례로 평가된다."
  },
  {
    "date": "2026-06-05",
    "title": "블리칼라, 스웨덴 SMR 플랜트 정부 지원 신청",
    "summary": "스웨덴 납냉각 SMR 개발사 블리칼라가 6기의 SEALER 원자로 플랜트 건설을 위한 정부 재정 지원을 신청했다.",
    "cat": "정책",
    "type": "General",
    "dev": "Blykalla",
    "region": "EU",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/blykalla-applies-for-state-aid-for-smr-plant",
    "summaryLong": "스웨덴의 납냉각 소형모듈원자로 개발사인 블리칼라가 SEALER 원자로 6기로 구성된 플랜트 건설을 위해 정부 재정 지원을 신청했다. 이는 유럽의 에너지 독립성과 탄소중립 목표 달성을 위한 스웨덴의 원자력 정책 강화를 나타낸다. 납냉각 SMR 기술은 고온 냉각, 수동 안전성, 소형화 등의 장점으로 주목받고 있으며, 정부 지원을 통해 상용화 가속화가 기대된다. 블리칼라의 정부 지원 신청이 승인될 경우 유럽 지역의 SMR 개발 생태계 활성화에 긍정적 영향을 미칠 것으로 전망된다."
  },
  {
    "date": "2026-06-05",
    "title": "Rolls-Royce SMR, 부품 외주 논란 (한국 협력사)",
    "summary": "영국 Rolls-Royce가 자국 SMR 프로젝트의 일부 부품을 한국으로 외주하면서 논란이 발생했다.",
    "summaryLong": "영국의 Rolls-Royce가 자국의 소형모듈원자로 프로젝트의 일부 핵심 부품을 한국으로 외주하기로 결정하면서 국내 산업 역량에 대한 신뢰는 높아진 반면, 영국 내에서는 본국 산업 기반 약화 우려와 정책 일관성 논란이 제기되고 있다. 이는 SMR과 같은 전략 기술 분야에서 글로벌 공급망 구축의 필요성과 국가 간 기술 협력의 현실적 측면을 드러낸다. 한국 협력사의 참여는 국내 원자력 부품 산업의 기술 수준과 경쟁력이 국제 수준에 도달했음을 인증하는 의미를 갖는다. 향후 원자력 장비 산업의 글로벌 분업 구조와 국가별 기술 경쟁력 재편이 예상된다.",
    "cat": "기술",
    "type": "General",
    "dev": "Rolls-Royce",
    "region": "UK",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxOMGUzcERuMHNCUDdPc2s2aDlwb2hybzRmSEc5Rzg1ekl1VS04LVhWaVFiR1VuRklobWFZRURRMTdsN3NhWmQzQU9VZ09zRmh2VXM1YWJqWkUtZHBlRGtlY2g4V0VRZ182ZXNWOGM2QjNYczNXN1gtZFBDYnVFaEJNeW5KbVA?oc=5",
    "k": "rolls royce under fire for outsourcing parts of uk nuclear project to south korea"
  },
  {
    "date": "2026-06-05",
    "title": "소형모듈원자로 임계점 도달 첫 시운전 성공",
    "summary": "소형모듈원자로가 첫 시운전에서 임계점에 도달했다.",
    "summaryLong": "소형모듈원자로가 첫 시운전에서 임계점 달성에 성공하여 원자로 운영 능력의 기초적 검증을 완료했다. 임계점 도달은 핵분열 연쇄반응이 자체적으로 유지되는 상태를 의미하며, 설계 및 건설 과정이 기술적으로 적절히 수행되었음을 입증한다. 이 성과는 SMR 프로젝트의 개발 일정이 계획대로 진행되고 있으며, 추가 성능 확인 시험으로 나아갈 수 있는 기반을 마련했다. 첫 시운전 성공은 해당 SMR 기술의 상용 가능성을 높이고 향후 인허가 및 사업화 추진에 긍정적 신호를 제공한다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxPc1pTZEpKVHowV2VpVEdNY3g3d2NwQ3dKTWFDa3dMeGgtRGhnbGkxbHdOSmpqVVo1NnRNQ3lwVWxCX2lvLTlLbUpWVGp1R1VfQk1PVTFxT0RQUjFtd1VQNlFVME9aOFgySTF2RTJNb3EyS1B1Y1M3SWhfWENjN1RpRzkzTkczSmxjZWxfRmFfTXhUSFROUVVmdg?oc=5",
    "k": "small modular nuclear reactor reaches criticality in first test"
  },
  {
    "date": "2026-06-04",
    "title": "X-energy 2026년 1분기 실적 — 파이프라인 144기·11.5GWe",
    "summary": "상장(Nasdaq: XE) 후 분기 공시. 미국·영국 합산 144기, 약 11.5 GWe 파이프라인(고객 권리 전량 행사 가정).",
    "cat": "투자",
    "type": "HTGR",
    "dev": "X-energy",
    "region": "US·UK",
    "source": "X-energy IR",
    "url": "https://x-energy.com/news/x-energy-reports-first-quarter-2026-results/",
    "summaryLong": "나스닥 상장 후 X-energy가 분기 공시를 통해 미국과 영국을 합산한 144기 규모(약 11.5GWe 용량)의 SMR 파이프라인을 보유하고 있음을 공개했다. 이는 고객들의 권리 전량 행사를 가정한 수치로, X-energy의 시장 포지셔닝과 사업 전망에 대한 강한 신뢰를 반영한다. 144기의 주문 파이프라인은 업계에서 가장 강력한 수주 규모 중 하나로, 2026년 1분기 기준 회사의 성장 모멘텀과 글로벌 SMR 시장 확대의 현실성을 보여준다. X-energy의 공시는 SMR 기술에 대한 고객 수요가 구체적이고 규모가 있으며, 향후 산업 성장의 견고한 바탕이 될 수 있음을 시사한다."
  },
  {
    "date": "2026-06-04",
    "title": "미국 SMR 개발사들 협력 파트너십 발표",
    "summary": "Day & Zimmermann이 Deep Fission의 Gravity 원자로 건설 계획을, Sciaky가 NX Atomics의 SMR 플랫폼 부품 제조를 각각 맡기로 했다.",
    "cat": "기술",
    "type": "General",
    "dev": "Deep Fission, NX Atomics",
    "region": "US",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/us-smr-developers-announce-partnerships",
    "summaryLong": "미국의 건설 및 제조 기업들이 소형모듈원자로(SMR) 개발사들과 전략적 파트너십을 체결했다. Day & Zimmermann은 Deep Fission의 Gravity 원자로 건설 계획을 주도하고, Sciaky는 NX Atomics의 SMR 플랫폼 부품 제조를 담당하기로 합의했다. 이는 미국 SMR 산업의 상용화 가속화를 위해 설계 기업과 건설·제조 인프라를 연계하는 의미 있는 움직임이며, 향후 SMR 프로젝트의 실현 가능성을 높이는 데 기여할 것으로 예상된다."
  },
  {
    "date": "2026-06-04",
    "title": "Holtec 파트너십, Blue Castle 유타 SMR 프로젝트 재개",
    "summary": "Blue Castle 프로젝트가 Holtec International과의 파트너십으로 유타주 소형모듈원자로 시설로 재추진된다.",
    "summaryLong": "Blue Castle 프로젝트가 글로벌 원자력 솔루션 기업 Holtec International과의 파트너십을 통해 유타주 소형모듈원자로 사업으로 재추진되고 있다. Holtec의 기술력과 프로젝트 운영 경험이 결합되면서 사업의 구체화 속도가 높아질 것으로 보인다. 이는 미국 내 여러 주(州)에서 진행 중인 SMR 프로젝트의 다양한 추진 경로를 보여주며, 지역 에너지 수요 충족을 위한 실질적인 대응책으로 평가된다.",
    "cat": "기술",
    "type": "General",
    "dev": "Holtec",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE1EbUY4UFc2ZUw2bU92b1J1bnlBQzNiT25BNVNaTEVYblNnejdsVHd2T084T2hCUkFQMXRockRXeVN4RjBUYTZ2R2ZwbXJ1RWtiLU10RFptNzZTSHQ2S2ZpWGhkWGhBVnZVQk1N?oc=5",
    "k": "blue castle nuclear project in utah revived as small modular reactor facility in partnership with holtec international"
  },
  {
    "date": "2026-06-04",
    "title": "TerraPower, 미국 첫 상용 SMR 건설 착수",
    "summary": "TerraPower가 와이오밍에서 미국 최초의 상용 소형모듈원자로 건설을 시작했다.",
    "summaryLong": "TerraPower가 와이오밍주에서 미국 최초의 상용 소형모듈원자로 건설을 공식 착수함으로써 미국의 차세대 원자력 기술 도입이 현실화 단계에 진입했다. TerraPower의 이 프로젝트는 전 세계 SMR 개발 경쟁에서 미국의 선도적 위치를 보여주는 상징적 사건이다. 성공적 완공 시 향후 미국과 국제사회의 SMR 보급 확대에 실질적인 기준점이 될 것이며, 관련 산업 생태계 활성화를 견인할 수 있을 것으로 전망된다.",
    "cat": "기술",
    "type": "General",
    "dev": "TerraPower",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxOTUp2UFIxUDRDdmRfS0Fidi1aY01lT2NrRjhfODhrNVl5WTRFSVNlV2RYRWhnSHloZnJYXzQxdV9CU2Jfbk9EVVRxbmJpY0ZOWnQ5cm41SjVTMGhKRUVtWHowOHNnNE9NQUwtRlVsd2dhM2wyN3l2Tmh2SDJwNkJwVXpvNzg?oc=5",
    "k": "terrapower starts first u s commercial smr construction in wyoming"
  },
  {
    "date": "2026-06-04",
    "title": "미국 SMR 개발사들 파트너십 발표",
    "summary": "미국의 소형모듈원자로 개발사들이 파트너십을 체결했다.",
    "summaryLong": "미국의 소형모듈원자로 개발 기업들이 산업 활성화를 위한 파트너십을 체결했다. 개별 기업의 기술 개발을 넘어 협력 네트워크를 구축함으로써 설계, 건설, 규제 대응 등 전 영역에서 시너지를 창출하려는 움직임이다. 이러한 산업 내 협력 강화는 SMR의 상용화 시간 단축과 비용 경감을 가능케 하며, 미국 SMR 산업의 글로벌 경쟁력을 높이는 데 중요한 역할을 할 것으로 예상된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxNdmtuLWdRQmM3UnVoUEtvMms3MnJtMnppcDdiZDN0U2RZczlmTVZGQWhXcnZkNXBOQjZINFpXVnJXQXE2dm1wenNFdkZkXzAyZlBWNGw3aW5xc2w0QkZpRnQ3blo5NS1PekNySFMyNDg3VWpPa2gtb0VacmJXT3NfV29qZEpjRm51N2pV?oc=5",
    "k": "us smr developers announce partnerships"
  },
  {
    "date": "2026-06-04",
    "title": "미국 기업의 300MWe 소형모듈원자로 개발",
    "summary": "미국 기업이 300MWe 규모의 소형모듈원자로를 개발하여 핵심 프로젝트에 전력을 공급할 예정이다.",
    "summaryLong": "미국 기업이 300MWe 규모의 소형모듈원자로를 개발하여 산업 및 에너지 집약 시설의 전력 수요를 충족할 계획이다. 300MWe 수준의 전력 규모는 대규모 중앙 집중식 발전소보다는 작지만 지역 산업 시설의 효율적인 전력 공급에 적합한 수준이다. 이는 탈탄소화 요구가 높은 산업 분야에 SMR이 실질적인 솔루션으로 자리 잡도록 하는 중요한 기술 진전이며, 향후 여러 산업군으로의 SMR 확대 보급의 초석이 될 것으로 전망된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxNQUJ3ZGpJN0J4YnRObTVSTjlHX1MzbVZ2ZzVWMlpTblo1T21KWVlodGZVWEtoUVpMRlZON1FsdGxsSXg2UFRSSnA0ODh4NUMtcGJjQnJXRURKZU9IZGRhcHlCcVM2Xy1TZ0xwcXBNR0xiMEFxa1NXak55amtDOVl0Ql9pMmtBRTI0TUdWZHJB?oc=5",
    "k": "us firm s small modular reactor that generates 300 mwe electricity to power nuclear project"
  },
  {
    "date": "2026-06-04",
    "title": "NX Atomics와 Sciaky, 소형모듈원자로 부품 제조 기술 협력",
    "summary": "NX Atomics와 Sciaky가 EBAM 기술을 소형모듈원자로 부품 제조에 적용하기 위해 협력한다.",
    "summaryLong": "NX Atomics와 Sciaky가 적층제조 기술인 EBAM(Electron Beam Additive Manufacturing)을 소형모듈원자로(SMR) 부품 제조에 도입하기 위한 협력을 시작했다. 이는 SMR의 제조 효율성 및 경제성 향상을 목표로 한다.",
    "cat": "기술",
    "type": "General",
    "dev": "NX Atomics, Sciaky",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxOV0lJNFJYLXhLeTlFX2RJSGFQenl6N2poaTFqQWhwbE9VQWNTMWRud2EzSHFKbHNoZ1JxNWxnSjhkQ0wzLU10UFVFME5BTlN3eWcyYVBoNWNja01kcDZPWlVVS2xGYTRjSzNXX0RqbUxVaVdUMG5Sc24yUzhfQ0ZWdzVqMVBmU0RYR2luVFhHNmFqZEhPYzNOelNuejZySXfSAaQBQVVfeXFMTmZzVV92MUp2d1l2UTZUVVBhVzRSdHRSWF93eVZWOUtFN081c3hDT1pzY2hWOEE1emp3aWhFLW9BODBZYlVnUGdxQTIwM3U5NWNPUXFnTEtBQkVGLVVkWnhndmdvdWpOZE1nZGNDbnJsT1A2Q0dwQ1EtTW1Ya0tMaXUydVFxUXhmUXNQVVNJejBEVDZpY1lGOVJYWmhQMkgxVHZxbng?oc=5",
    "k": "nx atomics and sciaky bring ebam to small modular reactor components"
  },
  {
    "date": "2026-06-04",
    "title": "우즈베키스탄, 소형모듈원자로 건설 승인",
    "summary": "우즈베키스탄이 소형모듈원자로 건설을 공식 승인했다.",
    "summaryLong": "우즈베키스탄이 공식적으로 소형모듈원자로 건설을 승인함으로써 중앙아시아 지역의 원자력 기술 도입이 본격화되고 있다. 에너지 독립성 강화와 탄소 감축을 목표로 하는 우즈베키스탄의 이번 결정은 비(非)OECD 국가의 SMR 관심 증가를 의미한다. 이는 SMR이 글로벌 에너지 전환에서 지역별 맞춤형 솔루션으로 인식되고 있음을 보여주며, 향후 신흥국의 SMR 도입 확대에 긍정적 신호로 작용할 것으로 예상된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxPOTVKM2dhLWxCUTF6aHpEeTBBdzVFMkktdVlkNzQ2WjY0Zm5aem1EMUhmeFhnMVFXV3M3cU4tOU0wZlFHY21BT3ozMHRnYmtKZmxPRmttbGdWY1EteEtHSENTVmRQVUNFdFRvYUw4cldtdTlBZjYxNXh6c2FrVzEtczRVNzhqRHY5ejNPbFlFY2hfWmZUSHVnYnNoWnZiQnJTYTZkVXFR?oc=5",
    "k": "uzbekistan approves construction of small modular nuclear power unit"
  },
  {
    "date": "2026-06-03",
    "title": "X-energy, 영국 규제기관에 Xe-100 인허가 신청",
    "summary": "미국의 첨단원전 개발사 X-energy가 고온가스냉각로 Xe-100을 영국 제네릭 설계 평가 절차에 신청했다.",
    "cat": "기술",
    "type": "General",
    "dev": "X-energy",
    "region": "UK",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/x-energy-submits-xe-100-for-uk-regulatory-assessment",
    "summaryLong": "미국의 첨단원전 기업 X-energy가 고온가스냉각로(HTGR) 기술인 Xe-100을 영국의 제네릭 설계 평가 절차에 공식 신청했다. 이는 미국 기업의 혁신 원전 기술이 국제 규제 기준에 적합성을 입증받기 위한 첫 번째 국제 인허가 도전이다. 성공 시 Xe-100의 영국 진출은 물론 유럽 전역의 SMR·첨단원전 시장 진출의 교두보가 될 수 있으며, 국제 원자력 기술 표준화 논의에도 주요 사례를 제공할 것으로 전망된다."
  },
  {
    "date": "2026-06-03",
    "title": "네덜란드 용융염로 테스트 시설 개소",
    "summary": "네덜란드 아인트호펜에 용융염로 기술 개발·테스트를 위한 첨단 시설이 개설되었다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "EU",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/dutch-msr-testing-facility-launched",
    "summaryLong": "네덜란드 아인트호펜에 용융염로(Molten Salt Reactor, MSR) 기술의 개발·테스트 전용 시설이 개설되었다. 용융염로는 기존 경수로와는 다른 냉각 원리를 활용하는 차세대 원자로 개념으로, 안전성과 효율성이 높다는 평가를 받고 있다. 유럽이 이러한 최첨단 시설 구축을 통해 MSR 기술 개발을 가속화함으로써 SMR·첨단원전 분야에서 미국과의 기술 경쟁을 본격화하고 있으며, 향후 유럽의 에너지 전환 전략에 중요한 역할을 할 것으로 예상된다."
  },
  {
    "date": "2026-06-03",
    "title": "알레이마, SMR·첨단로 수요 대비 생산 확대",
    "summary": "스웨덴 알레이마가 샌드비켄에 신규 튜브밀 시설을 개설해 SMR·첨단로 부품 공급 체계를 강화했다.",
    "cat": "기술",
    "type": "General",
    "dev": "Alleima",
    "region": "EU",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/alleima-expands-capacity-as-nuclear-demand-grows",
    "summaryLong": "스웨덴의 알레이마(Alleima)가 샌드비켄에 신규 튜브밀 시설을 개설함으로써 소형모듈원자로(SMR)와 첨단원자로 부품 공급 역량을 대폭 확대했다. 이는 전 세계적으로 SMR 상용화 시장이 성장하면서 관련 부품에 대한 수요가 증가함에 따른 선제적 대응이다. 알레이마의 생산 시설 확충은 유럽 지역 SMR 프로젝트 추진에 필요한 공급망 안정화에 기여할 것으로 예상된다."
  },
  {
    "date": "2026-06-02",
    "title": "혁신형 SMR, CRDM 검증 과제 직면",
    "summary": "NuScale을 포함한 혁신형 SMR이 통제봉구동기구(CRDM) 검증이라는 인허가 과제를 안고 있다.",
    "summaryLong": "NuScale 등 혁신형 소형모듈원자로들이 규제 허가 과정에서 통제봉구동기구(CRDM, Control Rod Drive Mechanism) 검증이라는 새로운 과제에 직면해 있다. CRDM은 원자로 안전성에 필수적인 핵심 부품으로, 기존 대형 원자로와 다른 설계 사양을 가진 SMR의 경우 별도의 검증 절차가 요구되고 있다. 이 과제의 해결 정도가 향후 혁신형 SMR의 인허가 일정에 영향을 미칠 것으로 보인다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "KR",
    "source": "\"SMR 원자력\" - Google 뉴스",
    "url": "https://news.google.com/rss/articles/CBMibEFVX3lxTE1vOEZqZmJHQ2QxdHMwdlQwT2psVWp1MV85WVRMWE9fZHVWaW15T3JqcUJoZ1plQW1kQlJnckJZYjZQenhZQmo5Y3lWeVRVaXljUVZWMFVqcUxoNmJEeG1ZalNEdnVDanV3QkpLadIBcEFVX3lxTE43ZzRzVjRfQlgyN3Q5aWU5Smx0dU40VXB3ZVVDY1Q3WTVoYUJjNWhGUi1nU1Qxak1OMXFkTmNlWFlpUDN5TTh5UUQ0b3NwSXVCZnJqd0wtMUV1OEtjWFZvVmJZb2w0N081Y0FRaGlia1A?oc=5",
    "k": "뉴스케일도 거친 crdm 검증 혁신형 smr도 도전장"
  },
  {
    "date": "2026-05-29",
    "title": "유타 그린리버 SMR 프로젝트 합작사 출범",
    "summary": "Fulcrum Point Holdings과 Blue Castle Holdings이 홀텍의 SMR-300 기술을 이용한 유타주 SMR 건설 프로젝트 추진을 위해 합작사를 설립했다.",
    "cat": "계약",
    "type": "General",
    "dev": "Holtec",
    "region": "US",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/nineteen-years-on-companies-team-up-for-us-new-build-project",
    "summaryLong": "미국의 Fulcrum Point Holdings과 Blue Castle Holdings이 합작사를 설립하여 유타주에서 홀텍(Holtec)의 SMR-300 기술을 활용한 소형모듈원자로 발전소 건설 프로젝트를 추진하기로 합의했다. 이는 미국 내 SMR 상용화 프로젝트가 본격적인 사업 단계로 진입하고 있음을 보여주는 사례이다. 이번 프로젝트를 통해 홀텍의 SMR-300 기술이 실제 프로젝트에 적용되는 첫 사례가 될 것으로 기대된다."
  },
  {
    "date": "2026-05-29",
    "title": "미국 정부, 소형모듈원자로 기술 장려",
    "summary": "미국 정부가 소형모듈원자로 기술을 대외적으로 홍보하고 있다.",
    "summaryLong": "미국 정부가 소형모듈원자로(SMR) 기술의 개발과 상용화를 적극 지원하기 위해 대외적인 홍보 및 장려 활동을 펼치고 있다. 이러한 정책적 추진은 에너지 안보와 탄소 중립이라는 국가 전략 목표 달성의 맥락에서 추진되고 있다. 미국 정부의 이러한 노력은 국내 SMR 기업들의 기술 개발 및 프로젝트 추진에 긍정적인 환경을 조성하고 있다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMijwFBVV95cUxNQ3k0MFFtZUVDZ01RSlFTRENvaktLb0QtSHAwTFVudV8xdWhJYm1PejNTYW0xcF9UWEhHNU1mSF9CNk1YX3pPZ0pwV0ZsUWgzc3JmclotNEprU2pjT2s0ZjlvQ1lHZ182bHBDR2ZNUG4zYU9iYTVfejJ5ZG9xOWFKSDBiZUJpbWVmTjNySjlicw?oc=5",
    "k": "u s government promotes small modular reactor smr technology"
  },
  {
    "date": "2026-05",
    "title": "NRC, Dow(Long Mott) Xe-100 환경평가(EA) 완료",
    "summary": "건설허가 신청의 일부로 NRC가 약식 EA 완료 — 상업 첨단로 첫 사례. CP 승인은 2027 Q1 예상.",
    "cat": "인허가",
    "type": "HTGR",
    "dev": "X-energy",
    "region": "US",
    "source": "NRC Long Mott",
    "url": "https://www.nrc.gov/reactors/new-reactors/advanced/who-were-working-with/applicant-projects/long-mott",
    "summaryLong": "미국 원자력위원회(NRC)가 X-energy의 Xe-100 첨단원자로 프로젝트에 대해 건설허가 신청의 일부로 약식 환경평가(EA)를 완료했으며, 이는 상업용 첨단로 분야에서 처음 이루어진 사례이다. 건설허가(CP) 승인은 2027년 1분기로 예상되고 있어, X-energy의 Xe-100이 상업화 단계로 한 걸음 더 나아가고 있다. 이는 혁신형 원자로의 규제 승인 경로가 점차 구체화되고 있음을 시사한다."
  },
  {
    "date": "2026-05-28",
    "title": "롤스로이스 SMR, 슈코다·두산에너빌리티와 핵심 부품 계약",
    "summary": "롤스로이스 SMR이 원자로 압력용기 등 핵심 부품의 사전 생산 작업을 슈코다 JS와 두산에너빌리티에 발주했다.",
    "cat": "기술",
    "type": "General",
    "dev": "Rolls-Royce",
    "region": "UK",
    "source": "World Nuclear News",
    "url": "https://www.world-nuclear-news.org/articles/skoda-js-doosan-enerbility-get-key-rolls-royce-smr-work",
    "summaryLong": "영국의 롤스로이스 SMR이 원자로 압력용기 등 핵심 부품의 사전 생산 작업을 체코의 슈코다 JS와 한국의 두산에너빌리티에 발주했다. 이는 롤스로이스 SMR의 상용화를 위한 공급망 구축이 구체적으로 진행되고 있음을 보여주며, 국제 협력을 통해 필요한 부품 공급체계를 미리 확보하려는 전략적 움직임이다. 양사와의 협력은 향후 SMR 대량 생산 단계에서의 안정적인 부품 공급 기반이 될 것으로 예상된다."
  },
  {
    "date": "2026-05-28",
    "title": "i-SMR 경주 유치, 주민수용성 확보가 핵심",
    "summary": "경주시 정책 자문관이 혁신형 i-SMR 유치 성공의 핵심을 주민수용성으로 지적했다.",
    "summaryLong": "경주시 정책 자문관이 혁신형 i-SMR 프로젝트의 성공적 유치를 위해서는 지역 주민들의 수용성 확보가 가장 핵심적인 과제라고 지적했다. 이는 원자력 프로젝트 추진 시 기술적·경제적 요소뿐만 아니라 지역 공동체와의 신뢰 구축이 얼마나 중요한지를 보여주는 발언이다. 주민수용성 확보는 장기적인 사회 소통과 투명한 정보 공개를 통해서만 가능하며, 이것이 프로젝트 성공의 필수 조건임을 강조하고 있다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "KR",
    "source": "\"SMR 원자력\" - Google 뉴스",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTFBMMk5nQUNjZ2VtQlBsb3I4bERRbWJQZXBfVW96MXlRTUotYXAyUUZPeG51RDlRMjJkY3NkTUZPbVpINndJMjlhTkZDVGtKYlBmLWVVWkNybmFKMGJkdW90dVBEakpLQQ?oc=5",
    "k": "기고 이재근 경주시 원자력정책 자문관 혁신형 i smr 경주유치는 주민수용성이다"
  },
  {
    "date": "2026-05-26",
    "title": "스웨덴 SMR 발전소, 세 번째 인허가 신청 제출",
    "summary": "스웨덴에서 세 번째 소형모듈원자로(SMR) 발전소 건설에 대한 규제 신청이 접수되었다.",
    "summaryLong": "스웨덴에서 세 번째 소형모듈원자로(SMR) 발전소 건설을 위한 규제 신청이 관할 당국에 접수되었다. 이는 스웨덴이 SMR 기술 도입을 통해 에너지 전환과 탄소 감축 목표를 달성하려는 의지를 보여주는 사례이다. 스웨덴의 연속적인 SMR 프로젝트 추진은 유럽 지역에서 혁신형 원자로 기술 확산의 모범 사례가 될 수 있을 것으로 예상된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "EU",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxOVDBOT1BETGh0bXZBR2UtNTVycWl2VFQtbnVuUXZPVG1OdVFmN0RGdS05SmI2bURVQ0gxTGhNTjVqcVZaV09fcXpkbXVTSV8wNXJEb2hRWmxuVm5UZjhoMU9Tb25pMW9BNE9FNnhQSmV1MjdhVmhBY0NrcXJ6S3hVS3FmNG9mZE5XTTFuNkFtaFV6Nno4?oc=5",
    "k": "third application lodged for swedish smr plant"
  },
  {
    "date": "2026-05-21",
    "title": "미국 NPPD, 서덜랜드 지역 SMR 사이트 선정 진행",
    "summary": "미국 네브래스카 전력공사(NPPD)가 소형모듈원자로 입지 선정을 추진 중이며, 서덜랜드가 주요 후보지로 검토되고 있다.",
    "summaryLong": "미국 네브래스카 전력공사(NPPD)가 소형모듈원자로(SMR) 건설을 위한 입지 선정 절차를 진행하고 있으며, 이 과정에서 서덜랜드 지역이 주요 후보지로 검토되고 있다. 이는 지역의 전력 수급 안정성과 산업 경쟁력 강화를 목표로 한 전략적 결정으로 평가된다. NPPD의 SMR 도입 추진은 미국 전력회사들이 탄소 중립과 에너지 독립성 확보를 위해 차세대 원자력 기술을 적극 도입하려는 흐름을 반영한다. 향후 상세한 입지 평가와 지역사회 동의 과정을 거쳐 프로젝트가 구체화될 것으로 예상된다.",
    "cat": "기술",
    "type": "General",
    "dev": "NPPD",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxQUTZBWmF4aWpFOVlRZDBuaWRsWEhYdERPNnYyUk8yRm1MT1MyMWtDbGpKZm1IelB4SmhOT3NqYmN2UEt0NVRGNXA5NnMyZzhYV0loeXBvaUFVUkZrMFVEcEQyai1UdmMwdmNwVGR6Sl80cHBvV2hXT3IwNU8yOWc1Y1Rkd1ljOHVHSVVpZ0JxZGtCeXZ0akxLa21yeElmeEstWkVzMnNudDczSlBIdkp3TkdyX1RYMlpuNl91bTZ2amtoVFBGcGtCMlFldkJqODlkaUxVetIB6AFBVV95cUxQZmpjeUl4ZTJYTV9PZ0I4UnptSkgzeXNuY0huanNhLTFTdURsYXJWSmFXVEhrVGV5RzFHWGx2Rm1NX2I3c1h0VFIzRVVObmhHd2cyVWg3em5pQVdFLWpUS0ZsQzd6YTNmSzFiMV9vSVZHTkMzM28tdUtYaVFJQ1VzZW5oUzJrUS01MjBGZzdzQzNfbkVGVE9GaUxDV1g4ZGRibDhwZkk0dGlyVkFYZlZ5aF9hQWR4OE93enNlSU1xN3hPeXNMaGRBSEU3Y2YyeDFHZEp2UVBWZGNFVjF6TUdaT1ZidUlyVXlh?oc=5",
    "k": "continuing coverage lincoln county leaders push for sutherland as nppd small modular reactor search narrows"
  },
  {
    "date": "2026-05-20",
    "title": "NPPD, 네브래스카주 4개 지역을 소형모듈원자로 후보지로 선정",
    "summary": "NPPD가 네브래스카주 내 4개 지역을 소형모듈원자로 건설 후보지로 공식 지정했다.",
    "summaryLong": "NPPD가 네브래스카주 내 4개 지역을 소형모듈원자로 건설의 공식 후보지로 지정함으로써 미국 내 SMR 배치 계획이 구체적 단계로 진입했다. 이는 단순한 탐색 단계를 넘어 실질적인 사업 추진 의지를 보여주는 조치로, 각 후보지에 대한 환경영향평가 및 경제성 검토가 후속될 것으로 보인다. NPPD의 이번 결정은 소형모듈원자로가 지역 전력망 안정화와 장기적 에너지 수급 대책의 중요한 수단으로 인식되고 있음을 시사한다. 최종 입지 선정까지는 규제 승인, 지역사회 협의 등 다양한 절차가 필요할 것으로 예상된다.",
    "cat": "기술",
    "type": "General",
    "dev": "NPPD",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxOYmc5cmFKOU54VTFxM3RudjQyM0wwZE5nS3JEVldjLUtvUEN4LThhc2NaNDdjUG80TGZvV25IZWxObHJsS1R4LXVkbURYU1dGMzZJNUMzTkZwUmZrR0U4d2ZIMVVPSk9na0tvQzcwSlU5a1doNHM3T09PM0ZMdmY0eEgyM3BNYkNSTjFuQVBNc3JuSmpfVnhrRUkwOXRSRy15SGN4YTR1ZDlsVWVzNzlhQlNYekg?oc=5",
    "k": "nppd identifies 4 nebraska communities as potential small modular reactor sites"
  },
  {
    "date": "2026-05-20",
    "title": "NPPD, 네브래스카 4개 지역을 소형모듈원자로 부지로 선정",
    "summary": "미국 네브래스카 공공전력지구(NPPD)가 소형모듈원자로 건설을 위한 잠재적 부지로 4개 지역사회를 식별했다.",
    "summaryLong": "미국 네브래스카 공공전력지구(NPPD)가 소형모듈원자로(SMR) 도입을 추진하며 네브래스카 내 4개 지역사회를 잠재적 건설 부지로 선정했다. 이는 미국 중서부 지역의 SMR 배치 확대를 위한 구체적 단계로, 지역 전력 공급 다양화와 에너지 전환을 목표로 한다.",
    "cat": "기술",
    "type": "General",
    "dev": "NPPD",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxNb1V1ZVRpTDB1OUdtMG1NeWdxaWNYT1BvUWE2VVJxdF9pbkU3b2dRVUcwajNYUGhoNFNkY0ZjWnlsNzAwalVNZmVVZ1h5UUdNejN6M3g2VmplT1ZXYkVfMnNOYWwxRTkxcU8xNnlDNTRTYlBMcnVHUmRDYTBlYUtpSjVMTXJZUDdTYXFuTHF4YUxDVXRHN01uNkgzd2U5YlRyNHRRNUE0cnZLLTA2V2FoeTdCOEZKSl9XdHc?oc=5",
    "k": "nppd identifies 4 nebraska communities as potential small modular reactor sites koln nebraska local news weather sports"
  },
  {
    "date": "2026-05-15",
    "title": "DOE, 소형모듈원자로 배치 가속화를 위해 8개사에 9,400만 달러 지원",
    "summary": "미국 에너지부(DOE)가 소형모듈원자로 배치 가속화를 위해 8개 기업에 총 9,400만 달러를 지원한다.",
    "summaryLong": "미국 에너지부(DOE)가 소형모듈원자로의 시장 배치 가속화를 목표로 8개 기업을 대상으로 총 9,400만 달러 규모의 지원금을 배분하기로 결정했다. 이는 미국 정부가 SMR 기술 개발에서 상용화 단계로의 전환을 촉진하려는 정책적 의지를 명확히 드러낸 것으로, 선별된 기업들이 설계 개선, 인허가 지원, 건설 준비 등 다양한 영역에 자금을 활용할 것으로 예상된다. DOE의 대규모 지원은 SMR이 미국의 에너지 안보 전략과 탄소 감축 목표 달성의 핵심 기술로 평가받고 있음을 보여준다. 이러한 정부 지원이 민간 투자 활성화로 이어져 향후 SMR 프로젝트 추진이 가속화될 것으로 전망된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMif0FVX3lxTE5RTUVJaUpaNUVKSWliWDNuUXdmNXZmVTRzTXI5cG81VThFY3B1aUlNZ19maVN4c25tRGZRZHNReTNqaE1Ic3VOY1UxcG85c0NYemVpbWpUU1FXTGlzNm9xSlNLOEw5YmR0djE4TUtST1VWUFhHWXllT3lXNEhnZzQ?oc=5",
    "k": "doe awards 94m to 8 companies to accelerate small modular reactor deployment"
  },
  {
    "date": "2026-05-11",
    "title": "SMR, 기술이 아닌 경제성에서 경쟁력 부족",
    "summary": "분석 기사에서 SMR의 경제성 문제가 기술 문제보다 더 심각한 것으로 지적되었다.",
    "summaryLong": "소형모듈원자로 분야의 주요 분석 기사에서 SMR의 가장 큰 난제가 기술 개발이 아니라 경제성 확보에 있다는 점이 지적되었다. 현재 SMR은 설계 및 원형 개발 단계에서는 기술적 타당성을 입증했으나, 대량 생산 단계에서의 비용 경감 방안이 여전히 불명확한 상태이다. 이는 기존 대형 원자로 대비 높은 단위당 발전 비용 구조를 개선해야 SMR이 경제적 경쟁력을 갖출 수 있음을 의미한다. 향후 SMR 산업의 성공은 기술 혁신보다는 생산 표준화, 공급망 구축, 규제 비용 절감 등 실질적 경제 구조 개선에 달려있을 것으로 분석된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxNOWkwVnA5V0VBRVUwSXF4YzNjTnExX1VneHNMcVpxUzBaNG5KeGFnZU9mRXVnZmlWQkhBczhTX0RaenUzSGxfNjlWLVFXMDZQLW9mOFdEcUgyUmNmZmpGTVJ4bnZxV3E5aHNwZ0pNWGxFeWxkSWZ0NXJmQlZHTGFHc3U5bzNxZldnMTdDUWxGT2dtTW9IOWlwY3lraEwwc0gyYzE1M3FkdVZ6WVl3MGNFOTZETkpIRmRR0gG-AUFVX3lxTE5JQnVoVTNFMlFBSGR5MkRLTEdKUWloZlB3a1FRbFByZWdxTkd4Nkl6UVc1RVpnQWIyVjFnaDUzUDJ5TUluMlBtSGFPTXJ4RGcxcEFpZEtMR2tNbHNSb2t6YkdYQWRhbjVMZnlQWXNwaUxYSVZJb191RnIyaV9xYjZkSkxja0l4YUx2ZXppNXdMYTB0N1JJdW1ZeUl2UGVKRFhDRlV5bkNDb19oY0l0SllGaUt0TWdwbFJLZ2RyMGc?oc=5",
    "k": "smrs aren t losing on technology they re losing on economics crude oil prices today"
  },
  {
    "date": "2026-05-01",
    "title": "LG&E and KU, 소형모듈원자로 도입 검토",
    "summary": "미국 전력회사 LG&E and KU가 소형모듈원자로 도입 가능성을 탐색 중이다.",
    "summaryLong": "미국 전력회사 LG&E and KU가 소형모듈원자로의 도입 가능성을 검토하기로 결정함으로써 주요 민간 전력사들의 SMR 수용 관심이 점차 확대되고 있다. 이는 기존의 정부 주도 사업 추진 흐름에서 민간 전력회사의 실질적 수요가 반영되는 중요한 신호로 평가된다. LG&E and KU의 검토 대상은 지역 전력망의 안정화, 노후 석탄 발전소의 대체, 장기적 탄소 감축 목표 달성 등이 될 것으로 예상된다. 주요 전력회사의 이러한 움직임이 추가 도입 검토 사례를 촉발할 수 있어, 향후 미국 내 SMR 프로젝트 파이프라인 확대에 긍정적 영향을 미칠 것으로 보인다.",
    "cat": "기술",
    "type": "General",
    "dev": "LG&E and KU",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxNT3A1N3ZfV0tjekJmSzhLalpNU3N1bm11WVFpOWhzOVRxX2tEUWt1ZmRNWnFuRXVyaXVzZG1EdEFmNnZTZVBieTIyUlRSbWkwMWNCU2tGUlBZRDhPTEkzcVgwdUpYODF1dExwZXZyM0VONGVYeHdrOVM2d3E5RFBoZzAxWlQzLUlSalhTSlZ3SFNvWU5GQ3ExNmRQQ1c2bGo0dkpwYXAtZlRlWVE?oc=5",
    "k": "lg e and ku exploring use of small modular reactor nuclear energy"
  },
  {
    "date": "2026-04-29",
    "title": "NRC Part 53(첨단로 전용 트랙) 발효",
    "summary": "위험정보·성능기반·기술포괄 신규 인허가 트랙 발효. 현재 신청자 0건 — 향후 비경수로 SMR의 대안 트랙.",
    "cat": "정책",
    "type": "General",
    "dev": "NRC",
    "region": "US",
    "source": "Federal Register 2026-06048",
    "url": "https://www.ecfr.gov",
    "summaryLong": "미국 원자력규제위원회(NRC)가 '첨단로 전용 트랙(Part 53)'의 정식 발효로 비경수로와 소형모듈원자로에 적합한 신규 인허가 기준을 도입했다. 새 규제 트랙은 위험정보 기반 평가, 성능 기반 요구조건, 기술 포괄성 등의 특징을 갖추어 기존 경수로 중심 규제의 경직성을 완화하는 것을 목표로 한다. 현재 공식 신청 사례가 없다는 점은 개발사들이 여전히 설계 완성도 향상과 상용성 검증에 집중 중임을 시사한다. 향후 개발 진도가 진전되면서 Part 53 트랙을 활용한 인허가 신청이 증가할 것으로 전망되며, 이는 SMR의 규제 환경 개선과 시장 진입 가속화로 이어질 것으로 기대된다."
  },
  {
    "date": "2026-04-29",
    "title": "Aker Solutions, Rolls-Royce SMR MOU 체결",
    "summary": "Aker Solutions가 Rolls-Royce SMR과 소형모듈원자로 에너지 프로젝트 MOU를 체결했다.",
    "summaryLong": "영국 소형모듈원자로 개발사인 Rolls-Royce와 노르웨이 해양 솔루션 기업인 Aker Solutions가 SMR 에너지 프로젝트 추진을 위한 양해각서(MOU)를 체결했다. 이는 Rolls-Royce의 기술력과 Aker Solutions의 산업 인프라 및 국제 네트워크를 결합하여 SMR의 상용화와 글로벌 배치를 가속화하려는 전략적 협력을 의미한다. 양사의 협력은 SMR이 단순한 발전 기술을 넘어 해양, 산업 에너지 등 다양한 분야로 활용 범위를 확대하고 있음을 보여준다. 이러한 국제 기업 간 협력이 확대되면서 SMR의 기술 표준화와 공급망 구축이 촉진될 것으로 예상된다.",
    "cat": "계약",
    "type": "PWR",
    "dev": "Rolls-Royce",
    "region": "UK",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxNMWVQY0J3OG9IOGU1THpNQlMzSDI2blE3NXVudWZoSS1XcDg3QUx2VTR2LUVWbE5qbVB3UlhZYTNMNW8wR0dIa3QwNFV3V0t3UUJTWVNka01HM1NscGhJLU5VaHlxcWUxWFJBVm04NE03U21yRHhmeXoxUERWQWJnM0JwRUIwMTRxdUVJV1hIX2ktYXBHOFRfZ1JIcGEzbjRkVkQyWUlNd1MwZGtibzNJWXIzeTAwdVg4SEJSTGFZZG1uZlRIT3hpNGo2dHJ3Ylp0VEV2WjExTEs?oc=5",
    "k": "aker solutions signs mou with rolls royce smr for small modular reactor energy projects"
  },
  {
    "date": "2026-04-27",
    "title": "X-Energy IPO 후 1.5배 급등, AI 전력 수요 견인",
    "summary": "SMR 개발사 X-Energy가 IPO 직후 1.5배 상승하며 AI 전력 수요 증가에 주목받고 있다.",
    "summaryLong": "SMR 개발 기업 X-Energy가 기업공개(IPO) 직후 주가가 1.5배 상승하면서 시장의 강한 관심을 입증했으며, 이는 인공지능(AI) 데이터센터의 급증하는 전력 수요에 대한 기대감이 반영된 결과로 분석된다. AI 산업의 확대에 따른 전력 부족 우려가 SMR과 같은 소형, 분산형 청정 에너지원에 대한 투자 수요를 창출하고 있다. X-Energy의 성공적 상장은 SMR 부문의 투자 매력도가 상승하고 있음을 신호하며, 관련 기업들의 자본 조달 환경 개선을 의미한다. 향후 AI 전력 수요의 지속적 성장이 SMR 개발사들의 사업 확장과 기술 투자 가속화를 견인할 것으로 전망된다.",
    "cat": "투자",
    "type": "HTGR",
    "dev": "X-Energy",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxQckpjQURJcGVEb1ZEcWhvUWt0cW9uaEpOTXltNzhkcDBXZlJWSzFhUzFEckRZcG41eUZnWW5xRHJXMnpCSEJBMmJrcTRvdkN3QTVPcFk5TTRPX3FHREIyam05WTk1ZkwwVUJidTNBSzlRdE5sLUZFOFR1UWdkZGRtV19Wa3VEcFpYU3hNY0xiMzl2ckVNblJPTmZZUFVFZ2o5THJaMnMwUTEzSXRwWEpMeFdWTQ?oc=5",
    "k": "small modular reactor stocks soaring x energy surges 1 5x right after ipo is ai power hunger accelerating capital shifts spillover effects on related stocks"
  },
  {
    "date": "2026-04-24",
    "title": "X-Energy, SMR 개발사 최초 IPO 성공",
    "summary": "소형모듈원자로 개발사 X-Energy가 공모가 범위를 초과하여 주당 $23에 IPO를 실시했다.",
    "summaryLong": "소형모듈원자로(SMR) 개발 업체인 X-Energy가 공모가 범위를 상회하며 주당 23달러에 기업공개(IPO)를 성공적으로 완료했다. 이는 SMR 전문 개발사 최초의 IPO 달성으로, 민간 원자력 시장에 대한 투자자들의 관심과 신뢰를 보여주는 중요한 신호다. X-Energy의 성공적인 상장은 소형모듈원자로 산업이 기술 검증 단계를 넘어 상용화 단계로 진입하고 있음을 의미하며, 향후 유사 기업들의 자본 조달 경로를 개척하는 역할을 할 것으로 예상된다.",
    "cat": "투자",
    "type": "General",
    "dev": "X-Energy",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMizgFBVV95cUxPdk5MNlJqUk11MUJTaXRwVThhenB4b0d6S3BVNW8yWjFUc1pLMU9Vd08yWVFjWjlLYUJKUi1ZVnZjX2w4X00tYnpRSGlYTDRrbjN6UGlYLWhSZy1aMFJKaU9KeWpwRUg5ckN0X0VpQm1oUl9Zd004VUxmRTNRdzZSVExPdkRTZDdmWmlFeS1hSkRCOU5fUVVwNVRiNXJlUndMcmxiYzljQmJybjhWYkdENnRqNWladURmdlNhM1I2M0h5RDhWSjZDeWFVVEtqUQ?oc=5",
    "k": "xe ipo news small modular reactor developer x energy prices upsized ipo at 23 above the range"
  },
  {
    "date": "2026-04-15",
    "title": "First American Nuclear, 고속 스펙트럼 SMR 규제 협력 계획 제출",
    "summary": "First American Nuclear이 고속 스펙트럼 소형모듈원자로(SMR)에 대한 규제 협력 계획을 규제당국에 제출했다.",
    "summaryLong": "First American Nuclear이 자체 개발 중인 고속 스펙트럼 소형모듈원자로(SMR)에 대해 규제당국과의 협력 계획을 공식 제출했다. 이는 설계 인증 및 인허가 프로세스 진행을 위한 첫 단계로, 규제기관과의 상세한 협의 일정과 기술 검토 방안을 포함한다.",
    "cat": "기술",
    "type": "SFR",
    "dev": "First American Nuclear",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMi7gFBVV95cUxPaEJEQmhDNVNlaE1MNWRBY2hlc0plaWxNd1FzMVRoYkhkaTZnQmpRZVUzMHliRUlZSGtvN3Z0VVBlMW11SzdQNGJMOUV6dG56YWJyRTFKSE9YbjdnUS11YURJRldsei05bUhlMEJDUHItTmhBbkxhZHVYa3NFUFZma2VnT3pEa0o3U2RrS2laTU5hN0duaXNnX1FMdkw1SUtBU2llaktuUDNwMU9IYlVuMVBpOTk4b0R3dS1QMmdEVmd6akV6ZUIzODhQVGhsMkQzcmVvRUJfNkNYV2cxOTE1QzBnVEw1ZVo4NTNMeFFn?oc=5",
    "k": "first american nuclear submits regulatory engagement plan for fast spectrum small modular reactor smr"
  },
  {
    "date": "2026-04-06",
    "title": "Fluor, X-Energy와 텍사스 첨단원전 계약",
    "summary": "Fluor가 X-Energy와 텍사스주의 첨단 소형모듈원자로 프로젝트 계약을 체결했다.",
    "summaryLong": "대규모 엔지니어링 및 건설 기업인 Fluor가 X-Energy와 텍사스주의 첨단 소형모듈원자로 프로젝트 계약을 체결했다. 이 계약은 SMR 기술의 실제 프로젝트 적용 확대를 의미하며, Fluor의 건설·엔지니어링 역량과 X-Energy의 기술력이 결합되는 사례다. 미국 에너지 수요 중심지인 텍사스 지역에서의 첨단원자로 프로젝트 추진은 지역의 전력 안보와 에너지 전환 전략에 기여할 것으로 기대된다.",
    "cat": "계약",
    "type": "HTGR",
    "dev": "X-Energy",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxQWHhrTVRDOWVPNmJKU0x3M3ZhWHhTaklPN21JMHc1U2VoNjFHMG1OOTdBTEFwdE4zUXVDd2ZvMGxaNXdkenc1WmhyYmVIVXI3WFpzalNPTWRGUkFWcFpNODhrQnJIUEZFdC1aakVaQm1fSUpDRXcwMm42SEkwOFF6cVItd0YyQ0ZXaDdGbEZaN0oycXZRU3RnQUVfcFhSMEREMDZvVDdJZWhfbGU5Mk43UVlkZmVsN08xbWZ0aE9qYWNaZ1dOcHM4TFM2aklLcm50b1psOFhXZlhvZm5R?oc=5",
    "k": "fluor signs contract with x energy for advanced nuclear project in texas"
  },
  {
    "date": "2026-03",
    "title": "TerraPower Natrium 건설허가(CP) 발급 — 첫 상업 비경수로 CP",
    "summary": "NRC가 와이오밍 Kemmerer Natrium에 건설허가 발급. 40여 년 만의 상업용 Gen-IV/비경수로 CP.",
    "cat": "인허가",
    "type": "SFR",
    "dev": "TerraPower",
    "region": "US",
    "source": "DOE",
    "url": "https://www.energy.gov/ne/articles/nrc-issues-construction-permit-terrapowers-natrium-advanced-reactor",
    "summaryLong": "미국 규제당국(NRC)이 TerraPower의 Natrium 원전 프로젝트에 대해 와이오밍주 Kemmerer 지역의 건설허가(CP)를 발급했다. 이는 약 40년 만에 발급되는 상업용 4세대 원자로 건설허가로, 비경수로 기술의 상업화 첫 사례라는 점에서 극도로 중요한 의의를 갖는다. 나트륨 냉각 고속로 기술의 현실화는 첨단 원자력 기술 개발에 있어 규제 투명성과 안전성이 확보되었음을 입증하며, 향후 유사 차세대 원자로 프로젝트들의 인허가 가능성을 제시한다."
  },
  {
    "date": "2026-03-25",
    "title": "미국 BWRX-300 프로젝트, 일본 투자 유입",
    "summary": "GE Hitachi의 BWRX-300 SMR 프로젝트에 일본 투자자들이 투자를 진행하고 있다.",
    "summaryLong": "GE Hitachi의 BWRX-300 소형모듈원자로 프로젝트에 일본의 투자자들이 자금을 공급하고 있다. 이는 미국의 첨단 SMR 기술에 대한 국제적 자본 유입을 의미하며, 특히 원자력 기술 선진국인 일본의 전략적 관심을 반영한다. 미국과 일본 간의 원자력 기술 협력이 민간 투자 차원으로 확대되는 사례로, 양국의 에너지 안보 및 기후변화 대응 전략의 일환으로 평가된다.",
    "cat": "기술",
    "type": "BWR",
    "dev": "GEH",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxQMzhndEdYYThMWTFrYWowUFhZY0EzYlhodjdJUENFbVV1c053aHdjNmU5eFNVdWJUNng4am9pU1VxNkpOcE1DbTBWSl96R2M3NzFXRi14U1NqRHJhMkNmX3ZFLVRXN2kwUUhXNVkwVUJMZHloZFB1R21rbUxLV3N4UFlEX0pnYjVmb2p6X29ubE0tY3RieU9rRF81azRyUQ?oc=5",
    "k": "new u s bwrx 300 projects get japanese investment american nuclear society ans"
  },
  {
    "date": "2026-03-23",
    "title": "스웨덴 SMR 발전소 건설허가 신청",
    "summary": "스웨덴에서 소형모듈원자로 발전소 건설을 위한 허가 신청이 제출되었다.",
    "summaryLong": "스웨덴에서 소형모듈원자로 발전소 건설을 위한 공식 허가 신청이 제출되었다. 이는 유럽에서도 SMR 상용화가 본격적으로 추진되고 있음을 보여주며, 높은 전력 수요와 에너지 전환 목표를 가진 유럽 국가들의 원자력 정책 변화를 반영한다. 스웨덴의 사례는 유럽연합 내 다른 국가들에게도 SMR 도입의 모범 사례가 될 수 있으며, 유럽의 에너지 독립성과 탄소 중립 달성에 기여할 것으로 전망된다.",
    "cat": "인허가",
    "type": "General",
    "dev": "",
    "region": "EU",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMikAFBVV95cUxOQ2JCVWZlVnJLQ1ZzOXRsMTV3bHVjRlc1bzhSMTRlMnVnTUt1TDBLSnJBWTdUT2d2blc0Q3AydDhJOWN2UGRFNWVRc0ZQZ1huN1dKOEktLU1uRWF0TUR4QUJoN2lJVWcxRzFvQXVxckdMM2FNVnFvcWxxZ3BwTXc3cTJYNkVkRWdQeEg4QV9vRzg?oc=5",
    "k": "application submitted for swedish smr plant"
  },
  {
    "date": "2026-03-17",
    "title": "NuScale Power, 유일한 NRC 인증 SMR 기업",
    "summary": "NuScale Power는 미국 규제당국(NRC)으로부터 인증받은 유일한 상용 SMR 기업이다.",
    "summaryLong": "NuScale Power는 미국 원자력규제위원회(NRC)로부터 인증받은 유일한 상용 소형모듈원자로 기업으로 인정되고 있다. 이는 NuScale의 기술이 미국의 가장 엄격한 규제 기준을 충족하였음을 의미하며, 상용 SMR 시장에서 규제 확실성을 획득한 선도 기업의 지위를 확립했다. NRC 인증은 투자자 신뢰 구축과 프로젝트 사업화에 있어 결정적 이점을 제공하며, NuScale의 시장 선도 위치를 강화한다.",
    "cat": "기술",
    "type": "General",
    "dev": "NuScale",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxPanhYZEVnY0RyT3RkbTVNRXBWcjNwYXU0a0pqN3RCV2ZETjB2clVuQzBNVVg1X0FYdnNyN0ZfTV9UY3FXZ240c3NFX01fcG42TklocnpVNEh5eVcyY21uYzFMRlRJUDMyaFJkS29hVmxXU21EWE1XcjZRM0pUNFJ3SmlEajQzRFJUWTRwczlhM2wxRy1vMUZtSHptbU9SU1RxZi1mYjMzV2E2V2hnaTFJ?oc=5",
    "k": "nuscale power inside the only nrc certified small modular reactor company nyse smr"
  },
  {
    "date": "2026-03-15",
    "title": "NuScale, 산업 핵에너지 공급 역할 강조",
    "summary": "NuScale이 소형모듈원자로 기술을 산업용 핵에너지 공급에 활용하는 역할을 부각하고 있다.",
    "summaryLong": "NuScale Power가 소형모듈원자로 기술의 산업용 핵에너지 공급 역할을 강조하고 있다. 전통적인 발전 용도뿐 아니라 철강, 화학, 수소 생산 등 고열 산업 공정에 필요한 열에너지와 전력을 제공하는 용도로 SMR의 활용성을 적극 홍보하는 전략이다. 이는 탈탄소화가 필요한 산업 부문에 원자력 기술의 새로운 시장을 창출할 수 있는 가능성을 제시하며, SMR의 경제성 및 시장 수요 확대에 긍정적 영향을 줄 것으로 기대된다.",
    "cat": "기술",
    "type": "PWR",
    "dev": "NuScale",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxOR01GZzl4N3VVSElXY3pVRnRYMks0TGFQbWpReHF2TnpqaU82X05uS1RiLWNkY2oybEJMT29Sa3JTSEdNS05JYXVrcVlsVUdfcjZiai1KakR3NVBDTkRXbDBxQ2xfa0tFdjRlWjZ1UDY2aGI2Wk83MzczYjMwWXJwTA?oc=5",
    "k": "nuscale highlights role of its small modular reactor technology in supplying dependable industrial nuclear energy"
  },
  {
    "date": "2026-03-12",
    "title": "소형모듈원자로·마이크로원자로 전문가 인사이트",
    "summary": "미국 정책연구소가 SMR과 마이크로원자로에 대한 전문가 의견을 제시하고 있다.",
    "summaryLong": "미국의 정책연구기관이 소형모듈원자로와 마이크로원자로에 대한 전문가 의견과 인사이트를 제시하고 있다. 이는 SMR과 마이크로원자로의 기술적 특성, 경제성, 정책적 과제 등을 균형 있게 분석하여 정책결정자와 투자자들에게 정보를 제공하는 역할을 한다. 전문가 의견의 제시는 SMR 산업의 시장 성숙도 평가, 규제 환경 개선 방향, 향후 투자 전망 등에 대한 신뢰할 수 있는 기준점을 제공함으로써 산업 발전을 지원한다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxPaURLN1hFQWVNZFNLdHc5R2R1VnZiQUlSS2N4ejVYWnpVMXBTSEltampDMWhOUWpzT0k4ZW40VlR1UFg4NFNjdEFZendzZFd2WFU0enIxNVozd25jRlhHUVVkeHozSzJtOWNkRURjRnB4djlkbzliT29KWXE0VDQ0VHNvVk8?oc=5",
    "k": "small modular reactors microreactors expert insights energy environment"
  },
  {
    "date": "2026-03-09",
    "title": "Rolls-Royce, 항공용 지속가능연료(e-SAF) 원전 활용 검토",
    "summary": "Rolls-Royce가 항공용 지속가능연료 생산을 위해 소형원자로 활용 가능성을 파트너들과 검토 중이다.",
    "summaryLong": "Rolls-Royce는 항공 산업의 탄소중립화를 위해 지속가능항공연료(e-SAF) 생산 과정에 소형원자로(SMR) 기술을 활용하는 방안을 파트너 기관들과 함께 검토하고 있다. 이는 항공용 지속가능연료 생산에 필요한 대량의 열과 전력을 원자력으로 공급함으로써 탈탄소화를 추진하는 전략으로, 항공산업과 원자력산업의 협력 모델을 제시한다. 소형원자로는 기존 대형원전보다 유연한 배치와 산업용 열 공급에 유리하다는 점에서 항공용 지속가능연료 생산의 효율성을 높일 수 있다. 이러한 시도는 글로벌 에너지 전환 속에서 SMR 활용 분야를 다각화하는 사례로 의미를 가지며, 향후 항공 부문의 에너지 수급 체계 전환에 영향을 미칠 전망이다.",
    "cat": "기술",
    "type": "General",
    "dev": "Rolls-Royce",
    "region": "UK",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxNUTJIdmN4Qi1xQjE1dnktSk5DajB0eGEtdUFJR3RlZXNXcnJ1ZUs2WUQ2M1JXanpWOGZXRmJkSFEtYjZra0txQ21XTWljMk80WTM3VlpUZEtRb3JDZ2hxdXRsMjRwcHhCenU0cEozelI3SHREWGZxYlhfWWJuZDFTRGZ6emJQdmhuWlRYMXVNamc5TnZ4TFVFemFwZzR4TVg3YmRzeTB3bFg4S01FQjRsMFFXRWQ?oc=5",
    "k": "rolls royce partners to explore small nuclear reactors for e saf"
  },
  {
    "date": "2026-03-04",
    "title": "i-SMR 표준설계인가 추진",
    "summary": "i-SMR이 표준설계인가(SDA) 취득을 추진 중이다.",
    "summaryLong": "i-SMR이 캐나다에서 표준설계인가(SDA) 획득을 추진하고 있으며, 이는 해당 소형원자로 설계의 규제 심사를 통과하여 향후 건설 및 운영의 기술적 타당성을 공식 인정받는 과정이다. 표준설계인가는 규제기관의 상세한 안전 및 기술 평가를 거쳐 발급되므로, 이를 취득하면 실제 부지 건설 허가 취득 시간을 단축할 수 있다. 이는 캐나다의 SMR 상용화 로드맵에서 중요한 이정표로, 향후 온타리오와 같은 지역의 SMR 배치 계획을 뒷받침할 기반을 마련한다. 규제 승인 과정의 진전은 북미 지역의 SMR 산업 발전을 촉진하는 신호로 작용할 것으로 예상된다.",
    "cat": "인허가",
    "type": "General",
    "dev": "i-SMR",
    "region": "CA",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxNbV9jMko3WkpMYmY1MlhORG51N3EzXzAwQU9xbGx5WHZJUWFOV1lVdVlxWFZlcHFHcngtTXhKMlh1V2FiRGRRcXNiVmFWMGQ3T0syaG4xYmdoTDA5RHVXRzBESzRPNEJTR3M4R0tHMmhhYW14VW9DZjIydjlmTFE0UW5qVzVMNUNiX3c2OUlB?oc=5",
    "k": "standard design approval sought for i smr"
  },
  {
    "date": "2026-03-04",
    "title": "인도네시아·미국·일본, SMR 배치 컨퍼런스 개최",
    "summary": "인도네시아, 미국, 일본이 소형모듈원자로(SMR) 배치에 관한 국제 컨퍼런스를 공동 개최했다.",
    "summaryLong": "인도네시아, 미국, 일본이 공동으로 소형모듈원자로(SMR) 배치 전략에 관한 국제 컨퍼런스를 개최함으로써 아시아-태평양 지역의 SMR 협력을 강화하고 있다. 이 회의는 세 국가가 각자의 에너지 정책과 원자력 비전을 공유하고, SMR 기술의 지역적 수요와 배치 방안에 대해 논의하는 플랫폼으로 기능한다. 특히 개발도상국인 인도네시아의 참여는 신흥 경제권의 에너지 수요 충족과 탈탄소화를 위한 SMR의 역할을 강조한다. 이러한 다자간 협력은 SMR 기술 표준화, 규제 조화, 인력 양성 등 지역적 생태계 구축으로 이어질 가능성이 높으며, 향후 인도태평양 지역의 원자력 에너지 구도 재편에 영향을 미칠 전망이다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxPeERwbEpSc3djVEZKY1dlaUp6Y2xYd1R1RG9zSmpXRmNKZjRaSkROanFRdlZQMGlaWmd3dUFPT2lvaXlmSkNJeWdCektrTFVOS0Jid2xvRTZFa3FNTC04dEV0NUZiRm5UN1VXc1FhblphMlQ2LWM3ekcxYWppZzZDT2ZnNi16aUhlMG1MTC1xcGQ2TWJVYVNRbk9iYUpiZ0VSQjU0RWxFSS1lUXhyOHZMb1BqZjlzMi13NVhv?oc=5",
    "k": "indonesia united states and japan host conference on nuclear small modular reactor deployment"
  },
  {
    "date": "2026-02",
    "title": "Holtec, Palisades SMR-300(Pioneer) 건설허가 신청 NRC 접수",
    "summary": "미시간 Palisades 부지 쌍둥이 SMR-300 CP 신청 접수. 제한작업승인(LWA) 포함, 안전·환경평가 2027 상반기 목표.",
    "cat": "인허가",
    "type": "PWR",
    "dev": "Holtec",
    "region": "US",
    "source": "ANS",
    "url": "https://www.ans.org/news/article-7673/holtec-submits-partial-construction-permit-application-for-smrs-at-palisades/",
    "summaryLong": "Holtec은 미시간의 Palisades 부지에서 SMR-300(Pioneer) 2기를 건설하기 위해 미국 원자력규제위원회(NRC)에 건설허가 신청서를 제출했으며, 이에 제한작업승인(LWA)도 포함되어 있다. 동 신청은 안전 및 환경 평가 절차를 거쳐 2027년 상반기 완료를 목표로 하고 있어, 향후 3년 이상의 규제 검토 기간이 예상된다. Palisades 부지는 기존 폐지된 대형원전 부지의 재활용이라는 점에서 산업 재편과 지역 경제 부활의 의미를 가진다. 이는 미국의 SMR 상용화를 위한 첫 번째 대규모 건설 프로젝트로, 승인될 경우 북미 SMR 산업의 중요한 이정표가 될 것으로 전망된다."
  },
  {
    "date": "2026-02-27",
    "title": "소형모듈원자로, 큰 꿈: 온타리오의 핵 전략",
    "summary": "캐나다 온타리오 지역이 소형모듈원자로를 핵심 에너지 정책으로 추진하고 있다.",
    "summaryLong": "캐나다의 온타리오 주가 소형모듈원자로를 에너지 정책의 핵심축으로 추진하면서 지역의 원자력 비전을 재정립하고 있다. 온타리오는 전기 수요 증가, 산업 탈탄소화, 에너지 자립성 강화 등 다층적 정책 목표를 달성하기 위해 SMR 도입을 전략적으로 추진하고 있다. 이는 대형원전 중심의 전통적 원자력 정책에서 벗어나 소규모·분산형 에너지 공급 체계로의 전환을 의미한다. 온타리오의 정책 전환은 캐나다 내 다른 주(州)와 북미 지역 전체의 에너지 정책에 영향을 미치는 모범 사례로 작용할 가능성이 크며, 향후 산업용 열 공급과 지역 전력망 안정화에 중요한 역할을 할 것으로 예상된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "CA",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxQUWtCc3J2NWdpelRHSmpIaGZhZHI2eDJmT25FdDJqTHh2a05POUlGNDJaUGhXYWpkVV9qX3JtVmZNSXRpVVFyZUhPLWprbldNUjN1T0hWbW0wUE5KRmFEenZ5QmIxTTQwQ2hhbDFISXVlaHVNMExUdHJaRUdORGY2R2ItX19PSkk1aWxpeWxka0l4ZWtT?oc=5",
    "k": "small modular reactors big dreams ontario s nuclear pitch"
  },
  {
    "date": "2026-02-17",
    "title": "SMR vs. BWXT: 소형모듈원자로 주식 비교 분석",
    "summary": "투자 관점에서 SMR과 BWXT의 소형모듈원자로 관련 주식을 비교 분석하는 기사이다.",
    "summaryLong": "야후 파이낸스에서 소형모듈원자로(SMR) 기술 개발 기업들의 투자 가치를 비교 분석했다. SMR과 BWXT(Babcock & Wilcox Technologies) 등 주요 SMR 개발사들의 주가와 성장성을 평가하며 투자자를 위한 의사결정 정보를 제공한다.",
    "cat": "기술",
    "type": "General",
    "dev": "SMR, BWXT",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMie0FVX3lxTE9oZmNtUnpRNGJWbHNCNTBHTEdLbDk2U1lEX0hKLVp5ZHJ6VE5hQ0pKd3NHb0dOM0RPeWNhLU9jU3puanlpTHd2U0F0Wlk5bHVoT051OTRsTnlfT1FBbU9vWEhaWWcxOUxIVjhnUG5OMExyWGVBNGswSlg3aw?oc=5",
    "k": "smr vs bwxt which small modular reactor stock is a buy right now"
  },
  {
    "date": "2026-02-06",
    "title": "Rolls-Royce SMR, Yokogawa와 제어시스템 공급 계약",
    "summary": "Rolls-Royce SMR이 Yokogawa로부터 제어시스템 공급 계약을 체결했다.",
    "summaryLong": "Rolls-Royce SMR이 일본의 요코가와(Yokogawa)와 제어시스템 공급 계약을 체결함으로써 SMR 운영을 위한 핵심 안전·제어 기술 확보를 진행하고 있다. 제어시스템은 원자로의 안전성과 신뢰성을 보장하는 필수 인프라로, 선진 디지털 기술을 적용한 요코가와와의 협력은 Rolls-Royce SMR의 기술 경쟁력을 강화한다. 이 계약은 영국 기업과 일본 기업의 국제적 산업 협력을 보여주는 사례로, SMR 상용화를 위한 글로벌 공급망 구축 추세를 반영한다. 향후 Rolls-Royce SMR의 설계·인허가·건설 단계에서 요코가와의 첨단 제어 기술이 중요한 경쟁 우위가 될 것으로 예상된다.",
    "cat": "계약",
    "type": "General",
    "dev": "Rolls-Royce",
    "region": "UK",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPZWZDblF4emNqSEpLRmpveEFpOVpyRjlaaTdRSjhoSkZiMFRoNk5GYzExZkNzdGdXWDhPWDJHWDFLcGhkRUkybHVtdnF1QnBKMW5fV2xTMkFQdDZqWjhoUUw5X1UxbDFSb0VEdW9ySDdYQ3huRndNNjVrblNDZ2x2QjM5UlFsUE96c1daNEhmbGhpYkRuZ0swOVVvUUN6UFpsUjcyOTRTbzN2a0M3ZnltUzVUWQ?oc=5",
    "k": "rolls royce smr taps yokogawa to supply control systems for small modular reactor fleet"
  },
  {
    "date": "2026-01-30",
    "title": "NEA 소형모듈원자로 디지털 대시보드 3.1판 출시",
    "summary": "국제원자력기구(NEA)가 SMR 데이터베이스의 최신판(3.1판)을 출시하고 지속적 업데이트 체계를 확대했다.",
    "summaryLong": "경제협력개발기구(OECD) 산하 원자력청(NEA)이 SMR 데이터베이스의 최신판(3.1판)을 출시하고 지속적 업데이트 체계를 확대하였으며, 이는 전 세계 SMR 개발 현황에 대한 투명하고 신뢰할 수 있는 정보 제공 역할을 강화하는 것을 의미한다. 디지털 대시보드 형태의 데이터베이스는 정책결정자, 산업계, 학계 등 다양한 이해관계자들이 SMR 프로젝트 진행 상황, 기술 특성, 규제 상황 등을 실시간으로 모니터링할 수 있게 한다. 이러한 정보 공유 플랫폼의 확대는 국제적 산업 표준화와 기술 협력을 촉진하며, SMR 시장의 투명성과 신뢰도 제고에 기여한다. NEA의 지속적 업데이트 체계는 빠르게 변화하는 SMR 산업의 동향을 반영하는 정보 인프라로서 향후 글로벌 SMR 생태계 발전을 지원할 것으로 기대된다.",
    "cat": "기술",
    "type": "General",
    "dev": "NEA",
    "region": "",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxNNTlaNHNSOElINkpnU19mU3dyLWVLNDlpNDhIZ3RPRXhtbUpCNkZXcXNITm40Z0ZPUTgya2ppcGRUWjhQSDc2YS1yZjlFSTdJMmtpeXBTTUozUk11cWE5a3hOTWNIVmdkYnpjZk5teEQ2aUZGRVVaMEtQeUw3V0t1UnJ3U290Tnp5V0lTa3hsTEc0MVdHbGlxTUhQT2VYZ1BQQkVZTmQyUTJZeEJVaDBoRHJJcFBHVjBNd2Q3dWlsWWtpQ0JFOExN?oc=5",
    "k": "launch of edition 3 1 and new rolling update nea small modular reactor digital dashboard"
  },
  {
    "date": "2026-01-23",
    "title": "소형모듈원자로 법제가 주(State) 원자력 정책을 재편하다",
    "summary": "소형모듈원자로 관련 법제 정비가 미국 각 주의 핵에너지 정책을 재구성하고 있다.",
    "summaryLong": "미국에서 소형모듈원자로 관련 법제 정비가 각 주(State)의 원자력 정책을 근본적으로 재구성하고 있으며, 이는 연방 차원의 정책 지원과 지방 정부의 정책 혁신이 함께 이루어지는 과정을 보여준다. 주 단위의 에너지 정책과 규제 환경이 SMR 도입을 용이하게 하도록 개선됨에 따라, 각 지역의 에너지 자립성, 탈탄소화, 산업 재정의 등이 새로운 방향으로 전개되고 있다. 이는 미국의 원자력 정책이 중앙 집중식에서 분산형으로 전환되고, 다양한 지역 상황에 맞춘 맞춤형 에너지 전략이 부상하는 것을 의미한다. 향후 미국 내 지역별 SMR 프로젝트의 증가와 함께 글로벌 SMR 산업의 성장을 촉진하는 중요한 계기가 될 것으로 전망된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxOVjc3N2h4V1B4X0JTMDhjdWxQNHJrYTN5ZzlTZ3gwd0xLUk5LcjQ2VEp1THZHY1BieDJqU1RzbnVtcklTX3VlQzRFV0lueDRtWTd3dlUtOWptTEhqa2FPRnpSOUVIY21FcUN5LVhRNlBfeUtUZ0dncVd2MUFHa29LS3NSazRsM2hEdThvNVIwd1VmdW9ocHVOLWhfX3hQTC1aOXVaSzIxYU5tNlZsUkgzVDBZa1paQ00?oc=5",
    "k": "how small modular reactor laws are reshaping state nuclear energy policy"
  },
  {
    "date": "2026-01-22",
    "title": "SMR 대 GEV: 소형모듈원자로 주식 비교 분석",
    "summary": "금융 매체가 SMR 관련 상장사들의 주식 투자 가치를 비교 분석하고 있다.",
    "summaryLong": "금융 매체가 소형모듈원자로(SMR) 관련 상장사들의 주식 투자 가치를 비교 분석하는 기사를 발표했다. SMR은 차세대 원자력 에너지 솔루션으로 주목받고 있으며, 이에 따라 관련 기업들의 주가 움직임과 펀더멘털을 평가하는 분석이 증가하고 있다. 이는 에너지 전환과 탈탄소화 추세 속에서 SMR 산업의 성장 가능성에 대한 시장의 관심이 높아지고 있음을 시사한다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiekFVX3lxTE5NeVVNSy01XzY2Z2UwNlRhMDB0NFNGdm50a0x6YUtfa3AzRWZ1bVpnM1Ffb2xuYXV1OWFOSWs1ektOLWIwOUJuMHVHUVE0VWRZTFd4cnFxcHpYUm5VM0VuenRIbFR2ckhqNHBJM0ZrVHBhcG95S1RrSzF3?oc=5",
    "k": "smr vs gev which small modular reactor stock is a better pick"
  },
  {
    "date": "2025-12",
    "title": "NRC, Natrium 안전심사 조기 완료(예산 11% 절감)",
    "summary": "TerraPower Natrium 안전심사를 일정보다 앞서 완료 — 2026.3 CP 발급으로 이어짐.",
    "cat": "인허가",
    "type": "SFR",
    "dev": "TerraPower",
    "region": "US",
    "source": "ANS",
    "url": "https://www.ans.org/news/article-7818/nrc-approves-terrapower-construction-permit/",
    "summaryLong": "TerraPower의 Natrium 소형모듈원자로에 대한 미국 원자력규제위원회(NRC)의 안전심사가 예정된 일정보다 앞서 완료되었으며, 이는 예산을 11% 절감하는 성과도 함께 거두었다. 이번 조기 완료는 2026년 3월 건설허가(CP) 발급으로 이어질 것으로 예상되며, 미국의 SMR 상용화 일정 단축과 프로젝트의 경제성 개선을 의미한다. 이는 차세대 원자력 기술의 규제 절차 효율화가 가능함을 보여주는 사례로 평가된다."
  },
  {
    "date": "2025",
    "title": "Rolls-Royce SMR, 영국 GBE-N 우선기술 선정 — Wylfa 부지",
    "summary": "Great British Energy-Nuclear 우선협상 기술로 선정, 부지 Wylfa(최대 3기). 2026.4 site-specific 계약.",
    "cat": "계약",
    "type": "PWR",
    "dev": "Rolls-Royce",
    "region": "UK",
    "source": "WNN",
    "url": "https://www.world-nuclear-news.org/articles/rolls-royce-smr-progresses-to-final-step-of-uk-ass",
    "summaryLong": "Rolls-Royce의 SMR이 영국 Great British Energy-Nuclear(GBE-N)의 우선협상 기술로 선정되었으며, Wylfa 부지에서 최대 3기까지 건설될 수 있는 기회를 확보했다. 2026년 4월에는 해당 부지에 대한 구체적인 계약이 체결될 예정으로, 영국의 전략적 에너지 안보 강화와 SMR 산업 활성화에 중추적 역할을 할 것으로 기대된다. 이번 선정은 Rolls-Royce의 기술력을 국제적으로 입증하는 동시에 영국의 SMR 도입 로드맵 실현에 핵심적 이정표가 될 것으로 평가된다."
  },
  {
    "date": "2025",
    "title": "Rolls-Royce SMR, 영국 GDA 최종단계(Step 3) 진입",
    "summary": "SMR 중 유일하게 GDA 최종단계 도달, ~2026.8 완료 예정(총 53개월).",
    "cat": "인허가",
    "type": "PWR",
    "dev": "Rolls-Royce",
    "region": "UK",
    "source": "Rolls-Royce SMR",
    "url": "https://www.rolls-royce-smr.com/our-progress",
    "summaryLong": "Rolls-Royce의 SMR이 영국 포괄설계평가(GDA) 최종단계인 Step 3에 진입하여 현재 개발 중인 SMR 프로젝트 중 유일하게 이 수준에 도달한 것으로 나타났다. 약 53개월의 총 심사 기간 중 2026년 8월 완료를 목표로 하고 있으며, 이는 영국의 SMR 상용화를 위한 규제 기반 구축이 구체적으로 진행되고 있음을 의미한다. GDA 최종 완료 시 Rolls-Royce는 영국에서 SMR의 설계 승인을 획득하게 되어 실제 건설 단계로의 진입이 가능해질 것으로 전망된다."
  },
  {
    "date": "2025-12-16",
    "title": "폴란드 SGE-한국 삼성건설, 소형모듈원자로 MOU 체결",
    "summary": "폴란드의 SGE와 한국의 삼성건설이 소형모듈원자로 개발·배치에 관한 양해각서(MOU)를 체결했다.",
    "summaryLong": "폴란드의 SGE와 한국의 삼성건설이 소형모듈원자로의 개발 및 배치를 위한 양해각서(MOU)를 체결함으로써 동유럽 지역에서의 한국 원자력 기술 진출이 본격화되었다. 이번 협력은 에너지 자립과 탄소 중립을 추구하는 폴란드의 정책 방향과 한국 기술의 경쟁력이 만난 것으로, 한국 원자력 산업의 국제적 확대를 시사한다. 향후 구체적인 개발 계획과 사업화 방안이 수립될 것으로 예상되며, 이는 한국형 SMR의 해외 수출 가능성을 제시하는 의미 있는 사례가 될 것으로 평가된다.",
    "cat": "계약",
    "type": "General",
    "dev": "삼성건설",
    "region": "KR",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxPTGN0c3NFeUlMeGxTdG1DdVZnQmRDeDVFRzdSaGlQMzRZdlJ1WURQdDZCQWpzT3h4ckZvZVRKRkxjUUpUZE1OMkJ5d1VtSEg3LWJOUmdVdUVNYU5wNDMzdjFXVWUwdTJKM0tCLTBSTDhxR2MtQ2pCSTV6ZEdxbXoyMkpJVUlZYjE4alV5WjV3ODdWN1B2NndlaE5uZGdYc2RhUlpXeXNFUTJTb19wUTZSVHhLYjJ4MUZm?oc=5",
    "k": "poland s sge signs small modular reactor mou with south korea s samsung c t"
  },
  {
    "date": "2025-12-11",
    "title": "BWRX-300, 영국 GDA 2단계 통과",
    "summary": "GE Hitachi의 BWRX-300이 영국 포괄설계평가(GDA) 2단계를 통과했다.",
    "summaryLong": "GE Hitachi의 BWRX-300 소형모듈원자로가 영국의 포괄설계평가(GDA) 2단계를 통과하며 규제 승인 프로세스에서 주요 진전을 이루었다. 이는 글로벌 SMR 개발 경쟁에서 GEH의 기술이 국제 규제 기준을 충족하고 있음을 입증하는 것으로, 향후 3단계 최종 심사로의 진행이 예상된다. BWRX-300의 GDA 진행 상황은 영국뿐만 아니라 전 세계 SMR 상용화 시장에 긍정적 신호를 제공하고 있으며, 경쟁사들과의 기술 우위 확보에도 기여하고 있다.",
    "cat": "인허가",
    "type": "BWR",
    "dev": "GEH",
    "region": "UK",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxOZl9sdUJtaXVCRkV5WnlTOTZFRnhZNUR5djVNUk9ERmRFaElHbVFBMTZkdEw4WnpFbUxfQ21xQldKNnhVTG51dHFhWHlpZEFubXZQaEZjVVFyejExWTlOeEJDcHpOX3VaMWFOYko5V1ZVdVJLVE0tNXBual9feFRLWmwwQ2hrYmVVZEZvaXhySFNpb01PT3JGOVBPb1NubjdSUjJRWjJNRzl3SUxCbFJiNTV2MTNGX28?oc=5",
    "k": "bwrx 300 small modular reactor passes step 2 of uk s generic design assessment"
  },
  {
    "date": "2025-12-04",
    "title": "TVA, 미국 첫 소형모듈원자로 테네시주 건설 추진",
    "summary": "미국 테네시밸리청(TVA)이 미국 내 첫 상용 소형모듈원자로 개발을 테네시주에서 추진 중이다.",
    "summaryLong": "미국 테네시밸리청(TVA)이 테네시주에서 미국 내 첫 상용 소형모듈원자로 건설 프로젝트를 추진 중이다. 이 프로젝트는 기존의 대형 원자력 발전소 건설 방식을 벗어나 모듈식 설계와 소규모 투자로 차세대 원자력 에너지를 확산시키려는 미국의 에너지 정책을 반영하고 있다. TVA의 주도적 역할은 미국의 탄소 중립 목표 달성과 지역 에너지 안보 강화에 중요한 역할을 할 것으로 기대되며, 성공 시 다른 지역으로의 확산 모델을 제시할 수 있을 것으로 전망된다.",
    "cat": "기술",
    "type": "General",
    "dev": "TVA",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxQc1VzZXFhNVFWVjhmZUpKWXB3X3Y3cld0Y3FjdDBqNlljRHpiMDVweXY4ZVM4TmxLWDdHTjJmcWJJaEZ1NGtBQ1Y3SXlpZndHMm15UE9vVlpnNDVveGFQUnBtTWJRa0tzYlRyRHQ2a192UGkxcFdvMVJwVi16S2tLLWVEalJHRGpRRk1nbmJJNjA4YUJPZXpQREM0TFlBM3fSAbMBQVVfeXFMTm5TSlJLUkR6a2JmVlFfd25PMGtob195RHU2VVJvQWVqdERIc0hTMmFWRHpKOWEzd2NfQlZaQVdkd1ZudV81RllreGdRTFBmRTJmTzFGZjBrNmxWT2EyLS0tVnpYcnRIUURwVXoxRVlaYXppLUN0SE9zU2tuZy1pZW5Gc1c0Zk9JV21mZ1FvMEVZeTdtSGFzWUNWZnRLVlZqNDI3M3VoOVpqWHdsRUZYWHAtQms?oc=5",
    "k": "tva to develop america s first small modular reactor in tennessee"
  },
  {
    "date": "2025-12-03",
    "title": "DOE, TVA·Holtec SMR 프로젝트 선정 지원",
    "summary": "미국 에너지부(DOE)가 TVA와 Holtec의 SMR 프로젝트를 지원 대상으로 선정했다.",
    "summaryLong": "미국 에너지부(DOE)가 TVA와 Holtec의 소형모듈원자로 프로젝트를 정부 지원 대상으로 선정하여 미국 SMR 산업 육성 정책을 가시화했다. 양사의 프로젝트 선정은 기술력과 사업성을 동시에 인정받은 것으로, 미국의 SMR 상용화 로드맵 실현에 연방 차원의 적극적 투자가 이루어지고 있음을 의미한다. 이러한 정부 지원은 프로젝트의 경제적 타당성 개선과 상용화 일정 단축을 가능하게 할 것으로 예상되며, 미국이 글로벌 SMR 시장 선도 위치를 유지하기 위한 전략적 조치로 평가된다.",
    "cat": "기술",
    "type": "General",
    "dev": "TVA,Holtec",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxQYkVKSC1ZX0l5eE9wRUpSZU1tNS1raVk4QVozcl92blBDZEU3RXVwNXJFY2oyb3BlR0QwcFFBSlVmRFAxbnNtVE9ELXhDR2tSdnBTWWJXM0JBamszeVg0eVp2SThaLVJPNjJGcXp1UXRBR2FqQ0xqTW03Ul93MF9hOHYzZmI2MjdscjVzRnBMOS1lRFoyenc?oc=5",
    "k": "doe selects tva and holtec for smr awards american nuclear society ans"
  },
  {
    "date": "2025-12-02",
    "title": "테네시주, 미국 최초 소형모듈원자로 건설 DOE 그랜트 확보",
    "summary": "테네시주가 Clinch River 부지에서 미국 최초의 소형모듈원자로 건설을 위한 연방 정부 지원금을 확보했다.",
    "summaryLong": "테네시주가 미국 에너지부(DOE) 그랜트를 받아 Clinch River 부지에서 미국 최초의 상용 소형모듈원자로(SMR) 건설 프로젝트를 추진한다. 이 프로젝트는 SMR의 실제 건설 및 운영을 통해 미국의 핵에너지 정책 전환을 주도하는 중요한 이정표가 될 것으로 기대된다.",
    "cat": "정책",
    "type": "General",
    "dev": "",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMi-gFBVV95cUxNdFdETE5ZWjY3cjNwRk5adXlnNW4yYzl4b3FFMUFvRHdMY1ZTVkZ0eG1wcHp0YUtYTDRzRWRrcWhnUFVxcWRvUDhMZEZNQ2xOejItMUpONWt2bENVNDVjYmpQTTZJUkNFTVVZTmJIamxTQ1F3TUdDb0tTZHYxY2EtUlN5cktrMjFqbUdIcV9tbVh3dVBYeFh5TXNTdWlEcGR1bmR3R1k2WUV6Q0NQVU8zbDJzV0NHbkRhM25EdFBzTXlJdkwyeHZVRUtVc3Q3SnloOTk1amtHNll4UXhhNHBKaU1Pa09HVXJUYVN2cHVYSGVXQ3lRaWZPOFdn?oc=5",
    "k": "tennessee secures u s department of energy grant to develop nation s first small modular reactor at clinch river site"
  },
  {
    "date": "2025-11",
    "title": "X-energy, TRISO-X 연료 조사시험 개시 + TX-1 착공",
    "summary": "INL 첨단시험로(ATR) 연료 조사시험 시작, 테네시 Oak Ridge TX-1 연료제조시설 건설 착수.",
    "cat": "기술",
    "type": "HTGR",
    "dev": "X-energy",
    "region": "US",
    "source": "X-energy TRISO-X",
    "url": "https://x-energy.com/triso-x-fuel/",
    "summaryLong": "X-energy가 자사의 TRISO-X 핵연료에 대한 조사시험(irradiation test)을 INL의 첨단시험로(ATR)에서 개시했으며, 동시에 테네시주 Oak Ridge에 TX-1 연료제조시설의 건설을 착수했다. 이는 고온가스로 기술의 핵심인 TRISO 연료의 성능을 검증하고 상용화를 준비하는 중요한 단계로, 실제 운영 환경 조건에서의 연료 거동 데이터를 확보할 수 있게 된다. TX-1 시설 완공은 X-energy가 Xe-100 등 소형모듈원자로의 대규모 상용화를 추진하기 위한 필수 인프라 구축을 의미한다."
  },
  {
    "date": "2025-11-28",
    "title": "IAEA, SMR 규제 교육 프로그램 개시",
    "summary": "국제원자력기구(IAEA)가 소형모듈원자로 규제 전문가 양성을 위한 시범 교육 프로그램을 시작했다.",
    "summaryLong": "국제원자력기구(IAEA)가 소형모듈원자로의 확산에 대응하기 위해 회원국 규제 전문가 양성을 목표로 하는 시범 교육 프로그램을 공식 개시했다. 이는 각국의 원자력 규제 역량 강화를 통해 SMR 기술 도입 시 안전 기준과 규제 체계를 선제적으로 준비하기 위한 글로벌 차원의 조치이다. IAEA의 이러한 주도적 역할은 SMR 산업의 건강한 확산과 국제 규제 표준화에 기여할 것으로 기대된다.",
    "cat": "기술",
    "type": "General",
    "dev": "IAEA",
    "region": "",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxOdGdqRl9lclc0UFNKRkJRQ3J1UnRCSE1QV2FPX2dMbjE5a1BVQWpRVWdmN3I1WnRLRG1hTmR5R043eVZpYmpXcGF4N1hoNW90WVEyYkdiN0JRc2h0ZnBfVld6bzQxa0FKVUV3SFBMcWo1Rl9NLU9WUV9maUtINHdNNFZVRXhKdllIb2x2VFZmOVYxZTF6cWdwRTNDUkxkb2ZLeHc?oc=5",
    "k": "iaea launches pilot school for regulating small modular reactors"
  },
  {
    "date": "2025-11-18",
    "title": "세계은행, SMR 산업은 최고 기술 1~2개 개발 집중해야",
    "summary": "세계은행 총재가 소형모듈원자로 산업의 기술 개발 방향으로 최적 기술 선택과 집중을 강조했다.",
    "summaryLong": "세계은행의 총재가 소형모듈원자로 산업의 지속 가능한 발전을 위해서는 기술 개발을 최고 기술 1~2개로 집중하고 선택과 집중을 강조했다. 이는 현재 다양한 노형과 설계 개념들이 개발 중인 글로벌 SMR 시장에서 자원 배분의 효율성과 산업 표준화의 필요성을 지적한 것이다. 세계은행의 이러한 견해는 정부 지원과 민간 투자 결정에 영향을 미칠 수 있는 중요한 신호로 해석된다.",
    "cat": "기술",
    "type": "General",
    "dev": "",
    "region": "",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMi2wFBVV95cUxQbVlMUl9FMkZ3NVl3OVVHOEF2bmNGU0FTVkFMQ05vZjFMRjlXR1QxdlRpODJnbHNQYUZ3dVdUdDg0ME15ZDJCUGtzRVpTVmZVal9NQXI1NkMybW1sYmlfb3BXLS1yTGJldFFoWWdUdkRWc29pYTBxR2dXaEt2dmdSMHBBdWhYWjRMSUlmbmlDYkNld1NfNmFqaVY4UHU5WXFjYzRPZEloTmFSXzZrZlJsQ2h1SG0tUWhBQTV3NmJKbmY2MmpzRndGeWJoQ2M5dW1IWlIyclROVHA1eGc?oc=5",
    "k": "small modular reactor industry must focus on developing best one or two technologies says world bank head"
  },
  {
    "date": "2025-11-10",
    "title": "EU, 소형모듈원자로 전략 수립을 위한 의견 수렴",
    "summary": "EU 집행위원회가 소형모듈원자로(SMR) 전략 수립을 위해 이해관계자들의 의견을 수렴 중이다.",
    "summaryLong": "EU 집행위원회가 유럽의 소형모듈원자로 산업 지원을 위한 전략 수립 단계에서 산업계, 규제기관, 에너지 전문가 등 이해관계자들의 의견을 적극 수렴하고 있다. 이는 EU의 탈탄소화 목표 달성과 에너지 안보 강화 차원에서 SMR의 역할을 체계적으로 검토하는 정책 수립 과정이다. EU의 공식 SMR 전략 수립은 유럽 내 SMR 프로젝트 추진을 위한 제도적 기반과 자금 지원 방향을 명확히 하는 데 중요한 의미를 갖는다.",
    "cat": "기술",
    "type": "General",
    "dev": "EU",
    "region": "EU",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxNcng3YzJDUDdacEhmMFY1aHdxRjdaYWRSZUlsWmdmN2RRRV9qZ0NzbjBjN2x0VlhHV0JJYnhHQUQ2ZjRpYjcxSTZRVjlnNmdkSm13R2F6U0xUa3dRbUtvNXBpS1F2RmFmTkdmVEpLUHdSbEhvaEJ0OUFwVndHWTZyRUduUHFlQnl5N1pmRE4wUmV3eF9TSE9vQ2t6QkZ2YWdxWmduZlEwOTVkTmZ3MFZkaEZ3?oc=5",
    "k": "commission invites views to shape its small modular reactor strategy"
  },
  {
    "date": "2025-11-06",
    "title": "AES 소형모듈원자로 발표, 퍼듀대학 핵 정상회담 주목",
    "summary": "AES가 소형모듈원자로 관련 발표를 하며 퍼듀대학 핵 정상회담에서 주목받았다.",
    "summaryLong": "AES가 소형모듈원자로 관련 주요 발표를 통해 퍼듀대학에서 개최된 핵 정상회담에서 산업계의 주목을 받았다. 이는 미국 내 주요 에너지 관련 학계 및 정책 이해관계자들이 모인 고위급 회담에서 AES의 SMR 기술 및 사업 추진 계획이 중요한 논의 대상이 되었음을 나타낸다. 이러한 고위급 행사에서의 가시성 확보는 AES의 기술 신뢰성 입증과 투자 및 파트너십 유치에 긍정적 영향을 미칠 수 있다.",
    "cat": "기술",
    "type": "General",
    "dev": "AES",
    "region": "US",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiygFBVV95cUxPQWxuMDI1M0hHS1dhdVgyczdkOTg2MTliYUE3bHhhMlptc0g4czRNb3RmaEx3MlQ0NU1EUnFPb201QVFSWk1KVGhsLXd1NnBMS2JFWjFuZzJJMzhJbFpERkJVUWNCV1l2LS1QRjNGWkh4eVhMRU96TVBIVExQd2pfYml3N01FdDRfRVM2UE1ZTWl0ZzRudEo5ZGRCc0IwZWZ0ZnVXMDZscTNQLWFRTmFLLWRGamdvVWM5UDBXbEpHcU9ac1A1ZllnbC1n?oc=5",
    "k": "aes small modular reactor announcement highlights nuclear summit at purdue university"
  },
  {
    "date": "2025-09",
    "title": "Centrica–X-energy 공동개발협약(JDA) — 영국 6GW, Hartlepool 우선부지",
    "summary": "英 최초 첨단모듈로 배치 JDA. 영국 내 6GW 추진, 1차 부지 Hartlepool, 2026 본격화 목표.",
    "cat": "계약",
    "type": "HTGR",
    "dev": "X-energy",
    "region": "UK",
    "source": "Centrica",
    "url": "https://www.centrica.com/media-centre/news/2025/centrica-and-x-energy-agree-to-deploy-uk-s-first-advanced-modular-reactors/",
    "summaryLong": "Centrica와 X-energy가 영국 내 소형모듈원자로 사업 추진을 위한 공동개발협약(JDA)을 체결하여, 영국 최초의 첨단모듈로 배치 프로젝트를 공식화했다. 협약에 따라 총 6GW 규모의 SMR 배치를 영국 내에서 추진할 계획이며, 첫 번째 부지로 Hartlepool을 우선 선정하고 2026년 본격 시공을 목표로 하고 있다. 이는 영국의 에너지 안보 강화와 넷제로 목표 달성을 위한 핵심 사업으로, 유럽 지역의 SMR 상용화를 주도하는 사례가 될 것으로 예상된다."
  },
  {
    "date": "2025-09-25",
    "title": "X-Energy, Xe-100 캐나다 알버타주 배치 타당성 확인",
    "summary": "X-Energy가 Xe-100 고온가스로의 캐나다 알버타주 배치 가능성을 확인했다.",
    "summaryLong": "X-energy가 자사의 Xe-100 고온가스로에 대한 캐나다 알버타주 배치 타당성 조사를 완료하여 기술적, 경제적 가능성을 확인했다. 알버타주는 석유·가스 기반의 에너지 산업이 발달한 지역으로, SMR을 통한 산업 열 공급 및 에너지 전환의 중요한 잠재 시장이다. 이는 X-energy의 Xe-100 기술이 북미 지역에서의 상용화 추진을 위한 구체적인 근거를 확보한 것으로, 향후 캐나다와의 사업 추진 가능성을 크게 높였다.",
    "cat": "기술",
    "type": "HTGR",
    "dev": "X-Energy",
    "region": "CA",
    "source": "\"\"small modular reactor\"\" - Google News",
    "url": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxQbEJ3aWlWdC1tQWVaTFF0d05yYmM1YS1ZampzUllTV3BPTFBZZ0hiVW1NelNBbnZzSUEzSjFnajVjMV8wS0RfTnA2YmdJRVViQU5fYi1uU1BXODN2Y1M4M2JtSHNrVGxlUEFwbzVONFliWFRfcHNsQmoxNUxYUVV5MEZZek5NUFBrOXA2aEZ1b0ZUVVBhcTBWVV9ONU9RbExfeXlwSlY3R2JPd0RpQVZVbUswLUotdXY2b1Bv?oc=5",
    "k": "x energy confirms feasibility of xe 100 advanced small modular reactor deployment in alberta x energy"
  },
  {
    "date": "2025-08",
    "title": "X-energy, TX-1 연료시설 건설사로 Clark Construction 선정",
    "summary": "테네시 Oak Ridge TX-1 TRISO-X 시설 건설사 선정.",
    "cat": "계약",
    "type": "HTGR",
    "dev": "X-energy",
    "region": "US",
    "source": "X-energy",
    "url": "https://x-energy.com/news-releases",
    "summaryLong": "X-energy가 테네시주 Oak Ridge에 건설 예정인 TX-1 TRISO-X 연료 제조시설의 주요 건설사로 Clark Construction을 선정했다. Clark Construction과의 계약 체결을 통해 X-energy는 연료 제조시설 건설 일정을 확실히 하고, 고도의 핵연료 제조 기술 구현을 위한 전문 시공사와의 협력 체계를 확보했다. 이는 TRISO-X 연료의 조사시험과 함께 이루어지는 상용 규모 제조 인프라 구축으로, X-energy의 전반적 기술 상용화 로드맵을 가속화하는 중요한 진전이다."
  },
  {
    "date": "2025-08-25",
    "title": "X-energy·Amazon·KHNP·두산에너빌리티 4자 전략적 협력",
    "summary": "AI 인프라용 첨단원자력 확대 — 원자로 설계·공급망·건설·투자·운영·글로벌 공동배치. 한국(KHNP·두산) 공급망 편입.",
    "cat": "계약",
    "type": "HTGR",
    "dev": "X-energy",
    "region": "US·KR",
    "source": "BusinessWire",
    "url": "https://www.businesswire.com/news/home/20250825430061/en/",
    "summaryLong": "X-energy, Amazon, 한국수력원자력(KHNP), 두산에너빌리티가 AI 인프라 전력 공급을 위한 전략적 협력을 체결했다. 이번 협력은 첨단 소형모듈로(SMR) 원자로의 설계·공급망 구축·건설·투자·운영 및 글로벌 공동배치를 포괄하는 포괄적 파트너십으로, 한국 기업들이 국제 원자력 공급망의 핵심 역할을 담당하게 된다. 이는 글로벌 데이터센터의 탈탄소화 수요와 높은 부하기저 전력 필요성이 증가하는 가운데 원자력 에너지의 실질적 활용을 가속화하는 의미 있는 사례이며, 한국의 원자력 기술과 제조역량이 국제 시장에서 인정받는 계기가 될 전망이다."
  },
  {
    "date": "2025-07",
    "title": "TVA Clinch River BWRX-300, NRC 건설허가 도케팅(17개월 심사)",
    "summary": "미국 첫 BWRX-300 CP 신청 도케팅. ~2026.12 심사 완료 목표.",
    "cat": "인허가",
    "type": "BWR",
    "dev": "GE-Hitachi",
    "region": "US",
    "source": "Federal Register",
    "url": "https://www.federalregister.gov/documents/2025/07/01/2025-11037/tennessee-valley-authority-clinch-river-nuclear-site-construction-permit-application",
    "summaryLong": "GE-Hitachi의 소형모듈로 BWRX-300이 미국 테네시밸리오더티(TVA)의 클린치강 부지에서 건설허가(CP) 신청 도큐멘팅을 완료했다. 미국 최초의 BWRX-300 건설허가 신청으로, 미국 원자력규제위원회(NRC)는 약 17개월에 걸친 신청 심사를 거쳐 2026년 12월을 완료 목표로 진행 중이다. 이는 소형모듈로가 기존 대형 원자로보다 규제 절차를 신속하게 진행할 수 있음을 시사하며, 향후 BWRX-300의 상용화 추진력을 높일 수 있는 주요 마일스톤이 될 것으로 예상된다."
  },
  {
    "date": "2025-07",
    "title": "ARC-100, 캐나다 CNSC 벤더설계심사(VDR) Phase 2 완료",
    "summary": "\"근본적 인허가 장벽 없음\" 판정. NB Power가 부지준비허가 신청, 건설허가 신청 목표 2027.",
    "cat": "인허가",
    "type": "SFR",
    "dev": "ARC",
    "region": "CA",
    "source": "WNN",
    "url": "https://www.world-nuclear-news.org/articles/arc-100-completes-canadian-regulatory-design-review",
    "summaryLong": "캐나다의 소형모듈로 개발사 ARC의 ARC-100은 캐나다 핵규제위원회(CNSC)의 벤더설계심사(VDR) 2단계를 완료하고 \"근본적인 인허가 장벽이 없다\"는 판정을 받았다. 이를 바탕으로 NB Power가 부지준비허가 신청을 제출했으며, 2027년 건설허가 신청을 목표로 하고 있다. 이는 캐나다에서 소형모듈로의 규제 틀이 점진적으로 성숙해지고 있음을 보여주는 사례이며, 상용 수소·산업열 공급용 SMR의 실질적 배치가 더욱 현실화되고 있음을 의미한다."
  },
  {
    "date": "2025-05",
    "title": "두산에너빌리티, X-energy 16기분 주기기 예약 + 창원 SMR 공장",
    "summary": "RPV 등 NSSS 주기기 16세트 예약. 11GW 파이프라인 대응 위해 창원 SMR 전용 제작공장 신설 약정.",
    "cat": "계약",
    "type": "HTGR",
    "dev": "두산에너빌리티",
    "region": "KR",
    "source": "POWER",
    "url": "https://www.powermag.com/x-energy-doosan-lock-in-16-unit-xe-100-component-reservation-as-doosan-commits-to-new-smr-factory/",
    "summaryLong": "두산에너빌리티가 X-energy와의 협력 체계 속에서 원자로압력용기(RPV) 등 주기기(NSSS) 16세트 예약 계약을 체결하고, 11GW 규모의 글로벌 SMR 파이프라인 수요에 대응하기 위해 창원에 SMR 전용 제작공장 신설을 약정했다. 이는 한국의 원자력 부품 제조역량을 고도화하고 대규모 수출 기반을 구축하려는 전략적 투자로, 향후 한국이 글로벌 SMR 공급망의 중추적 역할을 수행할 수 있는 기반이 될 것으로 전망된다."
  },
  {
    "date": "2025-04",
    "title": "캐나다 OPG, BWRX-300 건설허가 발급·핵 콘크리트 타설(북미 최초)",
    "summary": "CNSC가 OPG Darlington에 건설허가 발급, 원자로건물 기초공사 착수 — 세계 최초 BWRX-300 건설. 운영허가 신청도 제출.",
    "cat": "인허가",
    "type": "BWR",
    "dev": "GE-Hitachi",
    "region": "CA",
    "source": "GE Vernova",
    "url": "https://www.gevernova.com/news/press-releases/ge-vernova-hitachi-bwrx-300-small-modular-reactor-approved-construction-province-ontario-opg",
    "summaryLong": "캐나다 핵규제위원회(CNSC)가 온타리오 전력공사(OPG)의 달링턴 부지 BWRX-300에 대해 건설허가(CP)를 정식 발급했으며, OPG는 원자로건물 기초 핵콘크리트 타설을 통해 북미 최초로 건설을 착수했다. 동시에 OPG는 운영허가 신청도 제출하여 순차적 인허가 진행 체계를 가동했다. 이는 세계 최초의 BWRX-300 실제 건설 사례로, 소형모듈로의 상용화 진입이 가시화되고 있음을 보여주는 획기적 이정표이며, 향후 다른 국가와 사업자들의 추진 가속화를 견인할 것으로 예상된다."
  },
  {
    "date": "2025-04",
    "title": "Seaborg→Saltfoss 사명 변경, 초기 연료 LEU로 전환",
    "summary": "덴마크 해상 부유식 용융염로(CMSR) 개발사. HALEU 공급 리스크로 초기 연료를 LEU로(감속재 흑연으로) 변경.",
    "cat": "기술",
    "type": "MSR",
    "dev": "Seaborg/Saltfoss",
    "region": "DK",
    "source": "WNN",
    "url": "https://world-nuclear-news.org/Articles/Seaborg-switches-fuel-plans-due-to-HALEU-supply-is",
    "summaryLong": "덴마크의 해상 부유식 용융염로(CMSR) 개발사 Seaborg가 Saltfoss로 사명을 변경하고, 동시에 초기 연료를 고농축우라늄(HALEU)에서 저농축우라늄(LEU)으로 전환하기로 결정했다. 이는 국제 HALEU 공급망의 불확실성을 회피하고 상용화 일정을 가속화하려는 실질적 조정으로, 감속재를 흑연으로 변경하는 기술적 재설계를 수반한다. 이러한 변화는 신형 원자로 개발에서 공급망 리스크를 얼마나 현실적으로 고려하고 대응하는지를 보여주는 사례로, 향후 다른 SMR 개발사들도 유사한 실용적 접근을 모색할 가능성을 시사한다."
  },
  {
    "date": "2025-04",
    "title": "Westinghouse eVinci, NRC 주요설계기준 토픽보고서 승인",
    "summary": "히트파이프 마이크로로 eVinci 사전협의 마일스톤(앞서 2024.12 I&C 플랫폼 승인 — 첫 마이크로로).",
    "cat": "기술",
    "type": "Micro",
    "dev": "Westinghouse",
    "region": "US",
    "source": "WNN",
    "url": "https://www.world-nuclear-news.org/articles/pre-licensing-milestone-for-evinci",
    "summaryLong": "Westinghouse의 히트파이프 기반 마이크로로 eVinci가 미국 원자력규제위원회(NRC)로부터 주요설계기준(Key Design Criteria) 관련 토픽보고서 승인을 획득했다. 이는 지난 2024년 12월 계측·제어(I&C) 플랫폼 승인에 이은 두 번째 주요 설계 마일스톤으로, eVinci의 사전협의 단계가 지속적으로 진전되고 있음을 의미한다. 소형모듈로의 규제 승인 경로가 단계적으로 성숙해지면서, 마이크로로 분야의 실질적 상용화 가능성도 함께 높아지고 있다."
  },
  {
    "date": "2025-03",
    "title": "Dow·X-energy, Long Mott Xe-100 건설허가(CP) 신청 제출",
    "summary": "Seadrift(텍사스) 부지 Xe-100 4기 CP 신청 — Dow 화학공장 공정열·전력. 산업체 첫 첨단로 CP 신청.",
    "cat": "인허가",
    "type": "HTGR",
    "dev": "X-energy",
    "region": "US",
    "source": "POWER",
    "url": "https://www.powermag.com/dow-and-x-energy-advance-landmark-nuclear-project-in-texas-with-construction-permit-filing/",
    "summaryLong": "X-energy와 화학회사 Dow가 텍사스 Seadrift 부지에서 Xe-100 소형모듈로 4기에 대한 건설허가(CP) 신청을 미국 원자력규제위원회(NRC)에 제출했다. 이 사업은 Dow의 화학공장에 공정열과 전력을 공급하는 목적으로 추진되며, 산업체가 첨단 소형모듈로의 건설허가를 신청한 첫 사례로서 역사적 의미를 갖는다. 이는 SMR이 단순한 기술 실증에서 벗어나 실제 산업용 에너지 수요를 충족시키는 상용 솔루션으로 인식되기 시작했음을 보여주며, 향후 산업계의 탈탄소화 추진에 원자력이 본격적으로 역할할 수 있는 전환점이 될 전망이다."
  },
  {
    "date": "2024",
    "title": "Amazon, X-energy에 5억 달러 투자 + Energy Northwest 배치",
    "summary": "Amazon Series C-1 약 5억$ 투자, 워싱턴주 Energy Northwest와 Xe-100 배치 합의(데이터센터 전원).",
    "cat": "투자",
    "type": "HTGR",
    "dev": "X-energy",
    "region": "US",
    "source": "X-energy",
    "url": "https://en.wikipedia.org/wiki/X-energy",
    "summaryLong": "Amazon이 SMR 개발사 X-energy에 약 5억 달러를 투자하는 Series C-1 라운드를 주도했으며, 워싱턴주의 Energy Northwest와 함께 Xe-100 소형모듈로를 데이터센터 전원으로 배치하기로 합의했다. 이는 Amazon이 재정적 지원과 실제 배치를 동시에 추진함으로써 SMR의 상용화 경로를 구체화하는 움직임으로 평가된다. 빅테크 기업들이 전력 수요 증가에 대응하기 위해 첨단 원자력 기술에 직접 투자하는 추세를 보여주는 사례이며, 향후 SMR의 산업용·데이터센터 용도 확대 가능성을 시사한다."
  },
  {
    "date": "2024",
    "title": "Kairos Power–Google, 첨단로 전력공급 계약(PPA) 체결",
    "summary": "Kairos KP-FHR(Hermes 계열) 전력을 구글에 공급하는 PPA — 빅테크 첫 첨단로 전력계약 중 하나.",
    "cat": "계약",
    "type": "FHR",
    "dev": "Kairos Power",
    "region": "US",
    "source": "Kairos Power",
    "url": "",
    "summaryLong": "Kairos Power가 개발한 KP-FHR(Hermes 계열) 첨단로가 Google과 전력공급 계약(PPA)을 체결하여 빅테크 기업에 SMR 전력을 공급하기로 합의했다. 이는 Google 같은 초대형 기술 기업이 처음으로 SMR 기반 전력계약을 체결하는 사례로, 종래의 대규모 집중형 전원 중심 구조에서 벗어난 신호탄이 된다. 첨단로의 경제성과 신뢰성이 업계의 주요 고객들로부터 인정받는 계기가 되고 있으며, SMR 산업의 상용화 단계 진입을 가속화할 전망이다."
  },
  {
    "date": "2024-09",
    "title": "SMART100 표준설계인가 취득(한국)",
    "summary": "KAERI SMART100이 한국 표준설계인가 취득. 사우디 수출·현대ENG 협력 추진.",
    "cat": "인허가",
    "type": "PWR",
    "dev": "SMART/KAERI",
    "region": "KR",
    "source": "KAERI",
    "url": "https://kaeri.re.kr/board/view?linkId=12112&menuId=MENU00326",
    "summaryLong": "한국원자력연구원(KAERI)이 개발한 SMART100이 국내 표준설계인가를 취득하여 소형모듈로의 국산화 개발을 공식 인정받았다. 이를 기반으로 사우디아라비아로의 수출과 현대엔지니어링과의 협력을 추진함으로써 SMART를 한국 원자력 산업의 수출 전략 기술로 본격화하려는 계획이다. 표준설계인가는 향후 복수의 동일 기종 건설과 국제 경쟁력 강화의 기초가 되어, 한국의 SMR 기술 글로벌 진출을 가능하게 할 것으로 기대된다."
  },
  {
    "date": "2023-01",
    "title": "NuScale US600(77MWe) 설계인증(DC) 취득",
    "summary": "NRC 설계인증을 받은 첫 SMR. 이후 출력증강형 US460 표준설계승인(SDA) 추가 심사.",
    "cat": "인허가",
    "type": "PWR",
    "dev": "NuScale",
    "region": "US",
    "source": "Federal Register",
    "url": "https://www.federalregister.gov/documents/2023/01/19/2023-00729/nuscale-small-modular-reactor-design-certification",
    "summaryLong": "NuScale의 US600(77MWe)이 미국 원자력규제위원회(NRC)로부터 설계인증(DC)을 획득하여 미국 최초의 SMR 설계 인증 사례가 되었다. 이후 NuScale은 출력을 증강한 US460 모델에 대해 표준설계승인(SDA) 추가 심사를 진행 중이며, 이는 SMR의 상용화 경로가 실질적으로 열리는 중요한 전환점을 의미한다. NRC 인증 취득은 SMR에 대한 규제 선례를 확립하고 후속 개발사들의 인허가 진행을 촉진할 가능성이 높아, SMR 산업화의 가속도를 높일 것으로 전망된다."
  }
];
window.SMR_UPDATED = "2026-06-12 09:13 KST";
