/* news-recent.js — AUTO-GENERATED subset of news-data.js (do not edit; see track-news.mjs writeRecent) */
window.SMR_NEWS = [
 {
  "date": "2026-07-15",
  "title": "'부산형 SMR 상용화'에 정부 연구개발 지원 나선다",
  "summary": "정부가 부산형 SMR의 상용화를 위한 연구개발 지원을 시작한다.",
  "summaryLong": "정부가 부산 지역 기반의 소형모듈원자로(SMR) 상용화 프로젝트에 대한 연구개발 지원을 추진한다. 이는 국내 SMR 기술 자립화 및 지역산업 육성을 목표로 하는 국책 지원 정책이다. 부산형 SMR은 한국이 독자 개발 중인 SMR 노형으로, 정부 차원의 본격 R&D 투자·지원이 이루어질 예정이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "kookje.co.kr",
  "url": "https://www.kookje.co.kr/news2011/asp/newsbody.asp?code=0200&key=20260715.99099004385",
  "k": "뭐라노 부산형 smr 상용화 정부 연구개발 지원 나선다",
  "ko": 1,
  "id": "3ed478b2"
 },
 {
  "date": "2026-07-15",
  "title": "DL이앤씨, 매출 감소 속 SMR·데이터센터로 체질 개선",
  "summary": "DL이앤씨가 경영 부진을 극복하기 위해 SMR과 데이터센터 사업 확대로 사업 구조를 전환한다.",
  "summaryLong": "건설사 DL이앤씨가 매출 감소에 대응하기 위해 소형모듈원자로(SMR)와 데이터센터 사업을 중심으로 사업 포트폴리오를 재편하고 있다. 이는 기존 건설 중심 사업에서 에너지·첨단산업 분야로의 전략적 전환으로, SMR 프로젝트 참여 확대를 통해 미래 성장 동력을 확보하려는 시도다. 구체적 투자 규모와 추진 일정은 별도 공시 예정이다.",
  "cat": "기술",
  "type": "General",
  "dev": "DL이앤씨",
  "region": "KR",
  "source": "leadeconomy.co.kr",
  "url": "https://www.leadeconomy.co.kr/news/articleView.html?idxno=8644",
  "k": "매출 줄었지만 dl이앤씨 smr 데이터센터로 체질 바꾼다",
  "ko": 1,
  "id": "2b04fced"
 },
 {
  "date": "2026-07-15",
  "title": "경주시, 민선 9기 기자간담회서 'SMR을 최우선 과제'로 선언",
  "summary": "경주시가 새 시정의 최우선 과제로 소형모듈원자로(SMR) 유치를 공식 선언했다.",
  "summaryLong": "경주시가 민선 9기 기자간담회에서 소형모듈원자로(SMR) 유치 및 관련 산업 발전을 시정의 최우선 과제로 공식 밝혔다. 이는 지역 정부가 SMR 기반 조성에 정책적 우선순위를 부여하는 공식 정책 선언으로, 향후 부지 확보, 인프라 구축, 규제 지원 등 실질적 추진으로 이어질 가능성이 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "kbsm.net",
  "url": "https://www.kbsm.net/news/view.php?idx=526946",
  "k": "경주시 민선9기 기자간담회 개최 smr 최우선 과제",
  "ko": 1,
  "id": "7b31a160"
 },
 {
  "date": "2026-07-15",
  "title": "현대건설, 미국 차세대 SMR 'EAGL-1 프로젝트' 협력 강화",
  "summary": "현대건설이 미국의 차세대 SMR 'EAGL-1 프로젝트'와의 협력을 강화하고 있다.",
  "summaryLong": "현대건설이 미국의 차세대 소형모듈원자로(SMR) 개발 프로젝트인 'EAGL-1'과의 협력을 확대하고 있다. 이는 한국 대형 건설사가 글로벌 첨단 원자력 시장 진출을 본격화하는 움직임으로, 미국 내 SMR 사업 참여를 통해 국제 경쟁력을 강화하려는 전략으로 평가된다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "US",
  "source": "seonamtoday.com",
  "url": "http://seonamtoday.com/news/view.php?idx=50820",
  "k": "현대건설 미국 차세대 smr eagl 1 프로젝트 협력 강화",
  "ko": 1,
  "id": "1b35cc0e"
 },
 {
  "date": "2026-07-15",
  "title": "현대건설-미국 팬코(FANCO), 납-비스무트 냉각 SMR 사업 협력",
  "summary": "현대건설이 미국 팬코(FANCO)와 납-비스무트 냉각 소형모듈원자로(SMR) 사업에 협력하기로 했다.",
  "summaryLong": "현대건설이 미국의 팬코(FANCO)와 납-비스무트 냉각 소형모듈원자로(SMR) 개발·건설 사업에 협력하기로 합의했다. 납-비스무트는 차세대 첨단 냉각재로, 이를 활용한 SMR 사업 참여로 현대건설이 고급 원자력 기술 분야로의 진출을 가속화하고 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "US",
  "source": "meconomynews.com",
  "url": "https://www.meconomynews.com/news/articleView.html?idxno=132809",
  "k": "현대건설 fanco 납 비스무트 냉각 smr 사업 협력",
  "ko": 1,
  "id": "bb9849b8"
 },
 {
  "date": "2026-07-15",
  "title": "TRISO-X, 테네시주 연료 캠퍼스 확장비 1,100만 달러 지원금 획득",
  "summary": "엑스에너지(X-energy)의 자회사 TRISO-X가 테네시주(Tennessee)로부터 첨단 핵연료 캠퍼스 확장을 위해 1,100만 달러 경제개발 지원금을 받았다.",
  "summaryLong": "나스닥(NASDAQ) 상장 회사인 엑스에너지(X-energy)의 첨단 핵연료 제조 자회사 TRISO-X가 테네시주(Tennessee) 경제개발 부서로부터 1,100만 달러(약 110억 원)의 경제개발 지원금을 획득했다. 이 자금은 오크리지(Oak Ridge) 지역의 TRISO-X 핵연료 캠퍼스 확장을 지원할 예정이다. TRISO 연료는 고온가스로(HTGR)를 포함한 첨단 원자로 개발의 핵심 연료로, 국내 첨단로 사업과도 관련성 높은 소식이다.",
  "cat": "기술",
  "type": "HTGR",
  "dev": "X-energy",
  "region": "US",
  "source": "X-Energy, Inc. News Releases",
  "url": "https://investors.x-energy.com/news-releases/news-release-details/triso-x-awarded-tennessee-grant-support-expansion-nuclear-fuel",
  "k": "triso x awarded tennessee grant to support expansion of nuclear fuel campus",
  "id": "15ddb20b"
 },
 {
  "date": "2026-07-15",
  "title": "테라파워, 영국과 긍정적 협상 진행, 2030년대 초중반 원자로 가동 목표",
  "summary": "테라파워(TerraPower)가 영국(UK)과의 협상에서 긍정적 진전을 이루며 2030년대 초중반 원자로 가동을 목표로 하고 있다.",
  "summaryLong": "차세대 소듐냉각고속로(SFR) 개발사 테라파워(TerraPower)가 영국(UK) 정부와의 협상에서 긍정적 결과를 거두고 있는 것으로 알려졌다. 회사는 영국 내 원자로 건설 및 운영을 목표로 2030년대 초중반의 원자로 가동을 추진 목표로 설정했다. 이는 테라파워의 주요 국제 전략의 일환으로, 첨단로 상용화 일정에 관한 중요한 진행 사항이다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "UK",
  "source": "nucnet.org",
  "url": "https://www.nucnet.org/news/terrapower-holds-positive-talks-with-uk-targets-early-to-mid-2030s-for-reactor-launch-7-3-2026",
  "k": "terrapower holds positive talks with uk targets early to mid 2030s for reactor launch",
  "id": "af35605a"
 },
 {
  "date": "2026-07-15",
  "title": "오클로, 사용 핵연료 재활용 및 오하이오 청정에너지 캠퍼스 계획",
  "summary": "오클로(Oklo)가 사용 핵연료 재활용 사업과 오하이오(Ohio) 청정에너지 캠퍼스 건설 계획을 추진하고 있다.",
  "summaryLong": "소형모듈원자로(SMR) 및 사용 핵연료 재활용 기술 개발사인 오클로(Oklo)가 사용 후 핵연료 재활용 사업과 오하이오(Ohio)주에 청정에너지 캠퍼스 조성 계획을 발표했다. 이는 오클로의 핵심 사업 확장 전략으로, 폐연료 활용 기술과 지역별 거점 구축에 관한 중요한 사업 진행 뉴스이다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "Oklo",
  "region": "US",
  "source": "sg.finance.yahoo.com",
  "url": "https://sg.finance.yahoo.com/news/oklo-oklo-plans-used-fuel-111331373.html",
  "k": "oklo oklo plans used fuel recycling and ohio clean energy campus",
  "id": "9ce8d436"
 },
 {
  "date": "2026-07-15",
  "title": "SMR 연료 개발사 Standard Nuclear, IPO 앞두고 공모 규모 58% 축소",
  "summary": "소형모듈원자로(SMR) 연료 개발사 Standard Nuclear가 1억 5,000만 달러 규모 IPO를 앞두고 공모 규모를 58% 축소했다.",
  "summaryLong": "소형모듈원자로(SMR) 연료 개발사 Standard Nuclear가 1억 5,000만 달러 규모 신규공개(IPO) 진행을 앞두고 공모 규모를 58% 축소했다. 이는 시장 상황 변화 또는 투자 수요 조정에 따른 결정으로 보인다.",
  "cat": "투자",
  "type": "General",
  "dev": "Standard Nuclear",
  "region": "US",
  "source": "renaissancecapital.com",
  "url": "https://www.renaissancecapital.com/IPO-Center/News/120467/Small-modular-reactor-fuel-developer-Standard-Nuclear-slashes-deal-size-by-",
  "k": "small modular reactor fuel developer standard nuclear slashes deal size by 58 ahead of 150 million ipo",
  "id": "15292ccf"
 },
 {
  "date": "2026-07-15",
  "title": "SK와 베트남 VKIST, 차세대 SMR 기술 협력 본격화",
  "summary": "SK와 베트남 VKIST가 차세대 소형모듈원자로(SMR) 기술 협력을 본격적으로 진행한다.",
  "summaryLong": "SK그룹과 베트남의 VKIST(베트남 과학기술원으로 추정)가 차세대 소형모듈원자로(SMR) 기술 협력을 본격화하고 있다. 이는 한-베트남 간 원전 협력 확대 기조 속에서 추진되는 협력으로, SMR 기술 개발 및 도입 가능성을 탐색하는 사업으로 판단된다.",
  "cat": "기술",
  "type": "General",
  "dev": "SK",
  "region": "KR",
  "source": "g-enews.com",
  "url": "https://www.g-enews.com/article/Global-Biz/2026/07/2026071606464779892bd56fbc3c_1",
  "k": "sk와 베트남 vkist 차세대 smr 기술 협력 본격화",
  "ko": 1,
  "id": "a25ffd3d"
 },
 {
  "date": "2026-07-15",
  "title": "TRISO-X, 테네시주 보조금으로 핵연료 캠퍼스 확장",
  "summary": "엑스에너지(X-energy)의 자회사 TRISO-X가 테네시주로부터 보조금을 받아 핵연료 캠퍼스 확장을 추진한다.",
  "summaryLong": "엑스에너지(X-energy)의 TRISO-X 부문이 테네시주 정부로부터 보조금을 지원받아 핵연료 캠퍼스 확장 사업을 진행한다. TRISO-X는 고온가스로(HTGR) 및 첨단로 연료 공급 역할을 담당하는 회사로, 이번 보조금은 미국의 첨단원전 연료 공급망 강화 정책의 일환이다.",
  "cat": "정책",
  "type": "HTGR",
  "dev": "X-energy",
  "region": "US",
  "source": "x-energy.com",
  "url": "https://x-energy.com/news/triso-x-awarded-tennessee-grant-to-support-expansion-of-nuclear-fuel-campus/",
  "k": "triso x awarded tennessee grant to support expansion of nuclear fuel campus x energy",
  "id": "c498a2cf"
 },
 {
  "date": "2026-07-15",
  "title": "한국, 베트남과 원전 협력 공식화 및 K-전력 아세안 시장 진출",
  "summary": "한국이 베트남과 차세대 원전 협력을 공식화하고 'K-Electric' 기술을 아세안 시장에 선보이는 행사가 호찌민에서 개최되었다.",
  "summaryLong": "한국전기산업진흥회, 한국전력공사, 코엑스가 공동 주최하는 'ELECS VIETNAM 2026' 전시회가 호찌민 SECC에서 개최되었다. 이는 이재명 대통령의 지난 4월 베트남 국빈 방문 당시 한-베트남 정상회담에서 양국이 베트남의 차세대 원전 도입과 관련한 원전 협력을 공식화하고 신재생에너지 인프라 구축 협력에 합의한 배경을 바탕으로 한다. 한국의 전력·에너지 기술의 경쟁력을 아세안 지역 시장에 선보이는 기회이며, 한국의 원전 기술 수출 정책 추진을 보여주는 사례이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "전기신문 - 전체기사",
  "url": "https://www.electimes.com/news/articleView.html?idxno=370339",
  "k": "elecs vietnam 2026 k 전력 아세안 전력망을 잇다 호찌민서 개막",
  "ko": 1,
  "id": "9b94821d"
 },
 {
  "date": "2026-07-15",
  "title": "홀텍, SMR 300MW 사업 추진",
  "summary": "홀텍이 300MW 규모의 소형모듈원자로(SMR) 사업을 추진하고 있다.",
  "summaryLong": "원자력 관련 기업 홀텍이 원전 관련 사업에서 소형모듈원자로(SMR) 300MW 프로젝트를 중심으로 사업 전략을 전환하고 있다. 이는 홀텍의 SMR 개발 및 사업화 계획을 보여주는 기업의 실제 사업 추진 사항이다.",
  "cat": "기술",
  "type": "General",
  "dev": "홀텍",
  "region": "KR",
  "source": "esnews.kr",
  "url": "https://www.esnews.kr/news/articleView.html?idxno=5060",
  "k": "원전 장의사 서 조력자 로 홀텍 smr 300mw 승부수",
  "ko": 1,
  "id": "05ec2875"
 },
 {
  "date": "2026-07-15",
  "title": "NRC, TVA의 BWRX-300 소형모듈원자로 건설허가 권고",
  "summary": "미국 원자력규제위원회(NRC) 직원들이 테네시 클린치강(Clinch River)에 건설될 테네시밸리공사(TVA)의 BWRX-300 소형모듈원자로에 대한 건설허가를 권고했다.",
  "summaryLong": "미국 원자력규제위원회(NRC) 직원들이 테네시 클린치강(Clinch River)에 건설될 테네시밸리공사(TVA)의 BWRX-300 소형모듈원자로 프로젝트에 대한 건설허가를 권고했다. 이는 미국의 대표적 SMR 개발 프로젝트 중 하나로, NRC의 공식 승인 단계로의 진전을 의미한다.",
  "cat": "인허가",
  "type": "BWR",
  "dev": "TVA",
  "region": "US",
  "source": "energiesmedia.com",
  "url": "https://energiesmedia.com/nrc-recommends-tva-bwrx-300-reactor/",
  "k": "nrc staff recommend construction permit for tva s bwrx 300 small modular reactor at clinch river in tennessee",
  "id": "8d112163"
 },
 {
  "date": "2026-07-15",
  "title": "AI 시대 전력 경쟁력, SMR···원전 제조 유일 국가 '대한민국'",
  "summary": "김한곤 원자력연구원 단장이 AI 시대에 SMR이 전력 경쟁력의 핵심이며, 대한민국이 원전 제조 능력을 갖춘 유일한 국가라고 강조했다.",
  "summaryLong": "김한곤 원자력연구원 단장이 AI 시대 도래에 따른 전력 수요 증가 속에서 소형모듈원자로(SMR)의 중요성을 강조했다. 발언 내용에 따르면 대한민국이 원전 설계, 제조, 건설, 운영 등 전 주기의 능력을 갖춘 유일한 국가라고 주장했으며, 이는 SMR 시장에서의 경쟁력 우위를 반영한다. SMR이 AI 데이터센터 등 새로운 전력 소비처의 전력 공급 솔루션으로 주목되고 있음을 시사한다.",
  "cat": "기술",
  "type": "General",
  "dev": "원자력연구원",
  "region": "KR",
  "source": "hellodd.com",
  "url": "https://www.hellodd.com/news/articleView.html?idxno=112486",
  "k": "김한곤 단장 ai 시대 전력 경쟁력 smr 원전 제조 유일 국가 대한민국",
  "ko": 1,
  "id": "eedba6c7"
 },
 {
  "date": "2026-07-15",
  "title": "경주 '원전 전주기 도시' 도약…SMR 산단·AI 데이터센터 승부수",
  "summary": "경주시가 SMR 산업단지와 AI 데이터센터를 중심으로 '원전 전주기 도시'로 도약하려는 계획을 추진 중이다.",
  "summaryLong": "경주시가 SMR 산업단지 조성과 AI 데이터센터 유치를 핵심 전략으로 추진 중이다. 이는 기존의 원전 운영·관리 역할에서 한 단계 나아가 SMR 제조·건설·운영의 전주기 거점으로 도약하려는 구상이다. AI 시대의 전력 수요 증가에 대응하며, SMR이 분산 배치 가능한 청정에너지원으로서 데이터센터의 전력 공급원이 될 수 있다는 전략이 담겨있다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "kyongbuk.co.kr",
  "url": "https://www.kyongbuk.co.kr/news/articleView.html?idxno=4078443",
  "k": "경주 원전 전주기 도시 도약 smr 산단 ai 데이터센터 승부수",
  "ko": 1,
  "id": "413a9799"
 },
 {
  "date": "2026-07-15",
  "title": "경수로에서 고속로까지…현대건설, 4세대 SMR 선점",
  "summary": "현대건설이 가압경수로(PWR) 기반의 소형모듈원자로부터 고속로(SFR) 등 4세대 원자로까지 다양한 포트폴리오로 SMR 시장 선점을 추진 중이다.",
  "summaryLong": "현대건설이 SMR 사업 포트폴리오를 확대하고 있다. 기존의 가압경수로(PWR) 기반 중소형 원전에서 출발하여 나트륨냉각고속로(SFR) 등 4세대 원자로 기술까지 확보하려는 전략이 드러난다. 이는 다양한 응용 분야와 고객 요구에 대응할 수 있는 '풀 라인업' 구축을 목표로 하며, 글로벌 SMR 시장에서의 경쟁력 강화를 의도한다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "KR",
  "source": "ket.kr",
  "url": "https://ket.kr/news/article.html?no=39438",
  "k": "경수로에서 고속로까지 현대건설 4세대 smr 선점",
  "ko": 1,
  "id": "a020b3fd"
 },
 {
  "date": "2026-07-14",
  "title": "사천 환경단체, 삼천포화력 부지 SMR 추진 반대",
  "summary": "경남 사천지역 환경단체가 삼천포화력발전소 폐지 부지에 소형모듈원자로(SMR)를 도입하려는 계획에 반발하며 즉각 철회를 촉구했다.",
  "summaryLong": "경남 사천지역의 환경단체와 시민단체들이 삼천포화력발전소 폐지 부지에 소형모듈원자로(SMR)를 도입하려는 정부·기업의 계획에 대해 강하게 반발하고 있다. 단체들은 부지 재활용 방식에 대해 우려를 표시하며 계획의 즉각 철회를 요구했다. 이는 지역 수용성 측면에서 SMR 정책이 직면한 과제를 보여주는 사례이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "연합뉴스 최신기사",
  "url": "https://www.yna.co.kr/view/AKR20260714115200052",
  "k": "사천 환경단체 삼천포화력 부지 smr 추진 즉각 철회하라",
  "ko": 1,
  "id": "587a15b3"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 SMR 개발사 퍼스트 아메리칸 뉴클리어와 기본협약",
  "summary": "현대건설이 미국의 소형모듈원자로(SMR) 개발사 퍼스트 아메리칸 뉴클리어(FAN)와 차세대 SMR 협력 기본협약을 체결했다.",
  "summaryLong": "현대건설이 13일(현지시간) 미국 뉴욕에서 미국의 소형모듈원자로(SMR) 개발사 퍼스트 아메리칸 뉴클리어(FANCO)와 차세대 SMR 개발·사업화를 위한 기본협약(MOU)을 체결했다. 이 협력을 통해 현대건설은 첨단로 분야의 해외 협력 포트폴리오를 확대하고 미국 시장 진출을 가속화할 계획이다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "US",
  "source": "연합뉴스 경제 최신기사",
  "url": "https://www.yna.co.kr/view/AKR20260714068000003",
  "k": "현대건설 미국서 차세대 소형모듈원자로 협력 기본협약",
  "ko": 1,
  "id": "82af0948"
 },
 {
  "date": "2026-07-14",
  "title": "한·미·일, SMR 수출 동맹 구성",
  "summary": "한국, 미국, 일본이 소형모듈원자로(SMR) 수출을 위한 3국 협력 동맹을 결성했다.",
  "summaryLong": "한국, 미국, 일본 3개국이 소형모듈원자로(SMR) 기술 수출 및 글로벌 시장 개척을 위한 정부 간 협력 동맹을 공식 출범시켰다. 이는 SMR의 국제 수출 경쟁력 강화 및 규제 조화, 기술 표준화를 추진하기 위한 정책적 움직임이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "upi.com",
  "url": "https://www.upi.com/Top_News/World-News/2026/07/13/united-states-japan-joint-small-modular-reactor-project/9231783994951/",
  "k": "south korea u s japan form alliance on smr exports",
  "id": "9e3d6bd4"
 },
 {
  "date": "2026-07-14",
  "title": "아이티센씨티에스, 원자력 V-SMR 개발용 슈퍼컴 구축",
  "summary": "아이티센씨티에스가 원자력 V-SMR(수직축 소형모듈원자로) 개발 지원용 슈퍼컴퓨터 시스템을 구축했다.",
  "summaryLong": "정보통신 기업 아이티센씨티에스가 국내 첨단로 개발 프로젝트 중 하나인 V-SMR(수직축 소형모듈원자로) 기술 개발을 지원하기 위한 고성능 슈퍼컴퓨터 시스템을 신규 구축했다. 슈퍼컴은 원자로 설계, 열수력 해석, 안전 평가 등 복잡한 계산 작업을 담당하게 되며, 국내 SMR 자주 기술 개발 역량을 강화하는 데 기여할 것으로 기대된다.",
  "cat": "기술",
  "type": "General",
  "dev": "아이티센씨티에스",
  "region": "KR",
  "source": "mt.co.kr",
  "url": "https://www.mt.co.kr/stock/2026/07/14/2026071413269682002",
  "k": "더벨 아이티센씨티에스 원자력 v smr 개발 슈퍼컴 구축 머니투데이",
  "ko": 1,
  "id": "5b8c066d"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, FANCO(Fundamental Advanced Next-generation Compact Oscillator)와 미국(US) SMR 사업 전략적 파트너십 체결",
  "summary": "현대건설이 미국의 FANCO와 소형모듈원자로(SMR) 사업을 위한 전략적 파트너십을 체결했다.",
  "summaryLong": "현대건설이 미국의 FANCO와 소형모듈원자로(SMR) 사업 확대를 위한 전략적 파트너십을 체결했다. 이 파트너십을 통해 현대건설은 미국 시장에서의 SMR 사업 입지를 강화하고, FANCO와 함께 차세대 원자로 기술 개발 및 사업화를 추진할 것으로 보인다. 이는 현대건설의 글로벌 원전 협력망 확대 전략의 일환이며, 첨단 소형원자로 분야에서의 기술 협력 강화를 의미한다.",
  "cat": "계약",
  "type": "General",
  "dev": "현대건설, FANCO",
  "region": "US",
  "source": "koreaittimes.com",
  "url": "https://www.koreaittimes.com/news/articleView.html?idxno=155214",
  "k": "hyundai e c expands u s smr ambitions through strategic partnership with fanco",
  "id": "96237832"
 },
 {
  "date": "2026-07-14",
  "title": "아이티센씨티에스, 원자력연구원의 V-SMR 슈퍼컴퓨터 구축 프로젝트 수주",
  "summary": "아이티센씨티에스가 한국원자력연구원의 V-SMR 슈퍼컴퓨팅 시스템 구축 사업을 수주했다.",
  "summaryLong": "아이티센씨티에스가 한국원자력연구원의 V-SMR(Vertical Small Modular Reactor) 관련 슈퍼컴퓨팅 시스템 구축 프로젝트를 수주했다. 이 프로젝트는 V-SMR 설계 및 성능 검증을 위한 고성능 컴퓨팅 인프라 구축으로, 한국의 소형모듈원자로 기술 개발 지원 사업의 일환이다. 아이티센씨티에스의 참여는 국내 SMR 개발 사업의 기술 고도화 추진을 의미한다.",
  "cat": "계약",
  "type": "Micro",
  "dev": "아이티센씨티에스",
  "region": "KR",
  "source": "m.ddaily.co.kr",
  "url": "https://m.ddaily.co.kr/page/view/2026071410320190809",
  "k": "아이티센씨티에스 원자력연구원 v smr 슈퍼컴퓨터 구축",
  "ko": 1,
  "id": "ca4d7691"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 원전사와 'EAGL-1 프로젝트' 기본 협약 체결",
  "summary": "현대건설이 미국 원전사와 'EAGL-1 프로젝트'에 대한 기본 협약을 체결하며 SMR 풀라인업 확보를 추진 중이다.",
  "summaryLong": "현대건설이 미국 원전사와 'EAGL-1 프로젝트'에 대한 기본 협약(Master Agreement)을 체결했다. EAGL-1은 차세대 소형모듈원자로 프로젝트로 추정되며, 현대건설은 이 프로젝트를 통해 다양한 SMR 기술 포트폴리오(풀라인업) 확보를 목표하고 있다. 이 협약은 현대건설의 글로벌 SMR 사업 확대 전략의 핵심 마일스톤이며, 향후 설계, 건설, 운영 등 전 단계에서의 참여 확대를 의미한다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "US",
  "source": "asiatoday.co.kr",
  "url": "https://www.asiatoday.co.kr/kn/view.php?key=20260714010005017",
  "k": "smr 풀라인업 확보 현대건설 원전사와 eagl 1 프로젝트 기본 협약",
  "ko": 1,
  "id": "1cff64da"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국(US) FANCO와 납-비스무트 냉각 SMR 협력",
  "summary": "현대건설이 미국의 FANCO와 차세대 납-비스무트 냉각 소형모듈원자로(SMR) 개발 프로젝트 협력을 추진한다.",
  "summaryLong": "현대건설이 미국의 원자력 기업 FANCO와 납-비스무트 냉각 방식의 소형모듈원자로(SMR) 개발 사업에 협력하기로 결정했다. 이는 현대건설이 차세대 원자로 기술 분야로 사업을 확대하고 글로벌 원전 협력 네트워크를 강화하는 전략의 일환이다. 협력을 통해 현대건설은 EAGL-1 등 FANCO의 SMR 프로젝트에 EPC(설계·조달·건설) 사업 참여를 모색할 예정이다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "KR",
  "source": "biz.chosun.com",
  "url": "https://biz.chosun.com/en/en-realestate/2026/07/14/25E553TRJ5BLDKWY424YBVJZXE/",
  "k": "hyundai e c joins us fanco to advance lead bismuth smr project chosunbiz",
  "id": "c2e38041"
 },
 {
  "date": "2026-07-14",
  "title": "아이티센씨티에스, 한국원자력연구원 V-SMR 개발용 슈퍼컴 구축",
  "summary": "아이티센씨티에스가 한국원자력연구원의 V-SMR(수직형 소형모듈원자로) 개발을 위한 슈퍼컴퓨터를 구축하며 AI 기술을 제공한다.",
  "summaryLong": "아이티센씨티에스가 한국원자력연구원의 수직형 소형모듈원자로(V-SMR) 개발 프로젝트를 지원하기 위해 슈퍼컴퓨터 인프라를 구축했다. 아이티센씨티에스는 '풀스택(Full-stack) AI' 기술을 제공하여 V-SMR의 설계·분석·시뮬레이션을 지원하는 역할을 한다. 이는 국내 첨단 SMR 개발의 핵심 인프라 구축으로, 연구 속도 가속화와 기술 고도화에 기여할 것으로 예상된다.",
  "cat": "기술",
  "type": "General",
  "dev": "아이티센씨티에스",
  "region": "KR",
  "source": "byline.network",
  "url": "https://byline.network/2026/07/14-601/",
  "k": "아이티센씨티에스 원자력연구원 v smr 개발 슈퍼컴 구축 풀스택 ai 제공",
  "ko": 1,
  "id": "6b3846cd"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 FANCO와 차세대 SMR 'EAGL-1' 협력…EPC 참여 모색",
  "summary": "현대건설이 미국 FANCO의 차세대 SMR 프로젝트 'EAGL-1'에 협력하며 EPC(설계·조달·건설) 사업 참여를 검토한다.",
  "summaryLong": "현대건설이 미국의 원자력 기업 FANCO와 차세대 소형모듈원자로(SMR) 프로젝트 'EAGL-1'에 대한 협력 계약을 체결했다. 현대건설은 이 프로젝트에서 EPC(설계·조달·건설) 사업 참여를 적극 모색하고 있다. 이는 현대건설이 전통적 대형원전 건설 능력을 바탕으로 차세대 원자로 시장으로 진출하는 전략적 움직임이다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "KR",
  "source": "opinionnews.co.kr",
  "url": "https://www.opinionnews.co.kr/news/articleView.html?idxno=141487",
  "k": "현대건설 fanco와 차세대 smr eagl 1 협력 epc 참여 모색",
  "ko": 1,
  "id": "9b71f8e7"
 },
 {
  "date": "2026-07-14",
  "title": "NRC, 웨스팅하우스의 AP1000 표준설계인증 갱신 면제 승인",
  "summary": "미국 원자력규제위원회(NRC)가 웨스팅하우스의 AP1000 가압경수로(PWR) 표준설계인증(DC) 갱신을 위한 일정 요건 면제를 승인했다.",
  "summaryLong": "미국 원자력규제위원회(NRC)는 웨스팅하우스가 AP1000 가압경수로(PWR)의 표준설계인증(DC)을 갱신하고 업데이트하는 과정에서 신청 시기 제한에 대한 면제 요청을 승인했다. 이는 웨스팅하우스가 설계인증 갱신을 추진하는 데 있어 규제 절차상 중요한 진전으로, 갱신 일정의 유연성을 확보하게 됐음을 의미한다.",
  "cat": "인허가",
  "type": "PWR",
  "dev": "Westinghouse",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-07-14/article-8200/nrc-approves-westinghouse-exemption-request-for-ap1000-dc/",
  "k": "nrc approves westinghouse exemption request for ap1000 dc",
  "id": "8e72b8bf"
 },
 {
  "date": "2026-07-14",
  "title": "홀텍, IPO 등록명세서 공개 제출",
  "summary": "홀텍 뉴클리어 코퍼레이션(Holtec Nuclear Corporation)이 2026년 7월 10일 미국 증권거래위원회(SEC)에 신규공개(IPO) 등록명세서(Form S-1)를 제출했다.",
  "summaryLong": "홀텍 뉴클리어 코퍼레이션(Holtec Nuclear Corporation)은 2026년 7월 10일 미국 증권거래위원회(SEC)에 A급 보통주의 신규공개(IPO)와 관련된 등록명세서(Form S-1)를 공개 제출했다. 홀텍은 소형모듈원자로(SMR) 개발 업체로서 자본시장을 통한 자금 조달을 추진하고 있다.",
  "cat": "투자",
  "type": "PWR",
  "dev": "Holtec",
  "region": "US",
  "source": "Holtec International",
  "url": "https://holtecinternational.com/hh-41-11/",
  "k": "holtec nuclear corporation announces public filing of registration statement for proposed initial public offering",
  "id": "7bee8cb3"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설·FANCO, SMR 협력 양해각서 체결",
  "summary": "현대건설이 미국 FANCO와 EAGL-1 소형모듈원자로 프로젝트 협력을 위한 양해각서를 체결했다.",
  "summaryLong": "한국의 현대건설(Hyundai E&C)이 미국의 퍼스트 아메리칸 뉴클리어 컴퍼니(First American Nuclear Company, FANCO)와 EAGL-1 소형모듈원자로(SMR) 프로젝트에 대한 협력 양해각서를 체결했다. 이는 한국 기업이 미국 SMR 개발사와 국제 협력을 강화하는 사례로, 양국 간 SMR 사업 협의 체계를 마련한 것으로 의미가 있다.",
  "cat": "계약",
  "type": "General",
  "dev": "현대건설, FANCO",
  "region": "KR|US",
  "source": "World Nuclear News",
  "url": "https://www.world-nuclear-news.org/articles/hyundai-ec-fanco-to-collaborate-on-smr-project",
  "k": "hyundai e c fanco to collaborate on smr project",
  "id": "24e08e78"
 },
 {
  "date": "2026-07-14",
  "title": "아르헨티나의 첫 SMR 도입",
  "summary": "아르헨티나가 소형모듈원자로(SMR) 도입을 추진하는 것으로 보도되었다.",
  "summaryLong": "아르헨티나가 소형모듈원자로(SMR) 도입을 추진 중인 것으로 알려졌다. 보도에서는 아르헨티나의 첫 SMR 프로젝트에 대한 내용을 다루고 있으나, 제목과 스니펫만으로는 구체적인 개발사, 계약 내용, 일정 등의 세부사항이 불명확하다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "US",
  "source": "enlit.world",
  "url": "https://www.enlit.world/library/first-smr-deal-in-argentina-is-nuclear-investment-landmark",
  "k": "first smr for argentina",
  "id": "ea970ee1"
 },
 {
  "date": "2026-07-14",
  "title": "아이티센씨티에스, 원자력연구원 가상 SMR 개발용 슈퍼컴 구축",
  "summary": "아이티센씨티에스가 한국원자력연구원과 협력하여 가상 SMR(Virtual SMR) 개발을 위한 슈퍼컴퓨터 구축을 완료했다.",
  "summaryLong": "아이티센씨티에스가 한국원자력연구원과 함께 가상 SMR(Virtual SMR, V-SMR) 개발 프로젝트를 위한 슈퍼컴퓨터 구축을 완료했다고 보도되었다. 이는 한국의 SMR 기술 개발 인프라 확충을 의미하는 것으로, 수치해석 및 시뮬레이션 능력 강화를 목표로 한다.",
  "cat": "기술",
  "type": "General",
  "dev": "아이티센씨티에스",
  "region": "KR",
  "source": "sedaily.com",
  "url": "https://www.sedaily.com/article/20067763",
  "k": "아이티센씨티에스 원자력 가상 smr 개발 슈퍼컴 구축",
  "ko": 1,
  "id": "e886e70c"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 SMR 기업과 협력 - EAGL-1 프로젝트 기본협약",
  "summary": "현대건설이 미국 SMR 업체와 'EAGL-1 프로젝트' 기본협약을 체결하여 차세대 SMR 개발에 협력하기로 했다.",
  "summaryLong": "현대건설이 미국의 SMR 기업과 'EAGL-1 프로젝트' 관련 기본협약을 체결했다. 이 협력을 통해 현대건설은 미국 차세대 원자로 시장에 진출하며, 120만 가구에 전력을 공급할 수 있는 규모의 SMR 6기 건설에 참여할 계획이다. 보도에 따르면 현대건설은 미국 FANCO 등 SMR 업체와의 협력망을 확대하고 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "US",
  "source": "mt.co.kr",
  "url": "https://www.mt.co.kr/estate/2026/07/14/2026071410212383125",
  "k": "원전 6기로 120만가구 전력 공급 현대건설 smr 기업과 협력 머니투데이",
  "ko": 1,
  "id": "ee1e6486"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국(US) SMR 개발사 팬코(FANCO)와 납·비스무트 냉각로 협력",
  "summary": "현대건설이 미국의 소형모듈원자로(SMR) 개발사 팬코(FANCO)와 손을 잡고 납·비스무트 냉각로 기술 개발·사업화를 추진한다.",
  "summaryLong": "현대건설과 미국의 SMR 개발사 팬코(FANCO)가 협력 관계를 체결했다. 양사는 납·비스무트(lead-bismuth) 냉각식 소형모듈원자로 기술 개발 및 상용화를 공동으로 추진할 계획이다. 이는 현대건설이 해외 첨단원자로 기술 확보 및 국제 시장 진출을 노리는 전략적 파트너십으로 보인다. 납·비스무트 냉각로는 차세대 고속로 기술의 한 분야로, 안전성과 경제성 측면에서 주목받고 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "FANCO",
  "region": "US",
  "source": "market-ink.co.kr",
  "url": "https://www.market-ink.co.kr/news/articleView.html?idxno=9106",
  "k": "현대건설 smr 개발사 fanco와 손잡고 납 비스무트 냉각로 공략",
  "ko": 1,
  "id": "420bc0ec"
 },
 {
  "date": "2026-07-14",
  "title": "정부, 신규 원전·SMR 공론화…12차 전기본 반영 방침",
  "summary": "한국 정부가 제12차 전력수급기본계획에 신규 원전과 소형모듈원전(SMR)을 추가하는 방안을 국민 공론화를 통해 반영할 계획을 밝혔다.",
  "summaryLong": "한국 정부는 인공지능(AI) 데이터센터, 반도체 산단 등으로 인한 급증하는 전력수요에 대응하기 위해 제12차 전력수급기본계획에 신규 원전과 소형모듈원전(SMR) 추가를 반영할 방침을 밝혔다. 김성환 기후에너지환경부 장관은 2026년 국가재정전략회의에서 전력수요가 2040년까지 50GW 이상으로 급증할 것으로 예상되는 만큼, 재생에너지 확대와 함께 원전을 통한 대응이 필요하다고 강조했다. 이는 정부의 에너지 정책 방향이 SMR을 미래 에너지원으로 인정하고 있음을 보여주는 중요한 정책 신호이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "투데이에너지 - 전체기사",
  "url": "https://www.todayenergy.kr/news/articleView.html?idxno=300405",
  "k": "정부 신규 원전 smr 공론화 12차 전기본 반영 방침",
  "ko": 1,
  "id": "d3f90fb6"
 },
 {
  "date": "2026-07-14",
  "title": "아이티센씨티에스, 원자력연구원 V-SMR 슈퍼컴 구축 완료",
  "summary": "아이티센씨티에스가 한국원자력연구원의 V-SMR 슈퍼컴퓨터 구축을 완료했다.",
  "summaryLong": "아이티센씨티에스가 한국원자력연구원(KAERI)의 V-SMR(수직형 소형모듈원자로) 관련 슈퍼컴퓨터 구축 업무를 완료했다는 보도이다. 이는 국내 SMR 기술 개발의 핵심 인프라 구축으로, V-SMR의 설계·안전성 분석 및 시뮬레이션을 위한 계산 기반이 마련되었음을 의미하며 한국의 첨단로 개발 진전의 일부이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "it.chosun.com",
  "url": "https://it.chosun.com/news/articleView.html?idxno=2023092165784",
  "k": "아이티센씨티에스 원자력연구원 v smr 슈퍼컴 구축 완료",
  "ko": 1,
  "id": "cfdf838a"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 美 FANCO와 차세대 SMR 협력…4세대 원자로 협력망 확대",
  "summary": "현대건설이 미국의 FANCO와 차세대 소형모듈원자로(SMR) 개발에 협력하기로 합의했다.",
  "summaryLong": "현대건설이 미국 기업 FANCO와 차세대 소형모듈원자로(SMR) 개발 및 구축을 위한 협력 관계를 맺었다. 이는 현대건설의 4세대 원자로(첨단로) 국제 협력망 확대 전략의 일환으로, 미국 시장의 SMR 프로젝트 수주와 기술 개발을 강화하기 위한 파트너십 체결 사건이다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "US",
  "source": "greened.kr",
  "url": "https://www.greened.kr/news/articleView.html?idxno=344980",
  "k": "현대건설 fanco와 차세대 smr 협력 4세대 원자로 협력망 확대",
  "ko": 1,
  "id": "74c646b9"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 FANCO와 납-비스무트 냉각 SMR 사업 협력",
  "summary": "현대건설이 미국의 FANCO와 납-비스무트 냉각 방식의 SMR 사업 협력을 추진한다.",
  "summaryLong": "현대건설이 미국의 차세대 SMR 개발사 FANCO와 납-비스무트(Pb-Bi) 냉각 방식의 소형모듈원자로 사업 협력을 진행 중이다. 납-비스무트 냉각은 액체금속냉각 SMR 기술로, 고온·고밀도 에너지 특성으로 주목받고 있다. 현대건설은 이 협력을 통해 4세대 원전 기술 확보 및 미국 시장 진출을 강화하려는 전략이다.",
  "cat": "기술",
  "type": "FHR",
  "dev": "Hyundai E&C",
  "region": "US",
  "source": "newspost.kr",
  "url": "https://www.newspost.kr/news/articleView.html?idxno=224208",
  "k": "현대건설 fanco와 납 비스무트 냉각 smr 사업 협력",
  "ko": 1,
  "id": "51c3ba7a"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 차세대 SMR 개발사와 협약 체결…'풀라인업 완성'",
  "summary": "현대건설이 미국의 차세대 SMR 개발사와 협약을 체결하며 SMR 포트폴리오 확대를 완성했다.",
  "summaryLong": "현대건설이 미국의 차세대 SMR 개발사와 협약(MOU 또는 사업협약)을 체결했다. 현대건설은 이를 통해 여러 노형의 SMR 기술 확보로 완전한 포트폴리오(풀라인업)를 완성했다는 입장이다. 이는 글로벌 SMR 시장에서의 경쟁력 강화 및 다양한 고객 요구에 대응하기 위한 전략적 협력이다.",
  "cat": "기술",
  "type": "General",
  "dev": "Hyundai E&C",
  "region": "US",
  "source": "straightnews.co.kr",
  "url": "https://www.straightnews.co.kr/news/articleView.html?idxno=306968",
  "k": "현대건설 미국서 차세대 smr 개발사와 협약 풀라인업 완성",
  "ko": 1,
  "id": "e7d6ead8"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 4세대 SMR 사업 협력",
  "summary": "현대건설이 미국의 차세대 소형모듈원자로(SMR) 사업에 협력하기로 했다.",
  "summaryLong": "현대건설이 미국 내 4세대 소형모듈원자로(SMR) 개발·사업에 협력하기로 결정했으며, 차세대 원자로 시장을 공략하기 위한 전략을 추진 중이다. 구체적인 계약 상대방, 계약 내용, 건설 규모, 일정 등의 세부사항은 제공된 스니펫에 포함되지 않았다. 이는 한국 건설사의 해외 SMR 사업 참여를 나타내는 중요한 소식이다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "KR",
  "source": "it.chosun.com",
  "url": "https://it.chosun.com/news/articleView.html?idxno=2023092165762",
  "k": "현대건설 4세대 smr 사업 협력 차세대 원자로 공략 박차",
  "ko": 1,
  "id": "b9bccea6"
 },
 {
  "date": "2026-07-14",
  "title": "정부, 신규 원전·SMR 확대 공식 검토",
  "summary": "정부가 AI·반도체 산업의 전력 수요 급증에 대비하여 신규 원전과 소형모듈원자로(SMR) 확대를 공식 검토 중이다.",
  "summaryLong": "정부가 인공지능(AI)과 반도체 산업으로 인한 전력 수요 증가에 대응하기 위해 신규 원전과 소형모듈원자로(SMR) 확대를 공식적으로 검토하고 있다. 이는 에너지 안보와 산업 경쟁력 강화를 위한 정부 차원의 전략적 접근으로, 전력 대란 가능성을 사전에 예방하려는 목적으로 보인다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "dongponews.net",
  "url": "https://www.dongponews.net/news/articleView.html?idxno=59282",
  "k": "정부 신규 원전 smr 확대 공식 검토 ai 반도체 전력대란 대비",
  "ko": 1,
  "id": "5b9dbb01"
 },
 {
  "date": "2026-07-14",
  "title": "아이티센씨티에스, 원자력연구원 V-SMR 개발 슈퍼컴 구축",
  "summary": "아이티센씨티에스가 원자력연구원(KAERI)의 수직형 소형모듈원자로(V-SMR) 개발을 지원하기 위한 슈퍼컴퓨터를 구축한다.",
  "summaryLong": "아이티센씨티에스가 한국원자력연구원(KAERI)의 수직형 소형모듈원자로(V-SMR) 개발 프로젝트를 지원하기 위해 슈퍼컴퓨터 인프라를 구축하고 있다. 이는 V-SMR의 설계·분석·검증 업무를 가속화하기 위한 기술 협력으로, 국내 선진 SMR 개발의 중요한 마일스톤을 의미한다.",
  "cat": "기술",
  "type": "General",
  "dev": "KAERI",
  "region": "KR",
  "source": "digitaltoday.co.kr",
  "url": "https://www.digitaltoday.co.kr/news/articleView.html?idxno=684087",
  "k": "아이티센씨티에스 원자력연구원 v smr 개발 슈퍼컴 구축",
  "ko": 1,
  "id": "651c3ac7"
 },
 {
  "date": "2026-07-14",
  "title": "[심층 진단] SMR 패권 경쟁, 한국은 '제조'로 남을 것인가 '설계자'로 도약할 것인가",
  "summary": "한국의 SMR 산업 전략에 대한 심층 분석으로, 제조 기지 역할에서 설계 주도국으로의 도약 가능성을 진단한다.",
  "summaryLong": "국내 언론이 한국의 소형모듈원자로(SMR) 산업 전략을 진단하는 심층 분석 기사다. 글로벌 SMR 패권 경쟁 속에서 한국이 단순 제조업체로 남을 것인지, 아니면 설계·기술 주도국으로 도약할 것인지를 다룬다. SMR 정책·기술·산업 생태계 발전 방향에 대한 정책적·전략적 분석 내용으로 보인다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "newsvalue.kr",
  "url": "https://www.newsvalue.kr/news/articleView.html?idxno=24150",
  "k": "심층 진단 smr 패권 경쟁 한국은 제조 로 남을 것인가 설계자 로 도약할 것인가",
  "ko": 1,
  "op": 1,
  "id": "02e9b655"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 SMR 업체와 'EAGL-1 프로젝트' 기본 협약 체결",
  "summary": "현대건설이 미국 4세대 SMR 업체와 'EAGL-1 프로젝트'에 대한 기본 협약을 체결했다.",
  "summaryLong": "현대건설이 미국의 차세대 소형모듈원자로(SMR) 개발사와 'EAGL-1 프로젝트'의 기본 협약을 체결했다. 현대건설은 4세대 SMR 사업 협력을 통해 차세대 원자로 시장 진출을 추진하고 있으며, 이번 협약으로 첨단 원자로 협력망을 확대하고 있다. 한국 건설사의 미국 첨단 원자로 사업 참여를 의미하는 전략적 협력 사례다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "US",
  "source": "businesspost.co.kr",
  "url": "https://www.businesspost.co.kr/BP?command=article_view&num=442286",
  "k": "현대건설 미국 smr 업체와 eagl 1 프로젝트 기본 협약 체결",
  "ko": 1,
  "id": "acd33447"
 },
 {
  "date": "2026-07-14",
  "title": "삼성중공업, 부유식 데이터센터 구상 가운데 SOFC(고체산화물연료전지)를 넘어 SMR까지 추진",
  "summary": "삼성중공업이 부유식 데이터센터 프로젝트의 일환으로 소형모듈원자로(SMR) 도입을 검토하고 있다.",
  "summaryLong": "삼성중공업이 부유식 데이터센터 개발이라는 대형 구상 가운데 고체산화물연료전지(SOFC)를 거쳐 소형모듈원자로(SMR)까지 확대하려는 전략을 추진하고 있다. 이는 데이터센터의 장기 전력 수급 솔루션으로 SMR 활용 가능성을 검토하는 산업 응용 사례로 의미가 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "삼성중공업",
  "region": "KR",
  "source": "ebn.co.kr",
  "url": "https://www.ebn.co.kr/news/articleView.html?idxno=1716320",
  "k": "삼성중공업 부유식 데이터센터 큰 그림 sofc 넘어 smr까지",
  "ko": 1,
  "op": 1,
  "id": "f8b56322"
 },
 {
  "date": "2026-07-14",
  "title": "양자 컴퓨팅을 FLiBe 화학 계산에 응용, 삼중수소 번식 기술 진전",
  "summary": "연구팀이 양자·고전 컴퓨팅 결합으로 FLiBe(불화리튬베릴륨) 용융염 블랑켓 내 삼중수소 분광(tritium speciation) 화학 계산을 수행했으며, 핵융합 장비의 삼중수소 번식 잠금 해제를 위한 유망한 방향을 입증했다.",
  "summaryLong": "연구팀이 양자 컴퓨팅과 고전 컴퓨팅의 결합 방식을 활용하여 FLiBe(불화리튬(lithium fluoride)·불화베릴륨(beryllium fluoride)) 용융염 블랑켓에서 삼중수소 분광 관련 화학 계산을 수행했다. 이는 향후 핵융합 기계에서 삼중수소 번식을 활성화하기 위한 유망한 기술 방향을 제시한다. 용융염 냉각로(MSR) 및 핵융합 시스템의 삼중수소 취급 및 번식 기술 개발에 기여할 수 있는 기초 연구 성과이다.",
  "cat": "기술",
  "type": "MSR",
  "dev": "",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-07-14/article-8203/team-brings-quantum-computing-into-flibe-chemistry-calculations/",
  "k": "team brings quantum computing into flibe chemistry calculations",
  "id": "4d1a76f5"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 차세대 원전 'EAGL-1' 건설",
  "summary": "현대건설이 미국의 차세대 원전 프로젝트 'EAGL-1'의 건설을 진행.",
  "summaryLong": "현대건설이 미국 시장에서 차세대 원전 프로젝트 'EAGL-1'의 건설 사업을 수주하여 추진 중이다. 이는 현대건설의 미국 원자력 시장 진출과 차세대 원자로 건설 기술 수출을 나타내는 실제 계약 및 사업 이행 사항이다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "US",
  "source": "esnews.kr",
  "url": "https://www.esnews.kr/news/articleView.html?idxno=5037",
  "k": "k 건설 미국 원전 시장에 깃발 현대건설 차세대 원전 eagl 1 건설",
  "ko": 1,
  "id": "8ee0342d"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 SMR 프로젝트 본격 착수",
  "summary": "현대건설이 미국의 소형모듈원자로(SMR) 프로젝트를 본격적으로 시작하며 차세대 원자로 시장 진출을 강화하고 있다.",
  "summaryLong": "현대건설이 미국의 SMR(소형모듈원자로) 프로젝트를 본격적으로 추진하기 시작했다. 이는 현대건설이 차세대 원자로 시장에서의 입지를 강화하려는 전략적 움직임으로 평가된다. SMR은 대형 원전 대비 소규모이면서도 높은 효율성을 갖춘 차세대 원자로로, 미국과 국제 시장에서 주목받고 있다. 현대건설의 이번 프로젝트 착수는 한국 기업의 첨단 원자로 분야 진출 사례로, 향후 글로벌 SMR 시장 경쟁에서의 위치 강화를 의도하고 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "현대건설",
  "region": "US",
  "source": "gokorea.kr",
  "url": "https://www.gokorea.kr/news/articleView.html?idxno=872029",
  "k": "현대건설 미국 smr 프로젝트 본격 착수 차세대 원자로 시장 공략 강화",
  "ko": 1,
  "id": "6a491795"
 },
 {
  "date": "2026-07-13",
  "title": "홀텍(Holtec), 인도 SMR 사업 포함한 IPO 추진",
  "summary": "미국 핵심 기업 홀텍(Holtec)이 인도에서의 소형모듈원자로(SMR) 사업을 포함하여 기업공개(IPO)를 추진 중이다.",
  "summaryLong": "미국 원자력 기업 홀텍(Holtec)이 기업공개(IPO) 계획을 발표했으며, 이 과정에서 인도에서의 소형모듈원자로(SMR) 사업이 포함될 것으로 예상된다. 홀텍의 IPO는 회사의 국제적 사업 확장, 특히 인도 시장에서의 SMR 기술 전개 의지를 반영하는 것으로 보인다. 이는 홀텍이 글로벌 SMR 시장에서의 입지를 강화하려는 전략의 일환이다.",
  "cat": "투자",
  "type": "PWR",
  "dev": "Holtec",
  "region": "US",
  "source": "indianexpress.com",
  "url": "https://indianexpress.com/article/business/holtec-ipo-india-small-modular-reactor-smr-ntpc-10783696/",
  "k": "us nuclear firm holtec s ipo plans could have an india smr footprint",
  "op": 1,
  "id": "698f1008"
 },
 {
  "date": "2026-07-13",
  "title": "소형모듈원자로(SMR), 연구개발 넘어 상용화로 지원 특별법 개정 추진",
  "summary": "소형모듈원자로(SMR)의 상용화와 수출을 국가 차원에서 지원하는 특별법 개정안이 국회에 발의되었다.",
  "summaryLong": "더불어민주당 허성무 의원이 '소형모듈원자로(SMR) 개발 촉진 및 지원에 관한 특별법' 개정안을 발의했다. 데이터센터 증가로 인한 전력 수요 급증에 대응하기 위해 소형모듈원자로(SMR)의 상용화와 글로벌 시장 진출을 지원하도록 법안을 개정하는 것을 목표로 하고 있다. 현행 법은 연구개발과 실증 중심이었으나, 개정안은 산업화와 수출 지원까지 확대하여 국내 소형모듈원자로(SMR) 산업 생태계를 강화하겠다는 취지다. 현행법은 오는 9월 시행을 앞두고 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "에너지신문 - 전체기사",
  "url": "https://www.energy-news.co.kr/news/articleView.html?idxno=226754",
  "k": "smr 연구개발 넘어 상용화로 지원 특별법 개정 추진",
  "ko": 1,
  "id": "d3c263d3"
 },
 {
  "date": "2026-07-13",
  "title": "경남, 'SMR 진흥특구' 지정 추진…미래 원전산업 거점화",
  "summary": "경남도가 소형모듈원자로(SMR) 진흥특구 지정을 추진 중인 것으로 보도됐다.",
  "summaryLong": "경남도가 소형모듈원자로(SMR)를 중심으로 한 '진흥특구' 지정을 추진하는 것으로 알려졌다. 이는 경남 지역을 미래 원전산업의 거점으로 육성하기 위한 지역 정책 차원의 노력으로 평가된다. 구체적 특구 조성 일정, 규모, 지원 내용 등의 세부사항은 제시되지 않았으며, 특구 지정의 확실성도 불명확한 상태이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "news.nate.com",
  "url": "https://news.nate.com/view/20260713n11020",
  "k": "미래 원전 둥지 튼다 경남 smr 진흥특구 날개 달까",
  "ko": 1,
  "op": 1,
  "id": "88aef8cc"
 },
 {
  "date": "2026-07-13",
  "title": "테라파워(TerraPower), 미국 승인으로 SMR 상용화 진전",
  "summary": "테라파워(TerraPower)가 미국 승인을 획득하며 소형모듈원자로(SMR) 상용화를 진전시켰다.",
  "summaryLong": "테라파워(TerraPower)가 미국의 승인을 획득하여 소형모듈원자로(SMR) 상용화 추진을 한 단계 진전시켰다. 제시된 정보는 제목 수준의 기본 사실만 담고 있으나, 미국 규제당국의 공식 승인 획득은 개발사의 주요 인허가 마일스톤으로 평가된다. 이는 테라파워의 고급로 기술 개발이 규제 심사를 통과했음을 의미하며, 상용화 타임라인 단축에 긍정적 신호로 작용할 것으로 전망된다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "US",
  "source": "chosun.com",
  "url": "https://www.chosun.com/english/national-en/2026/07/13/56LCOKATNJE2BMAUTZNDS5H6SI/",
  "k": "terrapower advances smr commercialization with u s approval",
  "ko": 1,
  "id": "cd3706af"
 },
 {
  "date": "2026-07-13",
  "title": "김성환 기후부 장관 \"전력 수요 폭발 대응…신규 원전·SMR 추가 건설 공식 검토\"",
  "summary": "한국 기후부 장관이 전력 수요 증가에 대응하기 위해 신규 원전과 소형모듈원자로(SMR) 추가 건설을 공식 검토 중임을 밝혔다.",
  "summaryLong": "김성환 한국 기후부 장관이 급증하는 전력 수요 대응을 위해 신규 대형 원전과 소형모듈원자로(SMR) 추가 건설을 정부 차원에서 공식적으로 검토 중이라고 발표했다. 이는 한국 정부의 SMR 정책 의지를 보여주는 정책 신호로, 향후 SMR 사업 추진 기반이 될 수 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "m-i.kr",
  "url": "https://www.m-i.kr/news/articleView.html?idxno=1391030",
  "k": "김성환 기후부 장관 전력 수요 폭발 대응 신규 원전 smr 추가 건설 공식 검토",
  "ko": 1,
  "id": "84bdfc1b"
 },
 {
  "date": "2026-07-13",
  "title": "박상웅 의원, AI 시대 \"차세대 원전\" 상용화 법안 발의",
  "summary": "국회 의원이 인공지능(AI) 시대의 에너지 수요에 대응하기 위해 차세대 원전(SMR·첨단로) 상용화를 지원하는 법안을 발의했다.",
  "summaryLong": "박상웅 국회 의원이 인공지능(AI) 시대의 급증하는 전력 수요를 충족하기 위해 소형모듈원자로(SMR) 및 차세대 고급 원자로의 상용화를 촉진하는 법안을 국회에 발의했다. \"실험실 밖으로\"라는 기치 하에 기술 개발 단계를 넘어 실제 상용화 지원을 목표로 하는 정책 입법으로, SMR·첨단로 사업 확대를 위한 제도적 기반 마련을 의도하고 있다.",
  "cat": "정책",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "esnews.kr",
  "url": "https://www.esnews.kr/news/articleView.html?idxno=5001",
  "k": "실험실 밖으로 박상웅 의원 ai 시대 핵심 차세대 원전 상용화 법안 발의",
  "ko": 1,
  "id": "f8e796d0"
 },
 {
  "date": "2026-07-13",
  "title": "두산에너빌리티 SMR 매출 2031년 6조원 목표, 내년부터 본격화",
  "summary": "두산에너빌리티가 SMR 사업으로 2031년 6조원의 매출을 목표로 하고 있으며, 내년부터 본격적인 매출을 시작할 계획이다.",
  "summaryLong": "두산에너빌리티가 소형모듈원자로(SMR) 사업의 매출 목표를 2031년 6조원으로 설정했다고 발표했다. 회사는 2025년부터 SMR 관련 매출이 본격적으로 발생할 것으로 전망하고 있다. 이는 두산에너빌리티의 SMR 사업이 상용화 단계로 진입하고 있음을 시사한다.",
  "cat": "기술",
  "type": "General",
  "dev": "두산에너빌리티",
  "region": "KR",
  "source": "fntimes.com",
  "url": "https://www.fntimes.com/html/view.php?ud=202607131426542333fa6b69a559_18",
  "k": "두산에너빌리티 smr 매출 2031년 6조 내년부터 매출 본격화",
  "ko": 1,
  "id": "5b308ccb"
 },
 {
  "date": "2026-07-13",
  "title": "호남 반도체 전력 부족 우려에 원전·SMR 추가 건설 검토",
  "summary": "호남 지역 반도체 산업의 전력 부족 우려에 따라 정부가 원전과 SMR 추가 건설을 검토하고 있다.",
  "summaryLong": "호남 지역의 반도체 산업 확대에 따른 전력 수급 부족 문제를 해결하기 위해 정부가 원전과 소형모듈원자로(SMR) 추가 건설을 검토하기 시작했다. 이는 탈원전 정책 속도전과 에너지 수급 현실 사이의 긴장 속에서 이루어지고 있다. SMR은 호남 지역의 에너지 솔루션으로서 주목받고 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "v.daum.net",
  "url": "https://v.daum.net/v/20260713162209478",
  "k": "호남 반도체 전력 부족 우려에 원전 smr 추가 건설 검토 탈원전 속도전",
  "ko": 1,
  "op": 1,
  "id": "88fab9b6"
 },
 {
  "date": "2026-07-13",
  "title": "한수원 iSMR 및 원격로봇 등 미래 원전 안전기술 공개",
  "summary": "한국수력원자력이 국내형 소형모듈원자로(iSMR)와 원격로봇 등 미래 원전 안전기술을 공개했다.",
  "summaryLong": "한국수력원자력(한수원)이 국내형 소형모듈원자로(iSMR)와 원격로봇 기술 등 미래 원전의 안전성을 강화하기 위한 첨단 기술들을 공개했다. 이는 한수원의 iSMR 개발 현황과 차세대 원전 안전 기술 개발 진행 상황을 보여주는 것이다. 한수원은 이를 통해 국내 SMR 기술의 발전 수준을 대외적으로 입증하고 있다.",
  "cat": "기술",
  "type": "PWR",
  "dev": "한수원",
  "region": "KR",
  "source": "inpnews.kr",
  "url": "https://www.inpnews.kr/news/articleView.html?idxno=7328",
  "k": "한수원 ismr 원격로봇 등 미래 원전 안전기술 공개",
  "ko": 1,
  "id": "36116e5d"
 },
 {
  "date": "2026-07-13",
  "title": "경남, 243개 원전기업 보유…SMR 산업화 추진",
  "summary": "경남이 243개의 원전 관련 기업을 보유하고 있으며, SMR을 연구 단계에서 산업 단계로 전환하는 정책을 추진 중이다.",
  "summaryLong": "경남도가 보유한 243개의 원전 관련 기업들을 기반으로 소형모듈원자로(SMR)를 순수 연구개발 영역에서 상용화·산업화 단계로 진전시키는 정책을 추진하고 있다. 경남이 국내 원전 산업의 중심지로서 SMR 생태계 확대에 주력하는 모습을 보여준다. 이는 정부의 SMR 산업화 방향과 궤를 같이하는 지역 차원의 응대 전략이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "sedaily.com",
  "url": "https://www.sedaily.com/article/20067044",
  "k": "원전기업 243개 품은 경남 smr 연구 서 산업 으로 판 커진다",
  "ko": 1,
  "id": "16ac33fa"
 },
 {
  "date": "2026-07-13",
  "title": "SMR 정책 '과기부 단독'에서 공동 추진… 공급망·금융지원 담은 특별법 개정 추진",
  "summary": "정부가 소형모듈원자로(SMR) 개발 정책을 기후에너지환경부와 공동 추진 체계로 전환하고, 금융·세제 지원과 공급망 육성을 담은 특별법 개정을 추진 중이다.",
  "summaryLong": "국회 산업통상자원중소벤처기업위원회 허성무 의원(더불어민주당, 경남 창원시성산구)이 소형모듈원자로(SMR) 개발 정책의 대폭적 개편 내용을 담은 '소형모듈원자로 개발 촉진 및 지원에 관한 특별법 일부개정법률안'을 국회에 제출했다. 현재 과학기술정보통신부 중심의 추진체계를 기후에너지환경부와의 공동 추진 체계로 개편하고, 연구개발 중심에서 산업화·수출 중심으로 정책 방향을 확대한다. 금융·세제 지원, 공급망 육성, 진흥특구 지정 근거 등을 새로 포함하여 SMR 산업 생태계를 본격적으로 육성하려는 법안이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "에너지데일리 - 전체기사",
  "url": "https://www.energydaily.co.kr/news/articleView.html?idxno=201360",
  "k": "smr 정책 과기부 단독 에서 공동 추진 공급망 금융지원 담은 특별법 개정 추진",
  "ko": 1,
  "id": "16246de2"
 },
 {
  "date": "2026-07-13",
  "title": "원전 공급망 '진영화' 반영한 한미일 SMR 협력… 중러에 대항",
  "summary": "한국, 미국, 일본의 소형모듈원자로(SMR) 협력이 원전 공급망의 진영화 현상을 반영하고 있으며, 중국·러시아에 대항하는 성격을 갖는다.",
  "summaryLong": "한국, 미국, 일본이 추진 중인 소형모듈원자로(SMR) 협력은 국제 원자력 공급망에서 나타나는 진영화 현상을 반영한 것이라는 분석이 제시되고 있다. 이는 중국과 러시아의 원자력 기술 진출에 대항하기 위한 전략적 협력으로 평가되며, 한미일 삼국의 SMR 협력 강화는 민주주의 진영의 원자력 산업 경쟁력 확보와 공급망 선진화를 목표로 하고 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "연합뉴스 최신기사",
  "url": "https://www.yna.co.kr/view/AKR20260713131100504",
  "k": "원전 공급망 진영화 반영한 한미일 smr 협력 중러에 대항",
  "ko": 1,
  "id": "121ad5bd"
 },
 {
  "date": "2026-07-13",
  "title": "현대건설 SMR 파트너 홀텍, 나스닥 IPO 계획",
  "summary": "현대건설의 소형모듈원전(SMR) 파트너 기업인 홀텍(Holtec)이 나스닥(NASDAQ) 상장을 계획하고 있다.",
  "summaryLong": "현대건설과 협력하고 있는 미국 SMR 기업 홀텍(Holtec)이 미국 나스닥(NASDAQ) 거래소에 신규공개상장(IPO)을 추진하고 있다. 이는 현대건설이 추진 중인 해외 소형모듈원전(SMR) 사업의 자금 조달과 기업 가치 확대를 의미하며, 글로벌 SMR 시장에서 한국 기업의 영향력 확대 신호로 해석된다.",
  "cat": "투자",
  "type": "PWR",
  "dev": "Holtec",
  "region": "US",
  "source": "hankyung.com",
  "url": "https://www.hankyung.com/article/202607132829i",
  "k": "현대건설 smr 파트너 홀텍 나스닥 ipo 계획",
  "ko": 1,
  "id": "a913d76e"
 },
 {
  "date": "2026-07-12",
  "title": "SK이노베이션, 테라파워와 소형모듈원자로 상용화 가속",
  "summary": "SK이노베이션(SK Innovation)과 테라파워(TerraPower)가 소형모듈원자로(SMR) 상용화 협력을 가속화한다는 조선일보 보도.",
  "summaryLong": "조선일보에 따르면 한국의 SK이노베이션(SK Innovation)과 미국의 테라파워(TerraPower)가 소형모듈원자로(SMR) 상용화를 위한 협력을 가속화하고 있다. 두 기업 간의 협력 강화는 글로벌 SMR 시장에서의 경쟁 심화 속에 한국 기업의 입지를 강화하는 의미가 있으며, 상용 배치 일정과 기술 협력 방식에 대한 구체적 진전이 예상된다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "SK Innovation / TerraPower",
  "region": "KR",
  "source": "chosun.com",
  "url": "https://www.chosun.com/english/national-en/2026/07/13/56LCOKATNJE2BMAUTZNDS5H6SI/",
  "k": "sk innovation terrapower accelerate smr commercialization",
  "ko": 1,
  "id": "cd3706af"
 },
 {
  "date": "2026-07-11",
  "title": "뉴스케일(NuScale), 지연과 약한 실적으로 7.4% 하락",
  "summary": "뉴스케일(NuScale)의 프로젝트 지연과 확정 계약 부재로 주가가 7.4% 하락했다는 보도.",
  "summaryLong": "뉴스케일(NuScale)의 소형모듈원자로(SMR) 사업이 지연되고 실적이 부진하며 확정된 계약이 없다는 점으로 인해 주가가 7.4% 하락했다고 보도된 기사로, 회사의 사업 진행 상황과 계약 현황에 대한 실질적 소식에 해당한다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "NuScale",
  "region": "US",
  "source": "finance.yahoo.com",
  "url": "https://finance.yahoo.com/markets/stocks/articles/why-nuscale-power-smr-down-150821532.html",
  "k": "why nuscale power smr is down 7 4 after mounting delays weak results and no firm contracts",
  "id": "a571edbd"
 },
 {
  "date": "2026-07-10",
  "title": "NRC, 테네시 클린치 리버 사이트의 TVA 소형모듈원자로(BWRX-300) 건설허가 권고",
  "summary": "미국원자력규제위원회(NRC) 직원이 테네시(Tennessee) 클린치 리버(Clinch River) 부지에서 테네시밸리오써리티(TVA)의 BWRX-300 소형모듈원자로 건설을 위한 건설허가를 권고했다.",
  "summaryLong": "미국원자력규제위원회(NRC) 직원이 테네시밸리오써리티(TVA)가 테네시 클린치 리버 부지에서 추진 중인 BWRX-300 소형모듈원자로(SMR) 프로젝트에 대해 건설허가를 권고했다. BWRX-300은 캐나다 롤스로이스(Rolls-Royce SMR)가 개발한 소형 비등경수로(BWR) 기반 설계로, 미국 내 SMR 상용화의 중요한 진전을 나타낸다. 이는 대형 원전과 달리 소형 규모로 기존 화력발전소 부지 등에 배치 가능한 첨단 원자력 기술의 규제 승인 단계로 진행 중임을 보여준다.",
  "cat": "인허가",
  "type": "BWR",
  "dev": "TVA/Rolls-Royce",
  "region": "US",
  "source": "energiesmedia.com",
  "url": "https://energiesmedia.com/nrc-recommends-bwrx-300-permit-reactor/",
  "k": "nrc staff recommend construction permit for tva s bwrx 300 small modular reactor at clinch river site in tennessee",
  "id": "974f62d9"
 },
 {
  "date": "2026-07-10",
  "title": "미국 원자력위원회(NRC), 웨스팅하우스 AP1000 설계인증 갱신 면제",
  "summary": "미국 원자력위원회(NRC)가 웨스팅하우스(Westinghouse)에 보겔(Vogtle) 3·4호기 건설·운영 경험을 반영한 AP1000(가압경수로, PWR) 표준설계인증 갱신 신청을 인증서 만료 전에 진행할 수 있도록 면제했다.",
  "summaryLong": "미국 원자력위원회(NRC)가 웨스팅하우스(Westinghouse)에 AP1000 표준설계인증(Standard Design Certification) 갱신 신청을 통상적 규칙보다 앞당겨 진행할 수 있도록 허용했다. 이는 보겔(Vogtle) 3·4호기의 건설 및 운영 경험에서 나온 교훈을 신규 설계인증에 반영하기 위한 것이다. 현 인증서의 만료까지 충분한 여유를 두고 갱신 절차를 시작할 수 있어, 인증서 단절 없이 차세대 AP1000 기술 표준화를 이룰 수 있게 된다.",
  "cat": "인허가",
  "type": "PWR",
  "dev": "Westinghouse",
  "region": "US",
  "source": "World Nuclear News",
  "url": "https://www.world-nuclear-news.org/articles/nrc-exempts-westinghouse-from-design-certification-renewal-rule",
  "k": "nrc exempts westinghouse from design certification renewal rule",
  "id": "3e29fa6a"
 },
 {
  "date": "2026-07-09",
  "title": "산업 소식 — 2026년 7월: 하드론 에너지, 할로 원자로 사업결합 완료",
  "summary": "하드론 에너지(Hadron Energy)가 기가캐피탈7(GigCapital7)과의 사업결합을 완료하고 할로(Halo) 마이크로원자로 개발을 진전시키고 있다.",
  "summaryLong": "미국원자력학회(ANS) 뉴스와이어의 2026년 7월 산업 소식 요약에서 하드론 에너지(Hadron Energy)가 기가캐피탈7(GigCapital7 Corp.)과의 사업결합을 완료했음을 보도했다. 이 기업결합을 통해 하드론 에너지는 할로(Halo)라는 마이크로원자로 개발 프로젝트를 추진하고 있으며, 이는 초소형 모듈형 원자로 분야의 중요한 기업 결합 사건이다.",
  "cat": "기술",
  "type": "Micro",
  "dev": "Hadron Energy",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-07-09/article-8165/industry-updatejuly-2026/",
  "k": "industry update july 2026",
  "id": "15f346c1"
 },
 {
  "date": "2026-07-08",
  "title": "딥 피션(Deep Fission), 원형 원자로 용기 시제품 인수",
  "summary": "캘리포니아 스타트업 딥 피션(Deep Fission)이 시추공 매설형 소형모듈원자로(SMR) 프로젝트용 원형 원자로 용기 시제품을 파슨스(Parsons) 부지에서 인수했다.",
  "summaryLong": "캘리포니아(California) 기반 스타트업 딥 피션(Deep Fission)은 지하 1마일 깊이의 시추공(borehole) 내에 소형모듈원자로(SMR)를 설치하는 기술 개발을 추진 중이며, 이번에 캔자스(Kansas) 주의 파슨스(Parsons) 부지에서 해당 프로젝트 파일럿용 원형 원자로 용기 시제품을 인수했다. 이는 차세대 SMR 기술의 물리적 구현 단계로, 개념 설계를 벗어나 실제 하드웨어 개발이 진행되고 있음을 의미한다.",
  "cat": "기술",
  "type": "Micro",
  "dev": "Deep Fission",
  "region": "US",
  "source": "World Nuclear News",
  "url": "https://www.world-nuclear-news.org/articles/deep-fission-receives-prototype-reactor-canister",
  "k": "deep fission receives prototype reactor canister",
  "id": "9fad13f2"
 },
 {
  "date": "2026-07-07",
  "title": "DL이앤씨, 엑스에너지 Xe-100 표준화 설계 수주",
  "summary": "DL이앤씨가 국내 건설사로는 처음으로 미국 엑스에너지(X-energy)의 Xe-100 소형모듈원자로 표준화 설계를 수주했다.",
  "summaryLong": "한국의 건설사 DL이앤씨가 미국의 SMR 개발사 엑스에너지의 고온가스로(HTGR) 기술인 Xe-100에 대한 표준화 설계(design certification) 업무를 수주했으며, 이는 국내 건설사가 미국 첨단 소형모듈원자로 설계 인증에 참여한 첫 사례이다. 이는 한국 건설 산업의 국제 원자력 시장 진출과 엑스에너지의 설계 인증 추진을 위한 역량 강화를 의미하며, 양사 간 협력 체계가 강화되고 있음을 보여준다.",
  "cat": "계약",
  "type": "HTGR",
  "dev": "X-energy",
  "region": "US",
  "source": "market-ink.co.kr",
  "url": "https://www.market-ink.co.kr/news/articleView.html?idxno=8818",
  "k": "dl이앤씨 국내 건설사 최초 smr 표준화 설계 수주 엑스에너지 xe 100 파트너",
  "ko": 1,
  "id": "8035d6e9"
 },
 {
  "date": "2026-07-07",
  "title": "폴란드 SGE, 영국에 BWRX-300 14기 배치 제안",
  "summary": "폴란드의 신타스 그린 에너지(Synthos Green Energy)가 영국 3개 부지에 GE 베르노바 히타치 뉴클리어 에너지(GE Vernova Hitachi Nuclear Energy)의 BWRX-300 소형모듈원자로 14기 배치를 제안했다.",
  "summaryLong": "폴란드 바르샤바 소재의 개발·투자 회사 신타스 그린 에너지(Synthos Green Energy)가 영국에서 BWRX-300(비등경수로/BWR 기반 소형모듈원자로) 14기를 3개 다중 부지에 배치하는 사업을 발표했다. SGE가 이 영국 프로젝트를 위해 SGE SMR UK Limited라는 전담 법인을 설립했으며, 약 350억 파운드(GBP 35bn) 규모의 민간 자본 투자 유치를 검토하고 있는 것으로 전해졌다. 이는 영국의 에너지 안보와 탄소중립 목표 달성에 소형모듈원자로를 활용하려는 국제적 움직임의 일환으로 평가된다.",
  "cat": "기술",
  "type": "BWR",
  "dev": "SGE",
  "region": "UK",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-07-07/article-8183/polish-company-sge-hopes-to-deploy-14-bwrx300-reactors-in-uk/",
  "k": "polish company sge hopes to deploy 14 bwrx 300 reactors in u k",
  "id": "13b8ec6b"
 },
 {
  "date": "2026-07-05",
  "title": "뉴스케일(NuScale) 파라곤과 원자로 보호 계약 체결 후 소송 직면",
  "summary": "뉴스케일(NuScale)이 파라곤(Paragon)과 원자로 보호 계약을 체결했으나 소송에 직면하고 있다.",
  "summaryLong": "소형모듈원자로(SMR) 개발사인 뉴스케일(NuScale)이 파라곤(Paragon)과 원자로 보호(Reactor Protection) 관련 계약을 체결했다. 그러나 이 계약을 둘러싼 소송이 제기되었으며, 계약의 구체적 내용과 소송의 쟁점에 대한 상세 정보는 제시되지 않았다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "NuScale",
  "region": "US",
  "source": "finance.yahoo.com",
  "url": "https://finance.yahoo.com/markets/stocks/articles/nuscale-power-smr-faces-lawsuit-151304822.html",
  "k": "nuscale power smr faces lawsuit as it awards paragon reactor protection contract",
  "id": "074f0909"
 },
 {
  "date": "2026-07-01",
  "title": "i-SMR 기술개발사업단, 싱가포르 에너지시장청과 협력",
  "summary": "한국의 i-SMR(혁신형 소형모듈원자로) 기술개발사업단이 싱가포르 에너지시장청(EMA)과 협력 양해각서를 체결했다.",
  "summaryLong": "한국 정부의 i-SMR(혁신형 소형모듈원자로) 기술개발사업단이 싱가포르 에너지시장청(Energy Market Authority, EMA)과의 협력을 추진한다. 이는 한국의 소형모듈원자로 기술을 싱가포르 등 아시아 에너지 시장으로 확대하기 위한 전략적 파트너십이다. 양국 간 기술 정보 공유 및 규제 협력을 통해 i-SMR의 해외 인허가 기반을 마련하고자 한다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "i-SMR",
  "region": "KR",
  "source": "newsis.com",
  "url": "https://www.newsis.com/view/NISX20260701_0003691513",
  "k": "i smr 기술개발사업단 싱가포르 에너지시장청과 협력",
  "ko": 1,
  "id": "43462ee1"
 },
 {
  "date": "2026-07-01",
  "title": "엑스에너지, 영국 센트리카와 6GW 원전 파트너십 GDA 신청",
  "summary": "첨단원자로 개발사 엑스에너지(X-energy)가 영국(UK) 센트리카(Centrica)와의 6GW 파트너십을 위해 영국 범용설계심사(GDA) 신청을 진행했다.",
  "summaryLong": "첨단원자로 개발사 엑스에너지(X-energy)는 2026년 6월 2일 영국(UK)의 범용설계심사(Generic Design Assessment, GDA) 신청서를 제출했다고 발표했다. 이는 영국 에너지 기업 센트리카(Centrica)와 진행 중인 6GW 규모의 원전 파트너십 사업과 관련된 것으로, 규제 승인 절차의 중요한 단계를 나타낸다.",
  "cat": "인허가",
  "type": "HTGR",
  "dev": "X-energy",
  "region": "UK",
  "source": "POWER Magazine",
  "url": "https://www.powermag.com/power-digest-july-2026/",
  "k": "power digest july 2026",
  "id": "21f7b82e"
 },
 {
  "date": "2026-07-01",
  "title": "i-SMR 사업단, 싱가포르와 SMR 협력 양해각서 체결",
  "summary": "한국 혁신형 소형모듈원자로(i-SMR) 사업단이 싱가포르 에너지시장청(EMA)과 SMR 분야 협력을 위한 양해각서를 체결했다.",
  "summaryLong": "혁신형 소형모듈원자로 기술개발사업단(i-SMR)은 지난달 30일 싱가포르에서 개최된 'Asia Nuclear Energy & SMR 2026' 행사에서 싱가포르 에너지시장청(EMA)과 소형모듈원자로(SMR) 분야 협력 강화를 위한 양해각서(MOU)를 체결했다. 싱가포르 정부는 전력의 90% 이상을 수입 천연가스(LNG)에 의존하고 있으며, 화석연료 의존도를 낮추고 에너지원을 다변화하기 위한 핵심 대안으로 원자력 도입을 검토 중이다. 인구 밀집도가 높은 싱가포르의 환경적 특성을 고려할 때 SMR이 적합한 선택지로 평가되고 있으며, 이번 협력은 양국 간 SMR 기술 협력의 기초를 마련하는 의미를 갖는다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "i-SMR",
  "region": "KR",
  "source": "투데이에너지 - 전체기사",
  "url": "https://www.todayenergy.kr/news/articleView.html?idxno=299812",
  "k": "i smr 사업단 싱가포르 에너지시장청과 smr 협력",
  "ko": 1,
  "id": "23e963b9"
 },
 {
  "date": "2026-07-01",
  "title": "미국 원자력규제위원회, Clinch River BWRX-300 건설허가 추천",
  "summary": "미국 원자력규제위원회(NRC) 직원이 테네시 주 Clinch River 부지에 GE 베르노바 히타치(GE Vernova Hitachi) BWRX-300 원자로 건설을 위한 건설허가를 발급할 것을 권고했다.",
  "summaryLong": "미국 원자력규제위원회(NRC) 직원들이 테네시 밸리 오소리티(TVA)의 테네시 주 Clinch River 부지에 GE 베르노바 히타치(GE Vernova Hitachi) BWRX-300 비등경수로(BWR) 원자로 건설을 위한 건설허가를 발급할 것을 권고했다. 이 권고는 건설허가 신청 과정의 일환으로 공표된 안전성 평가 보고서에 포함되어 있다. BWRX-300은 소형모듈원자로(SMR) 개발의 주요 프로젝트로, 이번 허가 권고는 미국 SMR 상용화의 중요한 진전을 나타낸다.",
  "cat": "인허가",
  "type": "BWR",
  "dev": "GE Vernova Hitachi",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-07-01/article-8174/clinch-river-construction-permit-recommendation-follows-safety-evaluation/",
  "k": "clinch river construction permit recommendation follows safety evaluation",
  "id": "b9b49321"
 },
 {
  "date": "2026-06-25",
  "title": "스웨덴, 롤스로이스 SMR 개발사에 60% 지분 인수",
  "summary": "스웨덴 정부가 롤스로이스(Rolls-Royce) 소형모듈원자로 3기 건설을 추진하는 비데베리 크래프트(Videberg Kraft AB)에 60% 지분을 취득하기로 결정했다.",
  "summaryLong": "스웨덴 정부는 링할스(Ringhals) 인근 바뢰반도(Värö Peninsula)에 롤스로이스(Rolls-Royce) 소형모듈원자로 3기 건설을 계획 중인 비데베리 크래프트(Videberg Kraft AB)에 60% 지분을 취득하기로 결정했다. 이는 스웨덴이 SMR 기술 개발 및 구현에 국가 차원의 투자와 지원을 강화하려는 의지를 보여준다. 롤스로이스의 소형모듈원자로는 유럽에서 설계인증을 추진 중인 프로젝트로, 이번 스웨덴 정부의 지분 인수는 프로젝트 실현 가능성을 높이는 중요한 진전이다.",
  "cat": "투자",
  "type": "PWR",
  "dev": "Rolls-Royce",
  "region": "UK",
  "source": "World Nuclear News",
  "url": "https://www.world-nuclear-news.org/articles/swedish-state-to-take-majority-stake-in-videberg-kraft",
  "k": "swedish state taking majority stake in videberg kraft",
  "id": "ed7a9805"
 },
 {
  "date": "2026-06-24",
  "title": "카이로스 파워의 허메스(Hermes) 건설 현장 방문기",
  "summary": "ANS(American Nuclear Society) 기고자가 카이로스 파워(Kairos Power)의 허메스(Hermes) 테스트 원자로가 오크리지(Oak Ridge)에서 본격적인 건설 단계에 진입한 것을 확인했다.",
  "summaryLong": "미국 테네시주 오크리지(Oak Ridge)의 카이로스 파워 허메스 건설 현장에서 NQA-1 기준으로 시공된 파일, 지진 격리 장치, 중장비 등이 설치되고 있는 현장을 확인했다는 기고문이다. 이는 카이로스의 고온가스로(HTGR) 기반 시범 원자로가 설계 단계에서 벗어나 실제 건설이 진행 중임을 보여주는 사례로, SMR·첨단로 상용화의 진전을 나타낸다.",
  "cat": "기술",
  "type": "FHR",
  "dev": "Kairos Power",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-06-24/article-8043/from-theory-to-reality/",
  "k": "from theory to reality",
  "id": "279b7204"
 },
 {
  "date": "2026-06-23",
  "title": "테라스트리얼 에너지, 텍사스 A&M과 원자로 부지 협약 체결",
  "summary": "테라스트리얼 에너지(Terrestrial Energy)가 텍사스 A&M 대학 시스템과 용융염로 개발 부지 리스 및 연구협약을 체결했다.",
  "summaryLong": "테라스트리얼 에너지(Terrestrial Energy)가 텍사스 A&M 대학 시스템(TAMUS)과 지면리스 및 연구협약을 체결했다. 브라이언(Bryan), 텍사스 소재 텍사스 A&M–RELLIS 캠퍼스 내 약 77에이커(acres) 부지를 독점 사용할 권리를 확보했으며, 이 부지는 동사의 적분형 용융염로(Integral Molten Salt Reactor, IMSR) 개발에 투입될 예정이다. 협약은 부지 확보뿐 아니라 부지 특성 조사 완료를 위한 지원도 포함한다.",
  "cat": "기술",
  "type": "MSR",
  "dev": "Terrestrial Energy",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-06-23/article-8139/terrestrial-energy-and-texas-am-reach-agreement-on-reactor-siting/",
  "k": "terrestrial energy and texas a m reach agreement on reactor siting",
  "id": "c80a61d2"
 },
 {
  "date": "2026-06-22",
  "title": "오클로, 우라늄 공급 계약으로 핵분열 사업 강화",
  "summary": "오클로(Oklo)가 우라늄 공급 계약을 체결하며 핵분열 연료 확보에 나섰다.",
  "summaryLong": "오클로는 차세대 SMR 또는 첨단로 운영을 위한 핵연료 공급 계약을 확보함으로써 상용화 단계로의 진전을 도모하고 있다. 우라늄 공급 협약은 실제 원자로 운영 시 필수 요소로, 오클로의 사업화 준비도를 반영한다. 이는 개발 단계를 넘어 실제 운영 단계를 대비하는 계약으로, SMR 산업의 공급망 구축 진행 상황을 보여준다.",
  "cat": "계약",
  "type": "SFR",
  "dev": "Oklo",
  "region": "US",
  "source": "thedailyupside.com",
  "url": "https://www.thedailyupside.com/technology/artificial-intelligence/oklo-may-have-solved-its-uranium-sourcing-problem/",
  "k": "uranium deal powers up nuclear fission firm oklo",
  "id": "1164ecf0"
 },
 {
  "date": "2026-06-22",
  "title": "오클로(Oklo) 주가 최고점 대비 70% 하락…핵심 과제는 규제 승인",
  "summary": "소형모듈원자로·첨단로 개발사 오클로(Oklo)의 주가가 최고점에서 70% 하락했으며, 회사의 성공을 위해서는 규제 진전이 필수적이라는 분석이 제시되고 있다.",
  "summaryLong": "소형모듈원자로(SMR)·용융염로 개발사 오클로(Oklo)의 주가가 최고점 대비 70% 급락했다. 업계 분석에 따르면 오클로를 포함한 뉴스케일(NuScale), 엑스에너지(X-energy), 테라파워(TerraPower), 카이로스(Kairos Power), 롤스로이스 SMR(Rolls-Royce SMR) 등 첨단로 개발사들의 성공을 위해서는 규제 당국의 설계 승인 및 상용화 허가 등 규제 진전이 절대적 조건이다. 현재 낮은 주가에도 불구하고 규제 진전 여부가 이들 회사의 향후 전망을 결정할 핵심 변수로 작용하고 있다.",
  "cat": "인허가",
  "type": "SFR",
  "dev": "Oklo",
  "region": "US",
  "source": "tikr.com",
  "url": "https://www.tikr.com/blog/oklo-stock-has-fallen-70-from-its-peak-here-is-what-it-would-take-for-the-nuclear-bet-to-pay-off",
  "k": "oklo stock has fallen 70 from its peak here is what it would take for the nuclear bet to pay off",
  "op": 1,
  "id": "07b2ef53"
 },
 {
  "date": "2026-06-20",
  "title": "오클로, 센트러스 연료 계약 체결로 주가 상승",
  "summary": "오클로(Oklo)가 센트러스(Centrus)와 핵연료 공급 계약을 체결하면서 원전 공급망 우려 해소에 따른 주가 급등이 이루어졌다.",
  "summaryLong": "오클로(Oklo)와 센트러스(Centrus)의 핵연료 공급 계약 체결이 주목받으면서 오클로의 주가가 주간 상승률을 기록했다. 이 계약은 소형모듈원자로(SMR) 및 첨단로 상용화 과정에서 핵연료 공급의 안정성을 확보하는 데 중요한 의미를 갖는다. 센트러스는 미국의 주요 농축 연료 공급사로, 원전 산업의 공급망 리스크에 대한 시장 우려가 이 계약 체결로 완화된 것으로 해석된다.",
  "cat": "계약",
  "type": "SFR",
  "dev": "Oklo",
  "region": "US",
  "source": "ts2.tech",
  "url": "https://ts2.tech/en/oklo-rises-for-the-week-after-centrus-fuel-agreement-draws-attention-to-nuclear-supply-concerns/",
  "k": "oklo rises for the week after centrus fuel agreement draws attention to nuclear supply concerns",
  "id": "cfdd9ddc"
 },
 {
  "date": "2026-06-19",
  "title": "뉴스케일 파워, 패러곤(Paragon) SMR 계약 체결 후 주가 상승 후 거래 중단",
  "summary": "뉴스케일 파워(NuScale Power)가 패러곤(Paragon) 소형모듈원자로 거래 체결 발표 후 주가가 올랐지만 준틴스데이(Juneteenth) 휴장으로 거래가 중단되었다.",
  "summaryLong": "뉴스케일 파워(NuScale Power)가 소형모듈원자로(SMR) 관련 계약을 체결하면서 주가가 상승했으나, 미국의 준틴스데이(Juneteenth) 연방 휴일로 인해 시장 거래가 일시 중단되었다. 이 계약은 뉴스케일의 소형모듈원자로 사업 확대를 보여주는 신호로 평가되고 있다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "NuScale",
  "region": "US",
  "source": "ts2.tech",
  "url": "https://ts2.tech/en/nuscale-power-halts-after-gains-on-paragon-smr-deal-juneteenth-pause/",
  "k": "nuscale power halts after gains on paragon smr deal juneteenth pause",
  "id": "ba36d440"
 },
 {
  "date": "2026-06-18",
  "title": "테라파워, 나트륨(Natrium) 원자로 영국 설계인증(GDA) 신청",
  "summary": "테라파워(TerraPower)가 나트륨 고속로 기술에 대한 영국 설계인증을 공식 시작함.",
  "summaryLong": "테라파워(TerraPower)가 자사의 나트륨(Natrium) 고속냉각로에 대해 영국(UK) 설계인증(Generic Design Assessment, GDA) 프로세스를 개시했다. GDA는 영국 원자력규제청(ONR)이 실시하는 신형 원자로 설계에 대한 기술적 평가 단계로, 향후 건설 허가 취득의 전제 조건이 된다. 이는 테라파워의 SFR 기술이 영국 시장 진입을 위한 공식 규제 절차에 진입했음을 의미하며, 설계 검증(Design-led Justifying Design, 'Design-led JDD') 단계의 진전을 보여주는 중요한 마일스톤이다.",
  "cat": "인허가",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "UK",
  "source": "energynews.pro",
  "url": "https://energynews.pro/en/terrapower-launches-uk-generic-design-assessment-for-its-natrium-reactor",
  "k": "terrapower launches uk generic design assessment for its natrium reactor",
  "id": "73397c42"
 },
 {
  "date": "2026-06-18",
  "title": "테라파워, 영국 자회사 설립 및 나트륨(Natrium) 원자로 GDA 1단계 착수",
  "summary": "테라파워(TerraPower)가 영국(UK) 자회사를 설립하고 나트륨(Natrium) 소듐냉각고속로의 설계 인증(GDA) 1단계를 시작했다.",
  "summaryLong": "테라파워는 영국에서의 사업 확대를 위해 영국 자회사를 신설하고, 동시에 자사의 나트륨(Natrium) 소듐냉각고속로(SFR)에 대한 영국 설계 인증(GDA, Generic Design Assessment) 1단계 신청을 공식 착수했다. GDA는 영국 원자력규제청(ONR)에 의한 신형 원자로 설계의 안전성·보안성을 평가하는 프로세스로, 이는 테라파워의 나트륨 로 기술이 영국 시장에서 상용화되기 위한 중요한 인허가 단계이다. 이번 조치는 테라파워의 국제 시장 진출 전략과 기술 검증의 가속화를 의미한다.",
  "cat": "인허가",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "UK",
  "source": "niauk.org",
  "url": "https://www.niauk.org/terrapower-launches-uk-subsidiary-and-starts-gda-step-1-for-natrium-reactor/",
  "k": "terrapower launches uk subsidiary and starts gda step 1 for natrium reactor",
  "id": "de83fa73"
 },
 {
  "date": "2026-06-18",
  "title": "영국 첨단원자로 섹터 진전: 롤스로이스·NNLAB·일본원자력기구 고온가스로 협력 양해각서 체결",
  "summary": "롤스로이스(Rolls-Royce), 영국국립핵연구소(NNLAB), 일본원자력기구(JAEA)가 고온가스냉각로(HTGR) 기술 협력을 위한 양자 간 양해각서 2건을 6월 14일 체결했다.",
  "summaryLong": "영국의 첨단원자로 부문에서 주요 진전이 있었다. 롤스로이스(Rolls-Royce), 영국국립핵연구소(NNLAB), 일본원자력기구(JAEA)는 6월 14일 소형모듈원자로(SMR) 기술, 특히 고온가스냉각로(HTGR)에 대한 협력을 목표로 하는 양자 간 양해각서 2건을 체결했다. 이 협력은 영국의 첨단로 개발 프로그램과 일본의 원자력 정책 간의 국제 협력 확대를 의미하며, 고온가스로의 상용화 가속화에 기여할 것으로 예상된다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "Rolls-Royce",
  "region": "UK",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-06-18/article-8134/two-steps-forward-for-uk-advanced-nuclear/",
  "k": "two steps forward for u k advanced nuclear",
  "id": "98139f38"
 },
 {
  "date": "2026-06-18",
  "title": "엑스에너지(X-energy), 높은 현금 소소와 상장 후 밸류에이션 부담으로 주가 하락",
  "summary": "엑스에너지(X-energy)가 IPO 이후 높은 현금 소소율과 밸류에이션 평가를 둘러싼 투자자 우려로 주가 하락을 기록했다.",
  "summaryLong": "퀴버 퀀터티티브(Quiver Quantitative) 분석에 따르면 엑스에너지(X-energy)가 상장 후 주가 약세를 보이고 있다. 고온가스로(HTGR) 기술을 개발 중인 엑스에너지는 상당한 현금 소소로 인한 경영 효율성 논란과 상장 시 책정된 높은 밸류에이션에 대한 투자자들의 회의적 평가가 주가 하락의 배경이다. 이는 신흥 핵기술 기업들의 수익성과 사업화 일정에 대한 투자자 관심을 반영하고 있다.",
  "cat": "투자",
  "type": "HTGR",
  "dev": "X-energy",
  "region": "US",
  "source": "quiverquant.com",
  "url": "https://www.quiverquant.com/news/X-Energy+Slides+as+Investors+Continue+to+Digest+Heavy+Cash+Burn+and+Post-IPO+Valuation",
  "k": "x energy slides as investors continue to digest heavy cash burn and post ipo valuation",
  "id": "b6a13d20"
 },
 {
  "date": "2026-06-17",
  "title": "태웅, 테라파워(TerraPower) 나트륨(Natrium) SMR 주기기 부품 수주",
  "summary": "국내 원전 부품 전문기업 태웅이 빌 게이츠 설립 미국 테라파워사의 4세대 소형모듈원자로(SMR) 나트륨 프로젝트에 주기기 핵심부품을 공급하는 계약을 체결했다.",
  "summaryLong": "원전·해상풍력 소재 부품 전문기업 태웅이 미국 테라파워와 4세대 소형모듈원자로 나트륨(Natrium) 프로젝트 부품 공급 계약을 체결했다. 태웅은 창사 이래 처음으로 소형모듈원자로 주기기 분야에 진입하며, 국내 기업의 미국 본토 소형모듈원자로 공급망 참여도 사상 처음이다. 테라파워는 이미 2025년 3월 미국 원자력규제위원회(NRC)로부터 와이오밍주 케머러(Kemmerer) 프로젝트에 대한 건설허가를 획득하고 공사를 진행 중이다.",
  "cat": "계약",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "US",
  "source": "이투뉴스 - 전체기사",
  "url": "http://www.e2news.com/news/articleView.html?idxno=331411",
  "k": "태웅 테라파워 4세대 smr 주기기 핵심부품 첫 수주",
  "id": "807c56a1"
 },
 {
  "date": "2026-06-15",
  "title": "Natura Resources, 신생 핵연료 기업 QNI와 고농축저농축우라늄(HALEU) 공급계약 체결",
  "summary": "용융염로(MSR) 개발사 Natura Resources가 신생 핵연료 기업 Quadrant Nuclear Industries(QNI)와 고농축저농축우라늄(HALEU) 공급계약을 체결했다.",
  "summaryLong": "용융염로(MSR) 개발사 Natura Resources가 미국 뉴욕 소재의 신생 기업 Quadrant Nuclear Industries(QNI)와 고농축저농축우라늄(HALEU, High-Assay Low-Enriched Uranium) 공급을 위한 정식 계약을 체결했다. Natura의 상용 원자로 시스템이 필요로 하는 핵연료를 장기 안정적으로 확보하는 것을 목표로 한다. 이는 첨단 원자로와 신규 핵연료 공급망이 제휴를 통해 상용화 생태계를 구축하는 중요한 사례이다.",
  "cat": "계약",
  "type": "MSR",
  "dev": "Natura Resources",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-06-15/article-8120/natura-agrees-to-haleu-offtake-from-nuclear-startup-qni/",
  "k": "natura agrees to haleu offtake from nuclear start up qni",
  "id": "a8222dd8"
 },
 {
  "date": "2026-06-12",
  "title": "카이로스 파워(Kairos Power), 테네시주 오크릿지(Oak Ridge)에 원자로 시연 부지 착공",
  "summary": "카이로스 파워가 테네시주 오크릿지의 원자로 시연 부지에서 새로운 건설 접근법으로 착공했다.",
  "summaryLong": "카이로스 파워(Kairos Power)가 테네시주 오크릿지(Oak Ridge)에 위치한 원자로 시연 부지의 건설을 시작했다. 해당 부지는 약 85년 전 맨해튼 프로젝트(Manhattan Project) 당시 약 30,000명의 건설 노동자가 과수원과 농지를 원자력위원회(Atomic Energy Commission) 생산 시설로 변모시킨 역사적 위치이다. 이번 프로젝트는 소형모듈원자로(SMR) 기술의 실증 단계를 나타내며, 북미 지역의 첨단 원자로 개발 추진을 시사한다.",
  "cat": "기술",
  "type": "FHR",
  "dev": "Kairos Power",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-06-12/article-8048/breaking-ground-on-a-new-approach-to-construction/",
  "k": "breaking ground on a new approach to construction",
  "id": "f0696c46"
 },
 {
  "date": "2026-06-03",
  "title": "한국 i-SMRDA, 터키 Nuclean과 SMR 협력 협약 체결",
  "summary": "한국의 i-SMRDA(i-Small Modular Reactor Development Alliance)와 터키의 Nuclean이 소형모듈원자로(SMR) 개발·보급을 위한 협력 양해각서를 체결했다.",
  "summaryLong": "한국의 i-SMRDA와 터키의 Nuclean이 소형모듈원자로(SMR) 분야 협력을 위한 협약을 체결했다. 이는 한국의 SMR 기술과 터키의 시장 진출 의향이 결합된 전략적 파트너십으로, 양국이 SMR 개발과 국제 보급 네트워크 구축에 협력하기로 합의한 것이다. 이 협력은 아시아와 중동 지역의 에너지 안보 강화 및 탄소중립 달성에 기여할 것으로 예상된다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "i-SMRDA",
  "region": "KR",
  "source": "dailysabah.com",
  "url": "https://www.dailysabah.com/business/energy/south-koreas-i-smrda-turkiyes-nuclean-ink-co-op-deal-on-smrs",
  "k": "south korea s i smrda t rkiye s nuclean ink co op deal on smrs daily sabah",
  "id": "5ac4cb01"
 },
 {
  "date": "2025-07",
  "title": "ARC-100, 캐나다 캐나다핵안전위원회(CNSC) 벤더설계심사(VDR) Phase 2 완료",
  "summary": "아크클린에너지(ARC)의 ARC-100이 근본적 인허가 장벽이 없는 것으로 판정되었으며, 뉴브런즈윅전력(NB Power)은 부지준비허가 신청을 진행 중이고 2027년 건설허가 신청을 목표로 한다.",
  "cat": "인허가",
  "type": "SFR",
  "dev": "ARC",
  "region": "CA",
  "source": "WNN",
  "url": "https://www.world-nuclear-news.org/articles/arc-100-completes-canadian-regulatory-design-review",
  "summaryLong": "아크클린에너지(ARC)의 ARC-100 소형모듈원자로가 캐나다핵안전위원회(CNSC)의 벤더설계심사(VDR) 2단계를 완료하여 '근본적 인허가 장벽이 없다'는 판정을 받았다. 뉴브런즈윅전력(NB Power)은 이를 토대로 부지준비허가 신청 절차를 진행하고 있으며, 2027년 건설허가 신청을 목표로 하고 있다. 이는 캐나다에서 소형모듈원자로 인허가의 진전을 보여주는 중요한 사례이다. 실제 건설 단계로의 진입이 임박했다.",
  "id": "e5cb9369"
 },
 {
  "date": "2024",
  "title": "카이로스 파워(Kairos Power)–구글, 첨단로 전력공급 계약 체결",
  "summary": "카이로스의 KP-FHR(헤르메스(Hermes) 계열) 첨단로에서 생산한 전력을 구글에 공급하는 전력공급계약(PPA)을 체결했다.",
  "cat": "계약",
  "type": "FHR",
  "dev": "Kairos Power",
  "region": "US",
  "source": "Kairos Power",
  "url": "",
  "summaryLong": "첨단로 개발사 카이로스 파워와 기술 대기업 구글이 전력공급계약(PPA)을 체결했다. 카이로스의 KP-FHR(헤르메스 계열) 용융염냉각로(MSFR)에서 생산한 전력을 구글에 장기 공급하는 계약이다. 이는 빅테크 기업이 첨단로 전력을 직접 구매하는 계약 중 주요 사례로, 데이터센터 운영의 탈탄소화 추진을 보여준다. 구글의 재정 및 기술적 지원은 카이로스의 상용화 추진에 중요한 역할을 할 것으로 전망된다.",
  "id": "811c9dc5"
 },
 {
  "date": "2024-09",
  "title": "SMART100 표준설계인가 취득(한국)",
  "summary": "한국원자력연구원(KAERI)의 SMART100이 한국 표준설계인가를 취득했으며, 사우디 수출과 현대엔지니어링 협력을 추진 중이다.",
  "cat": "인허가",
  "type": "PWR",
  "dev": "SMART/KAERI",
  "region": "KR",
  "source": "KAERI",
  "url": "https://kaeri.re.kr/board/view?linkId=12112&menuId=MENU00326",
  "summaryLong": "한국원자력연구원(KAERI)이 개발한 소형모듈로(SMR) SMART100이 국내 표준설계인가를 취득했다. SMART100은 166 MWth급 통합형 원전으로, 한국 기술의 우수성을 국제적으로 입증하는 의미를 가진다. 이를 통해 사우디아라비아 수출 및 현대엔지니어링과의 협력이 구체화될 것으로 예상되며, 향후 한국의 SMR 해외 수출 전략 추진에 중추적 역할을 할 것으로 전망된다.",
  "id": "5661c65a",
  "ko": 1
 }
];
window.SMR_UPDATED = "2026-07-16 08:44 KST";
window.SMR_TOTAL = 1305;
