/* news-recent.js — AUTO-GENERATED subset of news-data.js (do not edit; see track-news.mjs writeRecent) */
window.SMR_NEWS = [
 {
  "date": "2026-07-30",
  "title": "KEPIC(전력산업기술기준), SMR·신기술 표준화 추진",
  "summary": "한국 전기산업연합회 KEPIC(전력산업기술기준) 본부장이 SMR 등 신기술에 대한 기술기준 확대와 플랫폼 고도화를 추진하겠다고 발표했다.",
  "summaryLong": "전영태 전기산업연합회 KEPIC(전력산업기술기준) 본부장이 2026년 KEPIC-Week(8월 25~28일, 강원도 정선) 사전 인터뷰에서 원전 중심의 기반을 유지하면서도 SMR, AI, ESS, 해상풍력 등 신기술 분야에 대한 성능 및 위험도 기반의 기술기준 확대가 필요하다고 밝혔다. 탄소중립 시대 전력산업의 변화에 대응하여 KEPIC 플랫폼 고도화와 실용적 내실화, 적기 기준 제·개정을 추진할 방침을 제시했다. 이는 국내 SMR 및 신기술 상용화를 위한 규제·표준 정책의 진전을 의미한다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "전기신문 - 전체기사",
  "url": "https://www.electimes.com/news/articleView.html?idxno=370800",
  "k": "원전안전성 지키며 smr 신기술 케픽화 노력",
  "ko": 1,
  "id": "d7baf510"
 },
 {
  "date": "2026-07-30",
  "title": "경남도, SMR 제조혁신 3개 핵심과제 모두 선정",
  "summary": "경상남도가 소형모듈원전(SMR) 제조혁신 프로젝트의 3개 핵심과제를 모두 확보했다.",
  "summaryLong": "경상남도가 소형모듈원전(SMR) 제조 분야 혁신 사업의 3개 핵심 과제를 모두 국책 프로젝트로 선정받았다. 이는 한국의 SMR 산업 육성 정책 아래 지역 기반 제조 혁신 계획이 정부 차원에서 공식 지원받게 됨을 의미한다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "newsgn.com",
  "url": "https://www.newsgn.com/news/articleView.html?idxno=565295",
  "k": "경남도 소형모듈원전 smr 제조혁신 3개 핵심과제 모두 선정",
  "ko": 1,
  "id": "689c05ef"
 },
 {
  "date": "2026-07-30",
  "title": "경남 원전기업·연구기관, SMR 제작기간 단축 기술 개발",
  "summary": "경남 지역 원전기업과 연구기관이 소형모듈원자로(SMR) 제작 기간을 단축하는 정부 과제에 주도적으로 참여하고 있다.",
  "summaryLong": "경남도가 소형모듈원자로(SMR) 제작 기간을 단축하는 3가지 기술 개발을 목표로 하는 정부 과제 공모를 진행하고 있으며, 지역의 원전기업과 연구기관이 이 과제의 핵심 추진 기관으로 참여하고 있다. SMR 제작 기간 단축은 소형모듈원자로의 경제성 향상과 시장 경쟁력 강화에 중요한 과제로 평가되고 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "연합뉴스 최신기사",
  "url": "https://www.yna.co.kr/view/AKR20260730134600052",
  "k": "경남 원전기업 연구기관 smr 제작기간 단축 기술 개발 주도",
  "ko": 1,
  "id": "2ecb9334"
 },
 {
  "date": "2026-07-30",
  "title": "미국 엑셀서비스, 베트남 법인 설립…SMR 기술 공유",
  "summary": "미국 원자력 기업 엑셀서비스(Excel Services)가 베트남에 법인을 설립하고 SMR 기술 경험을 단계적으로 공유한다.",
  "summaryLong": "미국의 원자력 기업 엑셀서비스(Excel Services)가 베트남에 법인을 설립하고 소형모듈원자로(SMR) 관련 기술 및 경험을 단계적으로 공유할 계획을 밝혔다. 이는 글로벌 SMR 시장 확대 추진 중 베트남 지역에서의 사업 진출 및 기술 협력 강화를 의미한다. 엑셀서비스의 베트남 진출은 동남아시아 지역 SMR 생태계 구축에 기여할 것으로 보인다.",
  "cat": "기술",
  "type": "General",
  "dev": "Excel Services",
  "region": "US",
  "source": "fnnews.com",
  "url": "https://www.fnnews.com/news/202607301037196296",
  "k": "미국 원자력 기업 엑셀서비스 베트남에 법인 설립 smr 경험 기술 단계적으로 공유",
  "ko": 1,
  "id": "9ceb015c"
 },
 {
  "date": "2026-07-30",
  "title": "빌 게이츠 방한, SK·현대중공업·두산과 SMR 공급망 구체화 예상",
  "summary": "테라파워(TerraPower) 회장 빌 게이츠가 1년 만에 방한하여 SK, 현대중공업, 두산 등과 SMR 공급망 협력을 구체화할 것으로 전망된다.",
  "summaryLong": "테라파워(TerraPower) 회장 빌 게이츠가 약 1년 만에 한국을 방문할 예정이며, SK이노베이션, 현대중공업, 두산 등 국내 주요 기업과의 소형모듈원자로(SMR) 공급망 협력을 구체화할 것으로 예상된다. 이는 테라파워의 고온가스로(HTGR) 기술과 한국 기업들의 제조·건설 능력을 연결하는 전략적 파트너십 확대를 의미한다. 이러한 협력은 글로벌 SMR 시장에서 한국의 지위 강화와 SMR 상용화 가속화에 중요한 역할을 할 것으로 평가된다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "US",
  "source": "biztribune.co.kr",
  "url": "https://www.biztribune.co.kr/news/articleView.html?idxno=356726",
  "k": "빌 게이츠 1년 만 방한 sk hd현대 두산과 smr 공급망 구체화할 듯",
  "ko": 1,
  "op": 1,
  "id": "f6a12026"
 },
 {
  "date": "2026-07-30",
  "title": "빌 게이츠 내달 방한, SK·HD현대와 SMR 협력 강화",
  "summary": "테라파워(TerraPower) CEO 빌 게이츠가 방한하여 SK·HD현대 등과 소형모듈원자로(SMR) 협력을 논의할 예정이다.",
  "summaryLong": "테라파워(TerraPower)의 CEO 빌 게이츠가 내달 한국을 방문하여 SK와 HD현대 등 주요 기업들과 소형모듈원자로(SMR) 분야의 협력을 강화하기로 예정되어 있다. 이는 한국의 핵심 산업 파트너들과의 협력을 통해 SMR 공급망 및 기술 개발을 가속화하려는 움직임으로 보인다. 게이츠의 방한은 글로벌 SMR 개발 및 상용화 전략의 일환으로 평가되고 있다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "KR",
  "source": "v.daum.net",
  "url": "https://v.daum.net/v/20260730111107608",
  "k": "빌 게이츠 내달 방한 sk hd현대 등과 smr 협력 강화",
  "ko": 1,
  "id": "afe75959"
 },
 {
  "date": "2026-07-30",
  "title": "홀텍, 2036년 오이스터 크릭 SMR-300 1.36GW 프로젝트 목표",
  "summary": "미국 원자력규제위원회(NRC)가 뉴저지주 오이스터 크릭 발전소의 폐지 허가 계획을 승인하여 홀텍이 SMR-300 4기 건설 추진이 가능해졌다.",
  "summaryLong": "미국 원자력규제위원회(NRC)가 뉴저지주 오이스터 크릭 발전소의 폐지 허가 계획(LTP)을 승인했다. 이는 폐지 절차의 최종 단계를 승인하는 규제 이정표로, 홀텍 인터내셔널이 레이시 타운십(Lacey Township)에서 SMR-300 소형모듈원자로 4기(총 1.36GW) 건설을 추진할 수 있는 길을 열었다. 홀텍은 2036년을 목표로 이 프로젝트를 진행할 계획이다.",
  "cat": "기술",
  "type": "PWR",
  "dev": "Holtec",
  "region": "US",
  "source": "POWER Magazine",
  "url": "https://www.powermag.com/holtec-targets-2036-for-1-36-gw-smr-300-project-at-oyster-creek/",
  "k": "holtec targets 2036 for 1 36 gw smr 300 project at oyster creek",
  "id": "43a1c044"
 },
 {
  "date": "2026-07-30",
  "title": "오이스터 크릭 폐지 허가 계획 NRC 승인, SMR-300 4기 프로젝트 추진",
  "summary": "홀텍이 오이스터 크릭 발전소 폐지 허가 계획 승인을 발표하며 SMR-300 4기 건설 프로젝트 추진을 공식화했다.",
  "summaryLong": "홀텍 인터내셔널이 미국 원자력규제위원회(NRC)의 오이스터 크릭 발전소 폐지 허가 계획(LTP) 승인을 공식 발표했다. 이 승인은 폐기 중인 발전소 부지를 SMR-300 소형모듈원자로 프로젝트로 전환할 수 있는 중요한 규제 승인이다. 홀텍은 이를 통해 뉴저지주에서 SMR-300 4기를 건설할 수 있게 되었다.",
  "cat": "기술",
  "type": "PWR",
  "dev": "Holtec",
  "region": "US",
  "source": "Holtec International",
  "url": "https://holtecinternational.com/hh-41-13/",
  "k": "oyster creek s license termination plan approved by the usnrc oyster creek project planned to feature four smr 300 units",
  "id": "fbe94605"
 },
 {
  "date": "2026-07-30",
  "title": "알로 애토믹스(Aalo Atomics)와 크루소(Crusoe), 2027년 INL 시연 목표 핵심 파트너십",
  "summary": "첨단원자로 개발사 알로 애토믹스와 AI 데이터센터 기업 크루소가 아이다호국립연구소(INL)에서 원자력 AI 팩토리 프로젝트를 위한 전략적 파트너십을 체결했다.",
  "summaryLong": "첨단 원자로 개발사 알로 애토믹스(Aalo Atomics)와 에너지 우선 AI 인프라 기업 크루소(Crusoe)는 7월 30일 아이다호국립연구소(Idaho National Laboratory, INL)에서 원자력 구동 'AI Factory' 데이터센터 프로젝트를 위한 전략적 파트너십을 공식 발표했다. 본 협력을 통해 알로의 INL 내 첨단 원자로 개발 프로그램과 크루소의 모듈식 AI 데이터센터 플랫폼을 결합하여 2027년 시연을 목표로 진행할 예정이다.",
  "cat": "기술",
  "type": "General",
  "dev": "알로 애토믹스",
  "region": "US",
  "source": "POWER Magazine",
  "url": "https://www.powermag.com/aalo-crusoe-plan-2027-inl-demonstration-pairing-nuclear-power-and-ai-data-center-load/",
  "k": "aalo crusoe plan 2027 inl demonstration pairing nuclear power and ai data center load",
  "id": "f0086d2a"
 },
 {
  "date": "2026-07-30",
  "title": "중국, 세계 최초 '순수 헬륨 터빈' 발전 성공으로 SMR 패권 속도",
  "summary": "중국이 세계 최초로 순수 헬륨 냉각 터빈 발전에 성공하며 소형모듈원자로(SMR) 분야 기술 주도권을 강화하고 있다.",
  "summaryLong": "중국이 소형모듈원자로(SMR) 기술 개발에서 세계 최초로 순수 헬륨을 냉각재로 사용하는 터빈 발전에 성공했다고 보도되었다. 고온가스로(HTGR) 등 첨단 원자로 계통에서 핵심인 헬륨 터빈 기술의 발전 성공으로 중국이 차세대 원자로 시장에서의 기술적 우위와 패권 확보를 가속화하고 있다.",
  "cat": "기술",
  "type": "HTGR",
  "dev": "",
  "region": "JP",
  "source": "esnews.kr",
  "url": "https://www.esnews.kr/news/articleView.html?idxno=5356",
  "k": "중국 세계 최초 순수 헬륨 터빈 발전 성공 smr 패권에 속도",
  "ko": 1,
  "id": "ec776665"
 },
 {
  "date": "2026-07-30",
  "title": "경남, SMR 혁신제조 정부사업 3개 과제 선정·2569억 원 투입",
  "summary": "경주 경상남도가 소형모듈원자로(SMR) 혁신제조 관련 정부 지원 사업에서 3개 과제를 선정받아 총 2569억 원을 투입하기로 결정했다.",
  "summaryLong": "경상남도가 소형모듈원자로(SMR) 혁신제조 분야 정부 지원 사업에서 3개 과제 전부를 석권하여 총 2569억 원의 사업비 투입이 확정되었다. 이는 정부 국책 프로그램으로서 차세대 원전 시장 선도를 위한 지역 및 산업 역량 강화 투자로, 한국의 SMR 기술 개발과 제조 기반 구축에 대한 정책적 지원을 반영한다.",
  "cat": "정책",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "thegnnews.com",
  "url": "https://thegnnews.com/View.aspx?No=4169202",
  "k": "경남 smr 혁신제조 정부사업 3개 과제 석권 2569억 원 투입해 차세대 원전시장 선도",
  "ko": 1,
  "id": "b8dc41ab"
 },
 {
  "date": "2026-07-30",
  "title": "빌 게이츠 방한 추진, SK·한수원·HD현대와 SMR 협력 논의 기대",
  "summary": "빌 게이츠(Bill Gates)가 내달 방한을 추진하며 SK, 한수원, HD현대 등과 소형모듈원자로(SMR) 협력을 논의할 것으로 예상된다.",
  "summaryLong": "테라파워(TerraPower) 창립자인 빌 게이츠가 내달 한국 방문을 추진 중이며, 이 자리에서 SK, 한국수력원자력(한수원), HD현대 등 국내 주요 기업들과 소형모듈원자로(SMR) 분야 협력을 논의할 가능성이 높다. 이는 테라파워의 첨단로(고속로) 기술과 국내 SMR 개발·제조 역량을 연결하는 국제 파트너십 논의로 해석된다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "KR",
  "source": "greened.kr",
  "url": "https://www.greened.kr/news/articleView.html?idxno=346428",
  "k": "빌 게이츠 내달 방한 추진 sk 한수원 hd현대 smr 협력 논의 기대",
  "ko": 1,
  "op": 1,
  "id": "1bdd318a"
 },
 {
  "date": "2026-07-30",
  "title": "빌 게이츠, 이르면 내달 방한…AI·SMR 협력 논의 전망",
  "summary": "빌 게이츠가 이르면 내달 한국을 방문하여 인공지능(AI)과 소형모듈원자로(SMR) 협력을 논의할 것으로 예상된다.",
  "summaryLong": "테라파워(TerraPower) 창립자인 빌 게이츠가 이르면 내달 한국 방문을 추진하고 있으며, 이 자리에서 인공지능(AI) 및 소형모듈원자로(SMR) 분야의 협력을 논의할 것으로 전망된다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "KR",
  "source": "KAIF 투데이뉴스",
  "url": "https://www.kaif.or.kr/ko/?c=250&s=&gp=1&gbn=view&ix=29999",
  "k": "빌 게이츠 이르면 내달 방한 ai smr 협력 논의 전망",
  "ko": 1,
  "op": 1,
  "id": "32de7250"
 },
 {
  "date": "2026-07-30",
  "title": "영국 원전 소재전쟁 가속…한국 i-SMR도 속도전",
  "summary": "영국의 원전 시장 경쟁이 심화되면서 한국의 i-SMR(차세대소형모듈원전)도 개발 속도를 높이고 있다.",
  "summaryLong": "영국에서 원전 기술 개발을 놓고 벌어지는 경쟁이 가속화되고 있으며, 한국의 i-SMR 프로젝트도 이에 응하는 형태로 개발 일정을 앞당기고 있다. 이는 글로벌 SMR·첨단로 시장에서 주요국들이 기술 확보와 인허가를 두고 벌이는 '속도전'의 일환으로 보인다. 영국과 한국을 포함한 여러 나라의 SMR 개발 동향이 상호 영향을 미치고 있음을 시사한다.",
  "cat": "기술",
  "type": "PWR",
  "dev": "한국원전",
  "region": "UK",
  "source": "esnews.kr",
  "url": "https://www.esnews.kr/news/articleView.html?idxno=5362",
  "k": "영국 원전 소재전쟁 가속 한국 i smr도 속도전",
  "ko": 1,
  "id": "766ff0de"
 },
 {
  "date": "2026-07-30",
  "title": "롤스로이스 SMR 네덜란드(Netherlands) 사업 확대, 두산에너빌리티 공급 기회 확대 전망",
  "summary": "롤스로이스 SMR(Rolls-Royce SMR)의 네덜란드 사업 확대에 따른 두산에너빌리티의 공급 기회 전망.",
  "summaryLong": "롤스로이스 SMR(Rolls-Royce SMR)이 네덜란드(Netherlands)에서 소형모듈원자로(SMR) 사업을 확대하고 있는 가운데, 국내 기업인 두산에너빌리티가 부품 공급 기회를 확대할 수 있을 것으로 보인다는 내용이다. SMR 개발사의 해외 사업 진전과 국내 기업의 참여 기회를 다루는 기사로, 첨단로 개발 사업과 관련된 공급망 동향을 반영한다.",
  "cat": "기술",
  "type": "PWR",
  "dev": "롤스로이스 SMR",
  "region": "UK",
  "source": "pinpointnews.co.kr",
  "url": "https://www.pinpointnews.co.kr/news/articleView.html?idxno=473066",
  "k": "롤스로이스 smr 네덜란드 사업 확대 두산에너빌 공급 기회 넓어지나",
  "ko": 1,
  "op": 1,
  "id": "a91ba03d"
 },
 {
  "date": "2026-07-29",
  "title": "SK이노베이션, 베트남 AI 전력시장 공략…LNG에서 SMR까지 협력",
  "summary": "SK이노베이션이 베트남과 LNG 공급부터 소형모듈원자로(SMR) 및 에너지저장장치(ESS)까지 단계별 에너지 협력을 제시했다.",
  "summaryLong": "SK이노베이션이 지난 16~17일 베트남을 방문하여 산업무역부 및 국영 에너지기업 PVN(Petrovietnam)과 에너지 협력을 협의했다. AI와 첨단 제조업 확산으로 전력 수요가 급증하는 베트남을 목표로 단기적으로는 미국·호주산 액화천natural가스(LNG) 공급망 구축, 장기적으로는 차세대 소형모듈원자로(SMR), 에너지저장장치(ESS), 재생에너지까지 협력 범위를 확대할 계획이다. 국내 주요 에너지 기업의 SMR 사업 다변화 및 국제 협력 추진 사례로 의미가 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "SK이노베이션",
  "region": "KR",
  "source": "에너지신문 - 전체기사",
  "url": "https://www.energy-news.co.kr/news/articleView.html?idxno=227120",
  "k": "sk이노베이션 베트남 ai 전력시장 공략 lng에서 smr까지 협력",
  "ko": 1,
  "id": "33a15887"
 },
 {
  "date": "2026-07-29",
  "title": "미국 SMR 테레스트리얼 에너지, 텍사스에 4세대 원자로 시범 플랜트 건설",
  "summary": "미국 SMR 업체 테레스트리얼 에너지가 텍사스에 4세대 원자로 시범 플랜트를 건설할 계획이다.",
  "summaryLong": "미국(US) SMR 개발사 테레스트리얼 에너지(Terrestrial Energy)가 텍사스(Texas) 지역에 4세대 원자로 기술을 적용한 시범 플랜트 건설을 추진 중이라는 소식이다. 제목과 스니펫만 제공되어 구체적인 일정·규모·기술 세부사항은 불명확하나, SMR 실증 프로젝트의 진전으로 관련성이 높다.",
  "cat": "기술",
  "type": "General",
  "dev": "Terrestrial Energy",
  "region": "US",
  "source": "kr.investing.com",
  "url": "https://kr.investing.com/news/stock-market-news/article-2033309",
  "k": "smr 테레스트리얼 에너지 텍사스에 4세대 원자로 시범 플랜트 짓는다 by the guru",
  "ko": 1,
  "id": "e5aa1273"
 },
 {
  "date": "2026-07-29",
  "title": "태웅, 테라파워(TerraPower) SMR 2호기 추가 수주 추진",
  "summary": "태웅이 미국의 테라파워(TerraPower) 소형모듈원자로(SMR) 1호기에 이어 2호기 추가 수주를 추진 중이다.",
  "summaryLong": "한국 기업 태웅이 미국 테라파워(TerraPower)의 소형모듈원자로(SMR) 사업에서 1호기 수주에 이어 2호기 추가 수주를 적극 추진하고 있다. 이는 태웅이 해외 선도 SMR 개발사와의 협력을 확대하려는 전략으로 보이며, 국내 SMR 시장 참여자의 글로벌 역할 강화를 의미한다.",
  "cat": "계약",
  "type": "SFR",
  "dev": "태웅",
  "region": "US",
  "source": "etoday.co.kr",
  "url": "https://www.etoday.co.kr/news/view/2608419",
  "k": "태웅 미 테라파워 smr 1호기 이어 2호기도 추가 수주 추진",
  "ko": 1,
  "op": 1,
  "id": "e26410c9"
 },
 {
  "date": "2026-07-29",
  "title": "태웅, SMR 대량생산 기술로 시장 주도 시동",
  "summary": "태웅이 소형모듈원자로(SMR) 대량생산 기술 확보로 소형원전 시장의 주요 플레이어로 본격 진입한다.",
  "summaryLong": "한국 기업 태웅이 소형모듈원자로(SMR)의 대량생산 기술 개발에 성공하며 글로벌 소형원전 시장에서 주도적 역할을 수행하려고 한다. 이는 기존의 일회성 수주 중심에서 벗어나 생산 효율성과 경제성을 갖춘 자체 기술 확보로 시장 경쟁력을 강화하는 전략이다.",
  "cat": "기술",
  "type": "General",
  "dev": "태웅",
  "region": "KR",
  "source": "market-ink.co.kr",
  "url": "https://www.market-ink.co.kr/news/articleView.html?idxno=9692",
  "k": "태웅 smr 대량생산 기술로 승부수 소형모듈원전 시장 메인 플레이어 시동",
  "ko": 1,
  "id": "84f90650"
 },
 {
  "date": "2026-07-29",
  "title": "한국 전기산업연합회, SMR 등 신기술용 기술기준 확대 추진",
  "summary": "대한전기산업연합회가 KEPIC(한국 전력산업 코드) 운영 관련 SMR 등 신기술에 대한 성능·위험도 기반의 기술기준 강화를 발표했다.",
  "summaryLong": "법정단체로 출범한 대한전기산업연합회가 2026 KEPIC-Week 개최를 앞두고, AI·SMR 등 신기술에 대해 성능·위험도 기반의 기술기준을 확대하고 국제표준화와의 정합성을 강화하겠다고 밝혔다. KEPIC(한국 전력산업 코드)은 전력설비의 설계·제작·시공·운전·유지·검사·해체 등에 필요한 기술적·제도적 요건을 규정한 민간 단체표준이며, 이번 기준 확대는 국내 SMR 산업의 규제 기반 정비 움직임으로 해석된다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "투데이에너지 - 전체기사",
  "url": "https://www.todayenergy.kr/news/articleView.html?idxno=300969",
  "k": "전기산업연합회 smr 등 신기술 성능 위험도 기반 기술기준 확대",
  "ko": 1,
  "id": "cbe37a9b"
 },
 {
  "date": "2026-07-29",
  "title": "KEPIC, AI·SMR 시대 맞춰 기준체계 확장",
  "summary": "원자력기술규정(KEPIC)이 SMR 시대에 대응하여 기준체계를 확장하고 있다.",
  "summaryLong": "한국원자력학회의 원자력기술규정(KEPIC)이 인공지능(AI)과 소형모듈원자로(SMR) 시대에 대응하기 위해 기준체계를 확장하고 있다. 이는 SMR 및 첨단로의 설계·안전 기준 강화와 관련된 정책·규제 차원의 움직임이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "inpnews.kr",
  "url": "https://www.inpnews.kr/news/articleView.html?idxno=7371",
  "k": "kepic ai smr 시대 맞춰 기준체계 확장",
  "ko": 1,
  "id": "b105640b"
 },
 {
  "date": "2026-07-29",
  "title": "맥더못, 네덜란드 롤스로이스 SMR 프로젝트 지원",
  "summary": "네덜란드 원자력 개발사 ULC-Energy가 미국 엔지니어링·건설사 McDermott과 협력 협약을 체결하여 네덜란드 내 롤스로이스(Rolls-Royce) SMR 프로젝트 개발을 지원한다.",
  "summaryLong": "네덜란드 원자력 개발 회사 ULC-Energy가 미국 기반 엔지니어링 및 건설 회사 McDermott과 협력 협약을 체결했다. 이 협약은 네덜란드에서 진행되는 롤스로이스(Rolls-Royce) SMR 프로젝트 개발을 지원하기 위한 것이다. McDermott은 설계, 엔지니어링, 구매 및 건설 관리 등 광범위한 서비스를 제공할 예정이다. 이는 유럽, 특히 네덜란드에서의 소형모듈원자로(SMR) 배치 확대를 위한 국제 협력의 사례이며, 롤스로이스의 SMR 상용화 진행의 중요한 진전이다.",
  "cat": "기술",
  "type": "PWR",
  "dev": "롤스로이스 SMR, ULC-Energy",
  "region": "EU",
  "source": "World Nuclear News",
  "url": "https://www.world-nuclear-news.org/articles/mcdermott-to-support-dutch-deployment-of-rolls-royce-smr",
  "k": "mcdermott to support potential dutch rolls royce smr projects",
  "id": "2d286fd6"
 },
 {
  "date": "2026-07-29",
  "title": "엑스에너지, 6천만 달러 규모 AI-원자력 프로메테우스 프로젝트 참여",
  "summary": "엑스에너지(X-energy)가 6천만 달러 규모의 AI-원자력 프로메테우스(Prometheus) 프로젝트에 참여한다.",
  "summaryLong": "고온가스로(HTGR) 개발사 엑스에너지(X-energy)가 6천만 달러(60M) 규모의 AI-원자력 프로메테우스(Prometheus) 프로젝트에 참여한다는 소식이다. 이 프로젝트는 인공지능(AI) 기술과 원자력을 결합하여 원자로 운영 최적화 및 안전성 강화를 추구하는 국책 또는 협력 프로그램으로 추정된다. 엑스에너지의 참여는 첨단로 기술과 AI의 융합 추세를 보여주며, 회사의 기술 개발 역량 강화를 의미한다.",
  "cat": "기술",
  "type": "HTGR",
  "dev": "엑스에너지",
  "region": "US",
  "source": "esgnews.com",
  "url": "https://esgnews.com/x-energy-joins-60m-ai-nuclear-prometheus-project/",
  "k": "x energy joins 60m ai nuclear prometheus project",
  "id": "0f643297"
 },
 {
  "date": "2026-07-29",
  "title": "오클로, 그로브스 시험로에 대한 미국 에너지부 시작 승인 획득",
  "summary": "오클로(Oklo)가 그로브스(Groves) 시험로에 대해 미국 에너지부(DOE) 스타트업 승인을 획득했다.",
  "summaryLong": "고속로 개발사 오클로(Oklo)가 자사의 그로브스(Groves) 시험로 프로젝트에 대해 미국 에너지부(DOE)로부터 스타트업(Start-up) 승인을 획득했다. 이는 원자로 운영을 위한 주요 규제 마일스톤으로, 설계 확정 이후 실제 운영 허가로 진행되는 과정의 중요한 단계이다. 이 승인은 오클로의 나트륨냉각고속로(SFR) 기술 상용화 추진이 규제 단계에서 실질적 진전을 이뤘음을 의미한다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "오클로",
  "region": "US",
  "source": "finance.yahoo.com",
  "url": "https://finance.yahoo.com/markets/stocks/articles/oklo-oklo-wins-doe-startup-120743224.html",
  "k": "oklo oklo wins doe startup approval for its groves test reactor",
  "id": "35660e6d"
 },
 {
  "date": "2026-07-29",
  "title": "빌 게이츠 방한…한국 기업과 SMR 공급망 논의",
  "summary": "테라파워 회장 빌 게이츠가 한국을 방문해 국내 기업들과 SMR 공급망 협력을 논의했다.",
  "summaryLong": "테라파워(TerraPower) 회장이자 빌앤멜린다게이츠재단(Bill & Melinda Gates Foundation) 의장인 빌 게이츠가 한국 방문 중 국내 원자력 기업들과 소형모듈원자로(SMR) 공급망 구축 및 협력 방안을 논의했다. 이는 테라파워의 고속로(SFR) 기술과 한국의 원전 부품·소재 역량을 결합하는 글로벌 공급망 전략의 일환으로 보이며, 한국이 SMR 생태계에서 핵심 공급업체로 포지셔닝되고 있음을 시사한다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "테라파워",
  "region": "US",
  "source": "hankyung.com",
  "url": "https://www.hankyung.com/article/2026072937601",
  "k": "단독 빌 게이츠 방한 기업과 smr 공급망 논의",
  "ko": 1,
  "id": "2c9c5ae8"
 },
 {
  "date": "2026-07-29",
  "title": "KEPIC, AI·SMR 시대 맞춰 기술기준 확대·산업계 지원 강화",
  "summary": "한국전력기술(KEPIC)이 AI·SMR 시대 대비 기술기준 확대 및 산업계 지원을 강화하기로 했다.",
  "summaryLong": "한국전력기술(Korea Electric Power Industry Code, KEPIC)이 인공지능(AI)과 소형모듈원자로(SMR) 시대 도래에 대비해 원자력 기술기준(Code) 확대 및 산업계 기술 지원을 강화하는 정책을 추진하고 있다. 이는 국내 원자력 규제·기준 체계를 SMR·첨단로 설계·건설·운영 요구사항에 맞춰 현대화하는 정책 차원의 조치로, SMR 상용화 환경 조성을 위한 정부·규제 기관의 의지를 나타낸다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "inpnews.kr",
  "url": "https://www.inpnews.kr/news/articleView.html?idxno=7371",
  "k": "kepic ai smr 시대 맞춰 기술기준 확대 산업계 지원 강화",
  "ko": 1,
  "id": "b105640b"
 },
 {
  "date": "2026-07-29",
  "title": "빌 게이츠 8월 방한… 한·미 SMR(소형모듈원자로) 동맹 강화",
  "summary": "빌 게이츠 테라파워(TerraPower) 회장이 8월 방한하여 한국과 미국의 SMR 협력을 강화할 예정이다.",
  "summaryLong": "빌 게이츠가 이끄는 미국의 첨단 원자로 개발사 테라파워(TerraPower) 회장이 8월 한국을 방문하여 한·미 SMR 동맹을 강화할 계획이다. 이는 한국이 원자력 발전을 부활시키는 정책 기조 속에서 이루어지는 것으로, 양국 간 SMR 기술 협력 및 파트너십 심화를 의미한다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "KR",
  "source": "segye.com",
  "url": "https://www.segye.com/newsView/20260729518839?OutUrl=google",
  "k": "빌 게이츠 8월 방한 한 미 smr동맹 강화",
  "ko": 1,
  "op": 1,
  "id": "e230041b"
 },
 {
  "date": "2026-07-29",
  "title": "맥더못(McDermott)과 ULC-에너지, 네덜란드 롤스로이스(Rolls-Royce) SMR 프로젝트 진전 위해 협력",
  "summary": "맥더못과 ULC-에너지가 네덜란드의 롤스로이스(Rolls-Royce) SMR 프로젝트 진전을 위한 협약을 체결했다.",
  "summaryLong": "맥더못(McDermott)과 ULC-에너지(ULC-Energy)가 네덜란드에서 롤스로이스 SMR(소형모듈원자로) 프로젝트 추진을 위한 협력 협약을 체결했다. 이는 롤스로이스의 소형모듈원자로 기술을 네덜란드에서 구현하기 위한 주요 파트너십으로, 프로젝트의 구체적인 일정과 규모 등의 세부사항은 보도에 나타나지 않았다. 이 협약은 유럽(EU) 지역에서의 SMR 배치 및 개발 확대 움직임을 나타낸다.",
  "cat": "기술",
  "type": "PWR",
  "dev": "Rolls-Royce",
  "region": "EU",
  "source": "oceannews.com",
  "url": "https://oceannews.com/news/energy/mcdermott-and-ulc-energy-partner-to-advance-rolls-royce-smr-projects-in-the-netherlands/",
  "k": "mcdermott and ulc energy partner to advance rolls royce smr projects in the netherlands",
  "id": "60d353a9"
 },
 {
  "date": "2026-07-29",
  "title": "SK이노베이션, 베트남에 LNG·SMR 연계 에너지 협력 방안 제시",
  "summary": "SK이노베이션이 베트남 에너지 부문과 LNG 및 소형모듈원자로 연계 협력 방안을 논의했다.",
  "summaryLong": "SK이노베이션 추형욱 대표이사가 16~17일 베트남을 방문하여 산업무역부(Ministry of Industry and Trade), 베트남 국영 에너지기업 PVN(Petrovietnam), 발전 자회사 PV Power와 협력 방안을 논의했다. 단기적으로는 미국(US), 호주(Australia)를 기반으로 한 액화천연가스(LNG) 공급망을 활용하여 전력 수급 안정성을 제고하고, 장기적으로는 차세대 소형모듈원자로(SMR) 분야로 협력을 확대하는 단계별 전략이다. 이는 베트남과의 에너지 및 첨단기술 협력 MOU 체결을 위한 협의로 평가된다.",
  "cat": "기술",
  "type": "General",
  "dev": "SK Innovation",
  "region": "KR",
  "source": "에너지데일리 - 전체기사",
  "url": "https://www.energydaily.co.kr/news/articleView.html?idxno=201844",
  "k": "sk이노베이션 베트남에 lng smr 연계 에너지 협력 방안 제시했다",
  "ko": 1,
  "id": "f43c66c5"
 },
 {
  "date": "2026-07-29",
  "title": "원전으로 청정 수소 생산…네덜란드 SMR 프로젝트 가속화",
  "summary": "네덜란드의 SMR 프로젝트가 원자력을 이용한 청정 수소 생산으로 가속화되고 있다.",
  "summaryLong": "네덜란드의 소형모듈원자로(SMR) 프로젝트가 원자력을 활용한 청정 수소 생산 분야로 확대되며 진전을 보이고 있다. 구체적인 프로젝트 명칭·일정·당사자는 제공된 스니펫에서 불명확하나, SMR 기술을 통한 그린 수소 생산의 실현이 추진 중임을 보여준다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "EU",
  "source": "esnews.kr",
  "url": "https://www.esnews.kr/news/articleView.html?idxno=5340",
  "k": "원전으로 청정 수소까지 만든다 네덜란드 smr 프로젝트 가속",
  "ko": 1,
  "id": "80747dca"
 },
 {
  "date": "2026-07-29",
  "title": "한국 총리, 빌 게이츠와 8월 만날 듯…SMR 분야 협력 논의 전망",
  "summary": "한국 총리가 빌 게이츠와 만나 SMR 분야 협력을 논의할 가능성이 제기되었다.",
  "summaryLong": "한국 총리가 빌 게이츠와 8월에 만날 것으로 전망되며, 이 자리에서 소형모듈원자로(SMR) 분야의 협력이 논의될 가능성이 있다. 제공된 스니펫이 제목만 있어 구체적 일정·배경·협력 범위는 명확하지 않으나, SMR 분야 국제 협력의 가능성을 시사한다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "newsis.com",
  "url": "https://www.newsis.com/view/NISX20260729_0003728870",
  "k": "한 총리 빌 게이츠와 8월 만날 듯 smr 분야 협력 논의 전망",
  "ko": 1,
  "op": 1,
  "id": "add2ddae"
 },
 {
  "date": "2026-07-29",
  "title": "빌 게이츠 방한, 한국 AI·SMR 협력 확대 신호탄 되나",
  "summary": "빌 게이츠의 방한이 한국과의 인공지능(AI), 소형모듈원자로(SMR) 협력 확대 신호로 전망된다.",
  "summaryLong": "마이크로소프트 창업자 빌 게이츠의 방한이 임박한 가운데 한국과 테라파워(TerraPower) 등 소형모듈원자로(SMR) 개발사 간의 협력 확대 신호로 관측되고 있다. 게이츠는 테라파워 회장으로서 첨단 핵기술 개발을 주도해온 인물이며, 이번 방한은 한국 정부의 원자력 정책 전환과 맞물려 한·미 SMR 협력 강화의 계기가 될 수 있다. 다만 구체적인 협력 내용, 계약, 투자 규모 등은 아직 공식화되지 않았다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "KR",
  "source": "g-enews.com",
  "url": "https://www.g-enews.com/article/ICT/2026/07/202607291957326672cd0bfacc1c_1",
  "k": "빌 게이츠 방한 초읽기 ai smr 협력 확대 신호탄 되나",
  "ko": 1,
  "op": 1,
  "id": "3f7411ca"
 },
 {
  "date": "2026-07-29",
  "title": "맥더못(McDermott)과 ULC-에너지(ULC-Energy), 네덜란드 롤스로이스 SMR 프로젝트 진전 협약",
  "summary": "맥더못이 ULC-에너지와 네덜란드에서의 롤스로이스(Rolls-Royce) SMR 사업 추진을 위한 협약을 체결",
  "summaryLong": "엔지니어링 기업 맥더못(McDermott)과 ULC-에너지(ULC-Energy)가 네덜란드에서 롤스로이스 SMR 프로젝트를 진전시키기 위한 협약을 체결했다. 이는 유럽에서 소형모듈원자로 도입을 위한 파트너십 강화를 의미하는 것으로, 롤스로이스의 소형모듈원자로 사업 추진의 구체적인 진전을 나타내는 사항이다.",
  "cat": "기술",
  "type": "PWR",
  "dev": "Rolls-Royce",
  "region": "EU",
  "source": "energynews.pro",
  "url": "https://energynews.pro/en/mcdermott-and-ulc-energy-sign-agreement-to-advance-rolls-royce-smr-projects-in-netherlands",
  "k": "mcdermott and ulc energy sign agreement to advance rolls royce smr projects in netherlands",
  "id": "1646d17f"
 },
 {
  "date": "2026-07-29",
  "title": "SK이노베이션, 베트남 AI 전력수요 대응…LNG부터 SMR까지 단계별 협력 제안",
  "summary": "SK이노베이션이 베트남의 인공지능(AI) 전력수요 대응을 위해 LNG에서 SMR까지 단계적 에너지 협력 방안을 제안했다.",
  "summaryLong": "SK이노베이션이 베트남의 인공지능(AI) 급증으로 인한 전력수요 증가에 대응하기 위해 액화천연가스(LNG)부터 소형모듈원자로(SMR)까지 단계적 에너지 협력 방안을 제시했습니다. 초기 LNG 공급으로 즉각적인 수요를 충족하고, 중·장기적으로 SMR 도입을 통한 저탄소 전력 공급 체계 구축을 제안하고 있습니다. 이는 베트남의 에너지 정책과 글로벌 탄소중립 목표에 부합하는 포괄적 협력 모델로, SK이노베이션의 SMR 사업 국제화 노력을 반영합니다.",
  "cat": "기술",
  "type": "General",
  "dev": "SK이노베이션",
  "region": "KR",
  "source": "eroun.net",
  "url": "https://www.eroun.net/news/articleView.html?idxno=86549",
  "k": "sk이노베이션 베트남 ai 전력수요 대응 제안 lng부터 smr까지 단계별 협력",
  "ko": 1,
  "op": 1,
  "id": "6a344298"
 },
 {
  "date": "2026-07-29",
  "title": "빌 게이츠, 내달 방한…SMR 동맹 강화",
  "summary": "빌 게이츠가 내달 한국을 방문하여 SMR 동맹 강화 협력을 추진한다.",
  "summaryLong": "테라파워(TerraPower) 회장인 빌 게이츠가 내달 서울을 방문하여 한국과의 소형모듈원자로(SMR) 협력 관계 강화를 도모할 예정이다. 한국의 원자력 정책 부활 배경 속에서 테라파워와 한국 간 전략적 파트너십 심화가 예상된다. 이는 글로벌 SMR 개발사와 한국의 정책적 연계를 나타내는 중요한 신호로 평가된다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "KR",
  "source": "news.nate.com",
  "url": "https://news.nate.com/view/20260729n34344",
  "k": "빌 게이츠 내달 방한 smr동맹 강화",
  "ko": 1,
  "op": 1,
  "id": "3bb2c8bd"
 },
 {
  "date": "2026-07-29",
  "title": "미국 ARC-100 SMR 실증 착수",
  "summary": "미국의 ARC-100 소형모듈원자로(SMR) 실증이 착수되었다.",
  "summaryLong": "미국에서 차세대 소형모듈원자로(SMR)인 ARC-100의 실증 프로젝트가 착수되었다. ARC-100은 고급 원자로 기술의 실용화를 위한 중요한 마일스톤으로, 이 프로젝트의 진행은 SMR 상용화 실현 가능성을 높이는 신호로 평가된다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "",
  "region": "US",
  "source": "esnews.kr",
  "url": "https://www.esnews.kr/news/articleView.html?idxno=5339",
  "k": "차세대 원전 smr 드디어 현실이 될까 미국 arc 100 실증 착수",
  "ko": 1,
  "id": "f97bf80a"
 },
 {
  "date": "2026-07-29",
  "title": "맥더모트, 네덜란드의 롤스로이스 SMR 프로젝트 지원",
  "summary": "맥더모트(McDermott)가 네덜란드의 롤스로이스 SMR 프로젝트 지원 계약을 체결했다.",
  "summaryLong": "엔지니어링·건설사 맥더모트(McDermott)가 네덜란드에서 진행될 롤스로이스(Rolls-Royce) SMR(소형모듈원자로) 프로젝트를 기술·관리적으로 지원하기로 합의했다. 이는 유럽에서의 소형모듈원자로 사업화를 위한 산업 파트너십 확대를 나타내며, 유럽 지역 첨단 원자력 기술의 상용화 경로를 강화하는 의미가 있다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "Rolls-Royce SMR",
  "region": "EU",
  "source": "world-nuclear-news.org",
  "url": "https://www.world-nuclear-news.org/articles/mcdermott-to-support-dutch-deployment-of-rolls-royce-smr",
  "k": "mcdermott to support potential dutch rolls royce smr projects world nuclear news org",
  "id": "2d286fd6"
 },
 {
  "date": "2026-07-29",
  "title": "SK이노베이션, LNG·SMR 연계로 베트남 전력시장 공략",
  "summary": "SK이노베이션이 베트남에 LNG와 소형모듈원자로(SMR)를 연계한 단계별 에너지 협력 방안을 제시하고, 장기적으로 SMR 분야 협력 확대를 추진한다.",
  "summaryLong": "SK이노베이션이 베트남 한-베 비즈니스 포럼에서 LNG와 소형모듈원자로(SMR)를 연계한 에너지 협력 전략을 발표했다. 단기적으로는 미국·호주 기반 LNG 공급망을 활용해 전력 수급 안정성을 높이고, 장기적으로는 차세대 SMR 분야로 협력을 확대한다는 구상이다. 베트남은 인공지능(AI)·첨단산업 성장으로 전력 수요가 빠르게 증가하고 있어 유망한 전력 공급시장으로 주목받고 있으며, SK이노베이션의 이번 제안은 동남아 에너지 시장 진출을 노린 전략적 움직임으로 평가된다.",
  "cat": "기술",
  "type": "General",
  "dev": "SK이노베이션",
  "region": "KR",
  "source": "투데이에너지 - 전체기사",
  "url": "https://www.todayenergy.kr/news/articleView.html?idxno=300988",
  "k": "sk이노베이션 lng smr 연계로 베트남 전력시장 공략 나서",
  "ko": 1,
  "id": "cf061196"
 },
 {
  "date": "2026-07-29",
  "title": "SK이노 CEO 추형욱, 베트남서 SMR 연계 에너지 협력 제안",
  "summary": "SK이노베이션의 추형욱 최고경영자가 베트남에서 소형모듈원자로(SMR) 연계 에너지 협력을 제안했다.",
  "summaryLong": "SK이노베이션의 추형욱 최고경영자가 베트남 방문 시 소형모듈원자로(SMR)와 연계된 에너지 협력 방안을 제안했다. 이는 SK이노베이션이 베트남 시장에서의 SMR 관련 사업 추진 및 전략적 파트너십 구축을 모색하고 있음을 보여준다. 한국 기업의 SMR 기술 및 사업 역량을 동남아 지역으로 확대하는 전략적 움직임으로 평가된다.",
  "cat": "기술",
  "type": "General",
  "dev": "SK이노베이션",
  "region": "KR",
  "source": "dt.co.kr",
  "url": "https://www.dt.co.kr/article/12075562",
  "k": "추형욱 sk이노 ceo 베트남서 smr 연계 에너지 협력 제안",
  "ko": 1,
  "id": "41a04d48"
 },
 {
  "date": "2026-07-29",
  "title": "빌 게이츠 방한, 한·미 SMR 동맹 강화",
  "summary": "빌 게이츠 회장이 한국을 방문하여 한·미 간 소형모듈원자로(SMR) 동맹 강화를 추진할 것으로 예상된다.",
  "summaryLong": "빌 게이츠 테라파워(TerraPower) 회장이 방한하여 한·미 간 소형모듈원자로(SMR) 협력을 강화할 것으로 보인다. 이는 한국과 미국 간 원자력 기술 동맹을 심화시키는 차원의 방문으로 평가된다. 방문 일정과 구체적 논의 내용은 향후 공개될 예정이다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "KR",
  "source": "bloomingbit.io",
  "url": "https://bloomingbit.io/feed/news/117264",
  "k": "단독 빌 게이츠 방한 smr 동맹 강화한다",
  "ko": 1,
  "op": 1,
  "id": "fc845227"
 },
 {
  "date": "2026-07-29",
  "title": "원자력 발전소 아날로그에서 디지털 제어로의 전환",
  "summary": "첨단원자로의 디지털 제어 시스템 도입에 대한 기술적 경험과 교훈을 다룬 기고문.",
  "summaryLong": "미국 해군(U.S. Navy)의 원자력 경험을 갖춘 전문가가 상용 첨단원자로로의 전환 과정에서 아날로그 제어에서 디지털 제어 시스템으로의 변화에 대해 기술합니다. 현대 첨단원자로의 완전 디지털 제어실 운영 경험을 통해 데이터 기반 의사결정의 중요성과 기술 전환의 과제를 논의하고 있으며, 소형모듈원자로(SMR)와 첨단로 개발에 필수적인 기술 이슈를 다룹니다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-07-29/article-8166/what-have-recent-projects-taught-us-about-the-move-from-analog-to-digital-plant-controls/",
  "k": "i nn i asks what have recent projects taught us about the move from analog to digital plant controls",
  "id": "dddc5368"
 },
 {
  "date": "2026-07-29",
  "title": "글로벌 원자력 법률 인재 양성, SMR 시대의 필수과제",
  "summary": "원전 수출과 소형모듈원자로(SMR) 시대에 대비한 국제 원자력 법률 전문가 양성의 필요성.",
  "summaryLong": "이 기사는 향후 원전 수출 확대와 소형모듈원자로(SMR) 시대의 도래에 따라 국제 규제, 안전 기준, 계약 등 원자력 관련 법률 업무를 담당할 글로벌 인재 양성의 중요성을 강조합니다. SMR과 첨단로 국제화에 필요한 법률·규제 인프라 구축 측면의 정책적 기초를 다루고 있습니다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "esnews.kr",
  "url": "https://www.esnews.kr/news/articleView.html?idxno=5331",
  "k": "원전 수출 smr 시대의 필수 글로벌 원자력 법률 인재 키운다",
  "ko": 1,
  "id": "f17beb72"
 },
 {
  "date": "2026-07-29",
  "title": "SK이노, 베트남에 LNG·SMR 연계 에너지 협력 제안",
  "summary": "SK이노베이션이 베트남에 LNG와 소형모듈원자로(SMR)를 연계한 에너지 협력을 제안했다.",
  "summaryLong": "SK이노베이션이 베트남 정부 및 기업에 대해 LNG(액화천연가스)와 소형모듈원자로(SMR)를 연계한 에너지 사업 협력 방안을 제시했다. 이는 한국 기업의 해외 SMR 사업 진출 전략을 보여주는 사례이며, 에너지 협력 양해각서(MOU) 체결로 발전할 가능성을 시사한다.",
  "cat": "기술",
  "type": "General",
  "dev": "SK이노베이션",
  "region": "KR",
  "source": "m-i.kr",
  "url": "https://www.m-i.kr/news/articleView.html?idxno=1396852",
  "k": "sk이노 베트남에 lng smr 연계 에너지 협력 제시",
  "ko": 1,
  "op": 1,
  "id": "7b652b5c"
 },
 {
  "date": "2026-07-28",
  "title": "[인터뷰] 대한전기산업연합회, SMR 등 적기 표준 마련 추진",
  "summary": "대한전기산업연합회가 SMR 등 신규 기술에 대한 산업 표준 마련을 추진한다고 밝혔다.",
  "summaryLong": "2026 KEPIC(Korea Electric Power Industry Code, 전력산업기술기준)-Week가 8월 25~28일 강원도(Gangwon-do) 정선(Jeongseon)에서 개최된다. 대한전기산업연합회가 이 행사를 통해 소형모듈원자로(SMR) 등 차세대 원전 기술에 대한 국내 산업 표준 마련에 최선을 다하겠다는 입장을 표명했다. KEPIC은 발전설비의 품질확보와 안전성을 위한 설계·제작·시공·운전·유지정비·시험·검사 등의 기술적·제도적 요건을 규정하는 민간단체표준이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "에너지데일리 - 전체기사",
  "url": "https://www.energydaily.co.kr/news/articleView.html?idxno=201801",
  "k": "인터뷰 대한전기산업연합회 smr 등 적기 표준 마련 최선 다하겠다",
  "ko": 1,
  "id": "8746488a"
 },
 {
  "date": "2026-07-28",
  "title": "두산에너빌, 축구장 6개 규모 SMR 전용공장 건설",
  "summary": "두산에너빌이 소형모듈원자로(SMR) 제조 전용 스마트팩토리를 건설 중이다.",
  "summaryLong": "두산에너빌(Doosan Enerbility)이 축구장 약 6개 규모의 소형모듈원자로(SMR) 전용 생산 공장을 첨단 스마트팩토리 형태로 건설하고 있다. 이 공장은 국내 SMR 산업의 성장을 뒷받침할 주요 제조 시설로, 최신 자동화·디지털화 기술이 적용될 예정이다.",
  "cat": "기술",
  "type": "General",
  "dev": "두산에너빌",
  "region": "KR",
  "source": "news.nate.com",
  "url": "https://news.nate.com/view/20260728n08817",
  "k": "르포 축구장 6개 크기 두산에너빌 smr 전용공장 첨단 스마트팩토리로 지어진다",
  "ko": 1,
  "id": "7387345a"
 },
 {
  "date": "2026-07-28",
  "title": "[산업지식퀴즈] 에너지 인프라 산업, AI 전력 확보 구원투수 SMR",
  "summary": "에너지 인프라 산업에서 AI 데이터센터의 전력 수요 증가에 대응하는 솔루션으로 SMR이 주목받고 있다.",
  "summaryLong": "인공지능(AI) 기술의 확산에 따른 데이터센터의 급증하는 전력 수요에 대응하기 위해 소형모듈원자로(SMR)가 핵심 솔루션으로 부각되고 있다. 기존 대형원전의 건설 기간과 비용 부담을 극복할 수 있는 SMR은 분산 배치가 가능하여 에너지 인프라 산업의 새로운 기회로 평가받고 있다. AI 시대의 에너지 수급 문제 해결을 위해 SMR이 '구원투수' 역할을 할 것으로 기대되며, 이는 SMR 산업의 성장 가능성을 보여주는 사례이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "",
  "source": "industryjournal.co.kr",
  "url": "https://industryjournal.co.kr/news/246848",
  "k": "산업지식퀴즈 에너지 인프라 산업 ai 전력 확보 구원투수 smr",
  "ko": 1,
  "id": "324b6153"
 },
 {
  "date": "2026-07-28",
  "title": "여야 의원들, 두산에너빌리티 찾아 원전·SMR 경쟁력 강화 방안 논의",
  "summary": "국회 의원들이 두산에너빌리티(Doosan Enerbility)를 방문하여 원전과 SMR의 경쟁력 강화 방안을 논의했다.",
  "summaryLong": "국회 여야 의원들이 한국의 주요 원전·SMR 개발사인 두산에너빌리티를 찾아 국내 원전 산업과 SMR 사업의 경쟁력을 높이기 위한 방안을 논의했다. 이는 정부와 여당, 야당이 원전·SMR 분야를 전략산업으로 인식하고 산업체와 협력을 강화하려는 의지를 보여주는 사례이다. 당사자 간의 정책 협력 논의를 통해 국내 원전 기업의 국제 경쟁력 강화 방향이 모색되고 있다.",
  "cat": "기술",
  "type": "General",
  "dev": "두산에너빌리티",
  "region": "KR",
  "source": "newskorea.ne.kr",
  "url": "https://www.newskorea.ne.kr/news/articleView.html?idxno=21081",
  "k": "여야 의원들 두산에너빌리티 찾아 원전 smr 경쟁력 강화 방안 논의",
  "ko": 1,
  "id": "1894d5a5"
 },
 {
  "date": "2026-07-28",
  "title": "두산에너빌리티, 원전·SMR 훈풍 타고 수주잔고 26조 돌파",
  "summary": "두산에너빌리티(Doosan Enerbility)가 원전·SMR 사업의 호황세를 바탕으로 수주잔고 26조 원을 달성했다.",
  "summaryLong": "한국의 주요 원전·SMR 개발사인 두산에너빌리티가 글로벌 원전 시장의 성장세와 SMR 사업 확대에 힘입어 수주잔고(미수행 계약액)가 26조 원을 넘어섰다. 이는 두산에너빌리티가 국내외 원전 및 SMR 프로젝트에서 다수의 계약을 수주했음을 의미하며, 기업의 실적 호황을 반영한다. 원전과 SMR 분야의 성장 기조 속에서 두산에너빌리티의 경영 성과가 우호적으로 진행되고 있음을 시사한다.",
  "cat": "계약",
  "type": "General",
  "dev": "두산에너빌리티",
  "region": "KR",
  "source": "bloter.net",
  "url": "https://www.bloter.net/news/articleView.html?idxno=669141",
  "k": "두산에너빌리티 원전 smr 훈풍 타고 수주잔고 26조 돌파",
  "ko": 1,
  "id": "382db3ea"
 },
 {
  "date": "2026-07-28",
  "title": "여수환경운동연합, 여수 SMR 실증단지 추진 철회 촉구",
  "summary": "여수환경운동연합이 여수 SMR 실증단지 추진의 철회를 촉구했다.",
  "summaryLong": "여수(Yeosu) 지역의 환경운동단체인 여수환경운동연합이 정부의 여수 SMR 실증단지 추진 사업에 대해 철회를 촉구했다. 이는 한국 정부가 추진 중인 소형모듈원자로(SMR) 실증 사업과 관련된 정책적 논쟁을 반영한다. 환경 시민단체의 반발은 한국의 SMR 정책 추진 과정에서 나타나는 규제 및 사회적 이슈를 보여준다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "news.nate.com",
  "url": "https://news.nate.com/view/20260728n19558",
  "k": "여수환경운동연합 여수 smr 실증단지 추진 철회 촉구",
  "ko": 1,
  "id": "2d61d5ee"
 },
 {
  "date": "2026-07-28",
  "title": "에너지 공기업, 도심·산단 소형원전(SMR) 도입 검토",
  "summary": "한국 에너지 공기업들이 도시 지역 및 산업단지에 소형모듈원자로(SMR) 도입을 검토 중이다.",
  "summaryLong": "한국의 에너지 공기업들이 도심 지역(都心) 및 산업단지(産業團地)에 소형모듈원자로(SMR)를 도입하는 방안을 검토 중인 것으로 보인다. 이는 분산형 전원 공급 및 산단 열 수요 충족 등을 목표로 한 정책적 추진으로 판단되며, 한국(KR) 정부 차원의 SMR 활용 방안 모색 움직임을 보여준다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "KAIF 투데이뉴스",
  "url": "https://www.kaif.or.kr/ko/?c=250&s=&gp=1&gbn=view&ix=29996",
  "k": "도심 산단에 소형원전 에너지 공기업 smr 도입 검토",
  "ko": 1,
  "op": 1,
  "id": "41de89ed"
 },
 {
  "date": "2026-07-28",
  "title": "배경훈 부총리, AI·6G·SMR 등 미래 산업 전방위 드라이브",
  "summary": "배경훈 과학기술정보통신부 장관이 AI, 6G, SMR 등 미래 산업 육성을 추진하고 있다.",
  "summaryLong": "배경훈 부총리 겸 과학기술정보통신부(Ministry of Science and ICT) 장관이 인공지능(AI), 6세대 이동통신(6G), 소형모듈원자로(SMR) 등 미래 전략 산업 육성을 전방위적으로 추진하고 있다. SMR은 탄소중립 에너지 전환과 에너지 안보 강화를 위한 핵심 기술로 정부 정책 추진 아젠다에 포함되어 있다. 부총리의 이러한 정책 드라이브는 한국의 미래 기술 경쟁력 강화와 관련 산업 육성 의지를 반영한 것이다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "news.nate.com",
  "url": "https://news.nate.com/view/20260728n16980",
  "k": "정치 배경훈 부총리 겸 과학기술정보통신부 장관 ai 6g smr까지 미래 산업 전방위 드라이브",
  "ko": 1,
  "id": "fba1bd68"
 },
 {
  "date": "2026-07-28",
  "title": "ARC(에이알씨)와 아이다호 국립연구소(INL), ARC-100 소형모듈원자로 배치를 위한 전략적 파트너십 공식화",
  "summary": "ARC 클린 테크놀로지와 미국 아이다호 국립연구소(INL)가 ARC-100 소형모듈원자로(SMR) 배치를 위한 전략적 파트너십을 공식화했다.",
  "summaryLong": "미국의 ARC 클린 테크놀로지와 아이다호 국립연구소(INL)가 ARC-100 소형모듈원자로 배치를 위한 전략적 파트너십을 공식화했다. 이는 ARC-100이 처음으로 실제 배치되는 사업으로, 양 기관의 협력을 통해 소형모듈원자로 기술의 실증을 추진하는 것이다. 이번 파트너십은 ARC의 소형모듈원자로 개발 기술을 실제 프로젝트에 적용하는 중요한 마일스톤이다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "ARC",
  "region": "US",
  "source": "pr.com",
  "url": "https://www.pr.com/press-release/974261",
  "k": "arc clean technology and idaho national laboratory formalize strategic partnership to deploy first of a kind arc 100 small modular reactor",
  "id": "0e30aa3e"
 },
 {
  "date": "2026-07-28",
  "title": "대한전기산업연합회, i-SMR·계속운전 관련 KEPIC 정책 방향 밝혀",
  "summary": "대한전기산업연합회가 i-SMR(한국 소형모듈원자로)과 계속운전 이슈에 대해 KEPIC(한국전기기술기준) 관점에서 정책 방향을 제시했다.",
  "summaryLong": "한국의 대한전기산업연합회가 2026 KEPIC(한국전기기술기준) 기자간담회에서 i-SMR(한국 소형모듈원자로) 및 계속운전(계속 운영) 관련 규제 입장을 밝혔다. 협회는 i-SMR과 기존 원전의 계속운전이 KEPIC 기준 적용 과정에서 걸림돌이 되지 않도록 하겠다는 입장을 표명했다. 이는 한국의 소형모듈원자로 및 기존 원전 운영 정책의 규제 기준 정립 과정에서 중요한 신호이다.",
  "cat": "기술",
  "type": "PWR",
  "dev": "",
  "region": "KR",
  "source": "skenews.kr",
  "url": "https://www.skenews.kr/news/articleView.html?idxno=52683",
  "k": "kepic2026 i smr 계속운전 발목 잡지 않겠다 대한전기산업연합회 kepic 기자간담회 q a",
  "ko": 1,
  "id": "c47555b1"
 },
 {
  "date": "2026-07-28",
  "title": "오클로, 고급 시험용 원자로 시운전 인허가 획득",
  "summary": "오클로가 그로브스 시험용 고급 원자로의 시운전 허가를 미국 에너지부(DOE)로부터 획득했다.",
  "summaryLong": "오클로가 자사의 그로브스 시험용 고급 원자로(Advanced Test Reactor)의 시운전을 시작할 수 있는 미국 에너지부(DOE) 인허가를 획득했다. 이는 오클로의 고급로 기술 개발 프로젝트가 중요한 규제 승인 단계를 통과한 것으로, 시험용 원자로 운영의 실질적 진전을 의미한다.",
  "cat": "기술",
  "type": "SFR",
  "dev": "Oklo",
  "region": "US",
  "source": "tomorrowsworldtoday.com",
  "url": "https://www.tomorrowsworldtoday.com/nuclear/oklo-is-now-authorized-to-start-up-its-advanced-test-reactor/",
  "k": "oklo is now authorized to start up its advanced test reactor",
  "id": "21bde856"
 },
 {
  "date": "2026-07-28",
  "title": "래디언트와 NASA, 미국 고농축우라늄(HALEU) 할당 확보",
  "summary": "래디언트 인더스트리(Radiant Industries)가 NASA의 화성 핵추진 미션 및 미국 공군 마이크로리액터 배치를 위해 고농축우라늄(HALEU) 할당을 받았다.",
  "summaryLong": "래디언트 인더스트리(Radiant Industries)와 NASA가 고농축우라늄 가용성 프로그램(HALEU Availability Program)의 3차 할당에서 우라늄을 획득했다. 할당분은 NASA의 화성 핵추진 우주 탐사 미션과 래디언트의 미국 공군(USAF)용 마이크로리액터 배치 사업에 활용될 예정이다. HALEU는 차세대 고급 노형(특히 마이크로리액터, 고온가스로 등)의 핵심 연료로, 이 할당은 미국 정부의 첨단원전 지원 정책 실현 사례이다.",
  "cat": "기술",
  "type": "Micro",
  "dev": "Radiant",
  "region": "US",
  "source": "World Nuclear News",
  "url": "https://www.world-nuclear-news.org/articles/radiant-and-nasa-awarded-us-haleu-allocations",
  "k": "radiant and nasa awarded us haleu allocations",
  "id": "e5d575d4"
 },
 {
  "date": "2026-07-28",
  "title": "SMR 발전플랫폼 조류하중 계수 도출 연구용역 입찰",
  "summary": "선박해양플랜트연구소(KRISO)가 SMR 발전플랫폼 설계를 위한 조류하중 계수 도출 학술연구용역을 발주한다.",
  "summaryLong": "선박해양플랜트연구소(Korea Research Institute of Ships and Ocean Engineering, KRISO)가 SMR 발전플랫폼 설계용 조류하중 계수 도출을 위한 학술연구용역을 발주했다. 마감일은 2026년 8월 10일이다. 이는 한국의 해상 부유식 SMR(부유형 소형모듈원자로) 기술 개발을 지원하는 국책 사업으로, SMR 플랫폼 기초 설계 연구의 일환이다.",
  "cat": "기술",
  "type": "General",
  "dev": "KRISO",
  "region": "KR",
  "source": "투데이에너지 - 전체기사",
  "url": "https://www.todayenergy.kr/news/articleView.html?idxno=300928",
  "k": "입찰 정보 7월 28일자",
  "ko": 1,
  "id": "52ed497c"
 },
 {
  "date": "2026-07-28",
  "title": "정부, SMR 특별법 시행령 제정령안 입법예고",
  "summary": "과학기술정보통신부가 지난 3월 공포된 소형모듈원자로(SMR) 개발 촉진 특별법의 시행령 제정령안을 입법예고했다. 시행령안은 SMR의 모듈 형태·제작·운송·설치 방식 등 핵심 특성을 구체화하고 부대시설을 시스템 구성요소로 규정했다.",
  "summaryLong": "과학기술정보통신부가 지난 3월 10일 공포된 소형모듈원자로(SMR) 개발 촉진 및 지원에 관한 특별법의 시행령 제정령안을 입법예고했으며, 해당 법은 9월 11일부터 시행될 예정이다. 지난 24일 입법예고된 제정령안의 주요 내용은 SMR의 설비용량 기준뿐 아니라 모듈 형태, 제작·운송·설치 방식, 용량 확장 구조 등 핵심 특성을 구체화한 것이다. 제정령안은 모듈 형태의 요건을 SMR 정의에 포함시키고, 소형모듈원자로와 결합 또는 연계되는 부대시설·장치를 시스템 구성요소로 규정했다. 이는 SMR 개발 및 규제 체계를 명확히 함으로써 관련 산업의 법적 기반을 마련하는 의미를 갖는다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "KR",
  "source": "투데이에너지 - 전체기사",
  "url": "https://www.todayenergy.kr/news/articleView.html?idxno=300929",
  "k": "정부 smr 특별법 시행령 제정령안 입법예고",
  "ko": 1,
  "id": "53ed4b0f"
 },
 {
  "date": "2026-07-28",
  "title": "롱비치항, MARAD와 해양 원자로 파트너십 체결",
  "summary": "미국 교통부 해사청(MARAD)이 캘리포니아 롱비치항과 협력각서(MOC)를 체결하여 상선·항만·해양자산 전력공급용 소형모듈원자로(SMR) 개발을 추진한다.",
  "summaryLong": "미국 교통부 산하 해사청(MARAD)이 캘리포니아 남부의 롱비치항(Port of Long Beach)과 협력각서(Memorandum of Cooperation, MOC)를 체결했다. 이는 상용선박, 항만, 기타 해양자산의 전력공급을 위한 소형모듈원자로(SMR) 개발을 추진하기 위한 최초의 협력 사례로, 롱비치항이 이 분야에서 MARAD와 파트너십을 맺은 미국 첫 항만이 되었다. 이 협력은 해양 부문에서의 SMR 활용 가능성을 실증하고 규제·기술 프레임워크를 개발하는 데 중점을 둘 것으로 예상된다.",
  "cat": "계약",
  "type": "General",
  "dev": "",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-07-28/article-8250/long-beach-is-first-port-to-partner-with-marad-on-maritime-reactors/",
  "k": "long beach is first port to partner with marad on maritime reactors",
  "id": "af32acef"
 },
 {
  "date": "2026-07-28",
  "title": "캐나다 첫 SMR용 대형 강철 반응기 용기 제작 중",
  "summary": "온타리오주의 공장에서 캐나다 첫 소형모듈원자로를 위한 길이 98피트, 무게 606톤의 대형 강철 반응기 용기 제작이 진행 중이다.",
  "summaryLong": "캐나다 온타리오주의 공장에서 캐나다 첫 소형모듈원자로(SMR)를 위한 대형 강철 반응기 용기 제작이 진행 중이다. 이 강철 용기는 길이 98피트, 무게 606톤 규모로, 현재 북미 대륙에서 이러한 규모의 용기 제작을 시작한 유일한 업체가 이 작업을 수행하고 있다. 이는 캐나다의 SMR 상용화 프로젝트가 설계 단계에서 실제 하드웨어 제작 단계로 진전되었음을 의미한다.",
  "cat": "기술",
  "type": "General",
  "dev": "",
  "region": "CA",
  "source": "autonocion.com",
  "url": "https://www.autonocion.com/us/canada-first-small-modular-reactor/",
  "k": "a 606 ton steel can 98 feet long is taking shape in an ontario factory the piece that turns canada s first small modular reactor from a hole in the ground into a machine and exactly one shop on the continent has started one",
  "id": "0a5bac57"
 },
 {
  "date": "2026-07-28",
  "title": "오리온이엔씨-서울대, 초소형원자로 사업성 검증 완료",
  "summary": "오리온이엔씨와 서울대학교가 협력하여 트럭으로 운반 가능한 초소형원자로의 사업성을 확인했다.",
  "summaryLong": "오리온이엔씨와 서울대학교가 협력하여 트럭으로 운반 가능한 마이크로 규모의 초소형원자로에 대한 사업성 검증을 완료했다. '트럭에 실려오는 발전소'라는 표현으로 표현된 초소형원자로는 극도로 모듈화된 소형모듈원자로(SMR) 기술을 대표한다. 이 검증은 해당 기술의 상용화 가능성과 시장 수요성을 평가하는 중요한 마일스톤으로 볼 수 있다.",
  "cat": "기술",
  "type": "Micro",
  "dev": "오리온이엔씨",
  "region": "KR",
  "source": "esnews.kr",
  "url": "https://www.esnews.kr/news/articleView.html?idxno=5303",
  "k": "트럭에 실려오는 발전소 오리온이엔씨 서울대 초소형원자로 사업성 확인",
  "ko": 1,
  "id": "777efcfb"
 },
 {
  "date": "2026-07-28",
  "title": "안타레스(Antares), 미국 군사기지 SMR 상용화 추진",
  "summary": "안타레스(Antares)가 초소형 원자로를 미국 군사기지에 배치하여 AI 데이터센터의 전력난 해결을 목표로 상용화를 추진 중이다.",
  "summaryLong": "SMR 개발사 안타레스(Antares)가 미국(US) 군사기지에 초소형 원자로를 설치하는 프로젝트를 추진하고 있다. 이는 인공지능(AI) 데이터센터의 전력 공급 부족 문제를 극복하기 위한 실제 상용화 사례이다. 안타레스는 이를 통해 미래 에너지 시장에서 마이크로 원자로의 실질적 적용 가능성을 입증하려 하고 있다.",
  "cat": "기술",
  "type": "Micro",
  "dev": "Antares",
  "region": "US",
  "source": "aipostkorea.com",
  "url": "https://www.aipostkorea.com/news/articleView.html?idxno=12213",
  "k": "군사기지에 smr 꽂는다 안타레스 ai 전력난 극복할 초소형 원자로 상용화 박차",
  "ko": 1,
  "op": 1,
  "id": "b18544e2"
 },
 {
  "date": "2026-07-28",
  "title": "미국 SMR 개발사 테레스트리얼 에너지, 텍사스에 4세대 원자로 시범 플랜트 건설",
  "summary": "미국의 SMR 개발사 테레스트리얼 에너지(Terrestrial Energy)가 텍사스에서 4세대 원자로 시범 플랜트 건설을 추진하고 있다.",
  "summaryLong": "미국의 소형모듈원자로(SMR) 개발사인 테레스트리얼 에너지(Terrestrial Energy)가 텍사스에 차세대(4세대) 원자로 시범 플랜트(파일럿 플랜트) 건설을 계획하고 있다. 테레스트리얼 에너지는 용융염냉각 고온 원자로(molten salt reactor) 기술을 개발 중인 회사로, 이 시범 플랜트는 첨단 노형의 기술 검증 및 규제 인허가 기반 마련을 위한 중요 마일스톤이 될 것으로 예상된다.",
  "cat": "기술",
  "type": "MSR",
  "dev": "Terrestrial Energy",
  "region": "US",
  "source": "theguru.co.kr",
  "url": "https://theguru.co.kr/news/article.html?no=105044",
  "k": "smr 테레스트리얼 에너지 텍사스에 4세대 원자로 시범 플랜트 짓는다",
  "ko": 1,
  "id": "81682a84"
 },
 {
  "date": "2026-07-24",
  "title": "GE 버노바 히타치·벨란, BWRX-300 밸브 공급 계약 체결",
  "summary": "GE 버노바 히타치와 벨란(Velan)이 유럽 지역 BWRX-300 소형모듈원자로용 밸브 공급 계약을 체결했다.",
  "summaryLong": "GE 버노바 히타치와 밸란(Velan)은 유럽(EU) 지역 BWRX-300 소형모듈원자로(SMR) 프로젝트용 밸브 공급 계약을 체결했다. 이는 BWRX-300의 유럽 전개를 위한 공급망 구축의 핵심 부품 협력 사례이다.",
  "cat": "계약",
  "type": "BWR",
  "dev": "GE Vernova Hitachi",
  "region": "EU",
  "source": "energiesmedia.com",
  "url": "https://energiesmedia.com/ge-vernova-velan-valve-agreement-energy/",
  "k": "ge vernova hitachi and velan sign valve supply agreement for bwrx 300 small modular reactors in europe",
  "id": "b9932a2f"
 },
 {
  "date": "2026-07-24",
  "title": "미국, '프로메테우스(Prometheus)' AI 핵 이니셔티브 출범, 엑스에너지·오클로 등 참여",
  "summary": "미국이 AI와 핵에너지를 결합한 '프로메테우스' 정부 이니셔티브를 출범시켰으며, 엑스에너지와 오클로 등 SMR 개발사들이 참여한다.",
  "summaryLong": "미국 정부가 인공지능(AI)과 핵에너지 기술을 통합하는 '프로메테우스(Prometheus)' 국책 프로그램을 공식 출범했다. 이 이니셔티브에는 엑스에너지(X-energy), 오클로(Oklo) 등 소형모듈원자로 개발 기업들이 파트너로 참여한다. 정부의 전략적 핵에너지 정책 프로그램으로, 첨단로 산업 생태계 조성과 경쟁력 강화를 목표로 한다.",
  "cat": "기술",
  "type": "HTGR",
  "dev": "Oklo, X-Energy",
  "region": "US",
  "source": "nai500.com",
  "url": "https://nai500.com/blog/2026/07/u-s-launches-prometheus-ai-nuclear-initiative-with-x-energy-oklo-among-partners/",
  "k": "u s launches prometheus ai nuclear initiative with x energy oklo among partners",
  "id": "52ae4301"
 },
 {
  "date": "2026-07-24",
  "title": "BWXT, 카이로스 파워, 와이오밍주 원자력산업 미래에 기대",
  "summary": "BWXT와 카이로스 파워(Kairos Power)가 와이오밍주의 원자력산업 발전에 대한 기대감을 표했다.",
  "summaryLong": "BWXT와 첨단 소형모듈원자로(SMR) 개발사 카이로스 파워(Kairos Power)가 와이오밍주에서의 원자력산업 미래에 대한 기대감을 표현했다. 두 기업 모두 지역 내 원자력 프로젝트 발전 가능성에 긍정적인 입장을 보이고 있다.",
  "cat": "기술",
  "type": "FHR",
  "dev": "BWXT, Kairos",
  "region": "US",
  "source": "gillettenewsrecord.com",
  "url": "https://www.gillettenewsrecord.com/news/local/article_e480b468-1c5d-447e-8ea3-98b484593fc9.html",
  "k": "bwxt kairos power excited about future of nuclear industry in wyoming",
  "id": "58c9c3e0"
 },
 {
  "date": "2026-07-23",
  "title": "카이로스 파워, 7월 28일 오크릿지 원자로 논의 예정",
  "summary": "카이로스 파워(Kairos Power)의 지도부가 오크릿지(Oak Ridge) 원자로 사업에 대해 논의할 예정이다.",
  "summaryLong": "카이로스 파워(Kairos Power)의 경영진이 7월 28일 오크릿지(Oak Ridge)에서 해당 지역의 원자로 사업을 논의하기로 했다. 구체적인 안건이나 상세 내용은 스니펫에 제시되지 않았으나, 카이로스의 용융염냉각 고온가스로(FHR) 기술 개발 및 지역 배치 계획과 관련된 논의로 추정된다.",
  "cat": "기술",
  "type": "FHR",
  "dev": "Kairos",
  "region": "US",
  "source": "oakridger.com",
  "url": "https://www.oakridger.com/story/news/local/2026/07/23/kairos-power-leader-to-discuss-oak-ridge-reactor/91025147007/",
  "k": "kairos power leader to discuss oak ridge reactor july 28",
  "op": 1,
  "id": "77082721"
 },
 {
  "date": "2026-07-22",
  "title": "나투라 리소스(Natura Resources) 용융염로, 미국 안전설계 인증 획득",
  "summary": "나투라 리소스(Natura Resources)의 액체 연료 고급 원자로가 미국 에너지부(DOE) 안전설계 인증을 획득하여 텍사스주 애빌린 크리스천 대학교(Abilene Christian University)에서 첫 배치 단계로 나아갔다.",
  "summaryLong": "미국 에너지부(DOE)가 나투라 리소스(Natura Resources)의 시연로에 대한 안전설계 인증(Nuclear Safety Design Agreement)을 승인했다고 발표했다. 이는 액체 연료 기반의 고급 원자로 기술이 규제당국 승인을 받은 주요 마일스톤이며, 텍사스(Texas)주 애빌린 크리스천 대학교(Abilene Christian University)에서의 첫 배치로 나아가는 길을 열었다.",
  "cat": "기술",
  "type": "MSR",
  "dev": "Natura Resources",
  "region": "US",
  "source": "World Nuclear News",
  "url": "https://www.world-nuclear-news.org/articles/molten-salt-reactor-gets-us-safety-design-approval",
  "k": "molten salt reactor gets us safety design approval",
  "id": "2763d189"
 },
 {
  "date": "2026-07-21",
  "title": "롤스로이스(Rolls-Royce) SMR, 체코 추가 2곳 건설 준비 착수",
  "summary": "체코 산업무역부(Ministry of Industry and Trade), ČEZ, 롤스로이스 SMR이 양해각서(MOU)를 체결하고 체코 내 2개 추가 지역에서 소형모듈원자로(SMR) 사업 준비활동을 시작한다.",
  "summaryLong": "체코 산업무역부, ČEZ, 롤스로이스 SMR이 양해각서(MOU)를 체결하여 체코 내 두 개의 추가 부지에서 소형모듈원자로(SMR) 프로젝트 준비활동을 시작하기로 합의했다. 이는 체코의 에너지 전환 전략의 일환으로, 기존 부지에 이어 새로운 입지를 확보함으로써 SMR 도입을 본격화하려는 움직임이다. 롤스로이스 SMR은 유럽 시장 진출의 중요한 계약 사례로, 향후 설계 인증 및 건설 인허가 획득으로 이어질 것으로 예상된다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "Rolls-Royce SMR",
  "region": "EU",
  "source": "World Nuclear News",
  "url": "https://www.world-nuclear-news.org/articles/two-more-czech-sites-lined-up-for-rolls-royce-smrs",
  "k": "two more czech sites lined up for rolls royce smrs",
  "id": "09680659"
 },
 {
  "date": "2026-07-21",
  "title": "프랑스 산업단지에 다중 용융염로 제안",
  "summary": "프랑스 용융염로 개발사 스텔라리아(Stellaria)가 유니텔 그룹(Unitel Group)·에너지 허브(Energie Hub)와 남부 포스쉬르메르(Fos-sur-Mer) 지역에 통합 에너지 허브 개발을 위한 양해각서를 체결했다.",
  "summaryLong": "프랑스 용융염로(MSR) 개발사인 스텔라리아(Stellaria)가 에너지 기업 유니텔 그룹(Unitel Group)과 에너지 허브(Energie Hub)와 양해각서를 체결하고 남부 프랑스 포스쉬르메르(Fos-sur-Mer) 지역에 다중 용융염로를 기반으로 한 통합 에너지 허브 개발을 추진하기로 합의했다. 이는 산업단지의 열·전력 공급을 위한 소형모듈원자로 활용 프로젝트로, 스텔라리아의 핵심 상용화 전략의 일환이다.",
  "cat": "계약",
  "type": "MSR",
  "dev": "Stellaria",
  "region": "EU",
  "source": "World Nuclear News",
  "url": "https://www.world-nuclear-news.org/articles/multiple-msrs-proposed-for-french-industrial-park",
  "k": "multiple msrs proposed for french industrial park",
  "id": "ffa3f8d0"
 },
 {
  "date": "2026-07-21",
  "title": "미국 원자력규제위원회(NRC), 테라파워(TerraPower) 건설허가 승인",
  "summary": "미국 원자력규제위원회(NRC)가 테라파워의 건설허가를 승인했다.",
  "summaryLong": "미국 원자력규제위원회(NRC)가 테라파워(TerraPower)의 건설허가를 승인했다. 이는 첨단 소형모듈원자로(SMR) 개발사의 중요한 규제 마일스톤으로, 상용 원자로 건설 추진에 있어 핵심적인 인허가 단계다. 테라파워는 나트륨냉각 고속로 기술을 개발 중이며, 이번 승인은 미국 첨단원자력 개발 정책의 구체적 진전을 보여준다.",
  "cat": "인허가",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "US",
  "source": "ans.org",
  "url": "https://www.ans.org/news/article-7818/nrc-approves-terrapower-construction-permit/",
  "k": "nrc approves terrapower construction permit",
  "id": "ca0f28bd"
 },
 {
  "date": "2026-07-20",
  "title": "홀텍, 소형모듈원자로 대량 생산 판매 확대를 위해 IPO 추진",
  "summary": "뉴저지 소재 홀텍이 소형모듈원자로(SMR)의 대량 생산·판매 확대를 목표로 신규공개상장(IPO)을 계획 중이다.",
  "summaryLong": "뉴저지주(New Jersey) 기반의 홀텍 인터내셔널이 소형모듈원자로(SMR) 사업 확장을 위한 자금 조달 목적으로 신규공개상장(IPO)을 추진하고 있다. 이는 SMR의 대량 생산 및 시장 판매를 본격화하기 위한 자본 확충 전략으로, 홀텍의 SMR 사업에 대한 투자자 관심이 증가함을 보여준다.",
  "cat": "투자",
  "type": "PWR",
  "dev": "Holtec",
  "region": "US",
  "source": "inquirer.com",
  "url": "https://www.inquirer.com/business/holtec-nuclear-plants-ipo-20260720.html",
  "k": "n j based holtec plans ipo to boost sales of its mass produced small nuclear plants",
  "id": "793bafc0"
 },
 {
  "date": "2026-07-19",
  "title": "홀텍(Holtec), SMR 사업으로 IPO 추진",
  "summary": "미국 홀텍이 소형모듈원자로(SMR) 사업 확대를 목표로 기업공개(IPO)를 추진 중이다.",
  "summaryLong": "미국의 원자력 기업 홀텍(Holtec)이 소형모듈원자로(SMR) 사업에 대한 투자 확대를 배경으로 기업공개(IPO)를 추진하고 있다. 이는 SMR 시장 성장 전망과 정부의 차세대 원전 정책 추진에 따른 사업 기회 확대에 대응하는 것으로 보인다. IPO를 통해 조달한 자금은 SMR 개발 및 사업화 가속화에 투입될 것으로 예상된다.",
  "cat": "투자",
  "type": "PWR",
  "dev": "Holtec",
  "region": "US",
  "source": "asiatimes.com",
  "url": "https://asiatimes.com/2026/07/us-firm-holtec-bets-big-on-small-modular-nuclear-reactors-in-ipo/",
  "k": "us firm holtec bets big on small modular nuclear reactors in ipo",
  "id": "b1dc37ce"
 },
 {
  "date": "2026-07-16",
  "title": "X-Energy: A Credible Nuclear Platform, But Valuation Is Not Cheap - Seeking Alpha",
  "summary": "X-Energy: A Credible Nuclear Platform, But Valuation Is Not Cheap Seeking Alpha",
  "summaryLong": "X-Energy: A Credible Nuclear Platform, But Valuation Is Not Cheap Seeking Alpha",
  "cat": "투자",
  "type": "HTGR",
  "dev": "X-energy",
  "region": "",
  "source": "seekingalpha.com",
  "url": "https://seekingalpha.com/article/4922467-x-energy-stock-credible-nuclear-platform-but-valuation-not-cheap",
  "k": "x energy a credible nuclear platform but valuation is not cheap",
  "id": "0a7c9b36"
 },
 {
  "date": "2026-07-16",
  "title": "Around 2 billion years ago, Oklo became a natural nuclear reactor beneath Africa, and its radioactive rem - The Times of India",
  "summary": "Around 2 billion years ago, Oklo became a natural nuclear reactor beneath Africa, and its radioactive rem The Times of India",
  "summaryLong": "Around 2 billion years ago, Oklo became a natural nuclear reactor beneath Africa, and its radioactive rem The Times of India",
  "cat": "투자",
  "type": "SFR",
  "dev": "Oklo",
  "region": "",
  "source": "timesofindia.indiatimes.com",
  "url": "https://timesofindia.indiatimes.com/world/rest-of-world/around-2-billion-years-ago-oklo-became-a-natural-nuclear-reactor-beneath-africa-and-its-radioactive-remains-are-still-there/articleshow/132436519.cms",
  "k": "around 2 billion years ago oklo became a natural nuclear reactor beneath africa and its radioactive rem",
  "id": "0e1b48e2"
 },
 {
  "date": "2026-07-15",
  "title": "NRC, TVA의 BWRX-300 소형모듈원자로 건설허가 권고",
  "summary": "미국 원자력규제위원회(NRC) 직원들이 테네시 클린치강(Clinch River)에 건설될 테네시밸리공사(TVA)의 BWRX-300 소형모듈원자로에 대한 건설허가를 권고했다.",
  "summaryLong": "미국 원자력규제위원회(NRC) 직원들이 테네시 클린치강(Clinch River)에 건설될 테네시밸리공사(TVA)의 BWRX-300 소형모듈원자로 프로젝트에 대한 건설허가를 권고했다. 이는 미국의 대표적 SMR 개발 프로젝트 중 하나로, NRC의 공식 승인 단계로의 진전을 의미한다.",
  "cat": "인허가",
  "type": "BWR",
  "dev": "TVA",
  "region": "US",
  "source": "energiesmedia.com",
  "url": "https://energiesmedia.com/nrc-recommends-tva-bwrx-300-reactor/",
  "k": "nrc staff recommend construction permit for tva s bwrx 300 small modular reactor at clinch river in tennessee",
  "id": "8d112163"
 },
 {
  "date": "2026-07-15",
  "title": "홀텍(Holtec), IPO 신청서에서 소형모듈원자로에 주력 선언",
  "summary": "홀텍이 기업공개(IPO) 신청서에서 소형모듈원자로(SMR) 사업을 핵심 성장 동력으로 제시했다.",
  "summaryLong": "홀텍(Holtec)이 기업공개(IPO) 신청 과정에서 소형모듈원자로(SMR) 분야에 대한 강한 사업 의지를 드러냈다. 신청서는 홀텍의 SMR 포트폴리오와 미래 성장 전략을 상세히 담고 있으며, 이는 차세대 원전 기술 시장에서의 입지 강화를 목표로 한다.",
  "cat": "투자",
  "type": "PWR",
  "dev": "홀텍",
  "region": "US",
  "source": "canarymedia.com",
  "url": "https://www.canarymedia.com/articles/nuclear/holtec-ipo-small-modular-reactors",
  "k": "holtec bets big on small nuclear reactors in its ipo filing",
  "id": "0794ebb9"
 },
 {
  "date": "2026-07-15",
  "title": "X-Energy drops 48% as InvestingPro Fair Value flagged overvaluation By Investing.com - Investing.com",
  "summary": "X-Energy drops 48% as InvestingPro Fair Value flagged overvaluation By Investing.com Investing.com",
  "summaryLong": "X-Energy drops 48% as InvestingPro Fair Value flagged overvaluation By Investing.com Investing.com",
  "cat": "투자",
  "type": "HTGR",
  "dev": "X-energy",
  "region": "",
  "source": "investing.com",
  "url": "https://www.investing.com/news/investment-ideas/xenergy-drops-48-as-investingpro-fair-value-flagged-overvaluation-93CH-4792876",
  "k": "x energy drops 48 as investingpro fair value flagged overvaluation by investing com",
  "id": "22339b6f"
 },
 {
  "date": "2026-07-15",
  "title": "Tracking Cathie Wood: Heavy Investment in Circle & X-Energy, Trimming Genomics Leaders - Moomoo",
  "summary": "Tracking Cathie Wood: Heavy Investment in Circle & X-Energy, Trimming Genomics Leaders Moomoo",
  "summaryLong": "Tracking Cathie Wood: Heavy Investment in Circle & X-Energy, Trimming Genomics Leaders Moomoo",
  "cat": "투자",
  "type": "HTGR",
  "dev": "X-energy",
  "region": "",
  "source": "moomoo.com",
  "url": "https://www.moomoo.com/community/feed/tracking-cathie-wood-heavy-investment-in-circle-x-energy-trimming-116923217674246",
  "k": "tracking cathie wood heavy investment in circle x energy trimming genomics leaders",
  "id": "4bdb10e9"
 },
 {
  "date": "2026-07-14",
  "title": "NRC, 웨스팅하우스의 AP1000 표준설계인증 갱신 면제 승인",
  "summary": "미국 원자력규제위원회(NRC)가 웨스팅하우스의 AP1000 가압경수로(PWR) 표준설계인증(DC) 갱신을 위한 일정 요건 면제를 승인했다.",
  "summaryLong": "미국 원자력규제위원회(NRC)는 웨스팅하우스가 AP1000 가압경수로(PWR)의 표준설계인증(DC)을 갱신하고 업데이트하는 과정에서 신청 시기 제한에 대한 면제 요청을 승인했다. 이는 웨스팅하우스가 설계인증 갱신을 추진하는 데 있어 규제 절차상 중요한 진전으로, 갱신 일정의 유연성을 확보하게 됐음을 의미한다.",
  "cat": "인허가",
  "type": "PWR",
  "dev": "Westinghouse",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-07-14/article-8200/nrc-approves-westinghouse-exemption-request-for-ap1000-dc/",
  "k": "nrc approves westinghouse exemption request for ap1000 dc",
  "id": "8e72b8bf"
 },
 {
  "date": "2026-07-14",
  "title": "현대건설, 미국 FANCO와 납-비스무트 냉각 SMR 사업 협력",
  "summary": "현대건설이 미국의 FANCO와 납-비스무트 냉각 방식의 SMR 사업 협력을 추진한다.",
  "summaryLong": "현대건설이 미국의 차세대 SMR 개발사 FANCO와 납-비스무트(Pb-Bi) 냉각 방식의 소형모듈원자로 사업 협력을 진행 중이다. 납-비스무트 냉각은 액체금속냉각 SMR 기술로, 고온·고밀도 에너지 특성으로 주목받고 있다. 현대건설은 이 협력을 통해 4세대 원전 기술 확보 및 미국 시장 진출을 강화하려는 전략이다.",
  "cat": "기술",
  "type": "FHR",
  "dev": "Hyundai E&C",
  "region": "US",
  "source": "newspost.kr",
  "url": "https://www.newspost.kr/news/articleView.html?idxno=224208",
  "k": "현대건설 fanco와 납 비스무트 냉각 smr 사업 협력",
  "ko": 1,
  "id": "51c3ba7a"
 },
 {
  "date": "2026-07-13",
  "title": "NRC issues white safety finding to V.C. Summer",
  "summary": "The Nuclear Regulatory Commission has upheld and finalized a “white” safety finding at V.C. Summer power plant in Jenkinsville, S.C., over the plant’s failure to properly…",
  "summaryLong": "The Nuclear Regulatory Commission has upheld and finalized a “white” safety finding at V.C. Summer power plant in Jenkinsville, S.C., over the plant’s failure to properly preplan and perform maintenance on its turbine-driven emergency feedwater pump (TDEFW) governor valve linkage. The 966-MWe three-loop Westinghouse pressurized water reactor at Summer started commercial operati…",
  "cat": "인허가",
  "type": "PWR",
  "dev": "Westinghouse",
  "region": "US",
  "source": "ANS Newswire",
  "url": "https://www.ans.org/news/2026-07-13/article-8198/nrc-issues-white-safety-finding-to-vc-summer/",
  "k": "nrc issues white safety finding to v c summer",
  "id": "a4191554"
 },
 {
  "date": "2026-07-11",
  "title": "뉴스케일(NuScale), 지연과 약한 실적으로 7.4% 하락",
  "summary": "뉴스케일(NuScale)의 프로젝트 지연과 확정 계약 부재로 주가가 7.4% 하락했다는 보도.",
  "summaryLong": "뉴스케일(NuScale)의 소형모듈원자로(SMR) 사업이 지연되고 실적이 부진하며 확정된 계약이 없다는 점으로 인해 주가가 7.4% 하락했다고 보도된 기사로, 회사의 사업 진행 상황과 계약 현황에 대한 실질적 소식에 해당한다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "NuScale",
  "region": "US",
  "source": "finance.yahoo.com",
  "url": "https://finance.yahoo.com/markets/stocks/articles/why-nuscale-power-smr-down-150821532.html",
  "k": "why nuscale power smr is down 7 4 after mounting delays weak results and no firm contracts",
  "id": "a571edbd"
 },
 {
  "date": "2026-07-10",
  "title": "NRC, 테네시 클린치 리버 사이트의 TVA 소형모듈원자로(BWRX-300) 건설허가 권고",
  "summary": "미국원자력규제위원회(NRC) 직원이 테네시(Tennessee) 클린치 리버(Clinch River) 부지에서 테네시밸리오써리티(TVA)의 BWRX-300 소형모듈원자로 건설을 위한 건설허가를 권고했다.",
  "summaryLong": "미국원자력규제위원회(NRC) 직원이 테네시밸리오써리티(TVA)가 테네시 클린치 리버 부지에서 추진 중인 BWRX-300 소형모듈원자로(SMR) 프로젝트에 대해 건설허가를 권고했다. BWRX-300은 캐나다 롤스로이스(Rolls-Royce SMR)가 개발한 소형 비등경수로(BWR) 기반 설계로, 미국 내 SMR 상용화의 중요한 진전을 나타낸다. 이는 대형 원전과 달리 소형 규모로 기존 화력발전소 부지 등에 배치 가능한 첨단 원자력 기술의 규제 승인 단계로 진행 중임을 보여준다.",
  "cat": "인허가",
  "type": "BWR",
  "dev": "TVA/Rolls-Royce",
  "region": "US",
  "source": "energiesmedia.com",
  "url": "https://energiesmedia.com/nrc-recommends-bwrx-300-permit-reactor/",
  "k": "nrc staff recommend construction permit for tva s bwrx 300 small modular reactor at clinch river site in tennessee",
  "id": "974f62d9"
 },
 {
  "date": "2026-07-10",
  "title": "미국 원자력위원회(NRC), 웨스팅하우스 AP1000 설계인증 갱신 면제",
  "summary": "미국 원자력위원회(NRC)가 웨스팅하우스(Westinghouse)에 보겔(Vogtle) 3·4호기 건설·운영 경험을 반영한 AP1000(가압경수로, PWR) 표준설계인증 갱신 신청을 인증서 만료 전에 진행할 수 있도록 면제했다.",
  "summaryLong": "미국 원자력위원회(NRC)가 웨스팅하우스(Westinghouse)에 AP1000 표준설계인증(Standard Design Certification) 갱신 신청을 통상적 규칙보다 앞당겨 진행할 수 있도록 허용했다. 이는 보겔(Vogtle) 3·4호기의 건설 및 운영 경험에서 나온 교훈을 신규 설계인증에 반영하기 위한 것이다. 현 인증서의 만료까지 충분한 여유를 두고 갱신 절차를 시작할 수 있어, 인증서 단절 없이 차세대 AP1000 기술 표준화를 이룰 수 있게 된다.",
  "cat": "인허가",
  "type": "PWR",
  "dev": "Westinghouse",
  "region": "US",
  "source": "World Nuclear News",
  "url": "https://www.world-nuclear-news.org/articles/nrc-exempts-westinghouse-from-design-certification-renewal-rule",
  "k": "nrc exempts westinghouse from design certification renewal rule",
  "id": "3e29fa6a"
 },
 {
  "date": "2026-07-07",
  "title": "Millionaire Maker or Market Hype? The Honest Truth About NuScale Power. - The Motley Fool",
  "summary": "Millionaire Maker or Market Hype? The Honest Truth About NuScale Power. The Motley Fool",
  "summaryLong": "Millionaire Maker or Market Hype? The Honest Truth About NuScale Power. The Motley Fool",
  "cat": "투자",
  "type": "PWR",
  "dev": "NuScale",
  "region": "",
  "source": "fool.com",
  "url": "https://www.fool.com/investing/2026/07/07/millionaire-maker-or-market-hype-the-honest-truth/",
  "k": "millionaire maker or market hype the honest truth about nuscale power",
  "id": "c067efe7"
 },
 {
  "date": "2026-07-05",
  "title": "뉴스케일(NuScale) 파라곤과 원자로 보호 계약 체결 후 소송 직면",
  "summary": "뉴스케일(NuScale)이 파라곤(Paragon)과 원자로 보호 계약을 체결했으나 소송에 직면하고 있다.",
  "summaryLong": "소형모듈원자로(SMR) 개발사인 뉴스케일(NuScale)이 파라곤(Paragon)과 원자로 보호(Reactor Protection) 관련 계약을 체결했다. 그러나 이 계약을 둘러싼 소송이 제기되었으며, 계약의 구체적 내용과 소송의 쟁점에 대한 상세 정보는 제시되지 않았다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "NuScale",
  "region": "US",
  "source": "finance.yahoo.com",
  "url": "https://finance.yahoo.com/markets/stocks/articles/nuscale-power-smr-faces-lawsuit-151304822.html",
  "k": "nuscale power smr faces lawsuit as it awards paragon reactor protection contract",
  "id": "074f0909"
 },
 {
  "date": "2026-07-01",
  "title": "i-SMR 기술개발사업단, 싱가포르 에너지시장청과 협력",
  "summary": "한국의 i-SMR(혁신형 소형모듈원자로) 기술개발사업단이 싱가포르 에너지시장청(EMA)과 협력 양해각서를 체결했다.",
  "summaryLong": "한국 정부의 i-SMR(혁신형 소형모듈원자로) 기술개발사업단이 싱가포르 에너지시장청(Energy Market Authority, EMA)과의 협력을 추진한다. 이는 한국의 소형모듈원자로 기술을 싱가포르 등 아시아 에너지 시장으로 확대하기 위한 전략적 파트너십이다. 양국 간 기술 정보 공유 및 규제 협력을 통해 i-SMR의 해외 인허가 기반을 마련하고자 한다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "i-SMR",
  "region": "KR",
  "source": "newsis.com",
  "url": "https://www.newsis.com/view/NISX20260701_0003691513",
  "k": "i smr 기술개발사업단 싱가포르 에너지시장청과 협력",
  "ko": 1,
  "id": "43462ee1"
 },
 {
  "date": "2026-07-01",
  "title": "i-SMR 사업단, 싱가포르와 SMR 협력 양해각서 체결",
  "summary": "한국 혁신형 소형모듈원자로(i-SMR) 사업단이 싱가포르 에너지시장청(EMA)과 SMR 분야 협력을 위한 양해각서를 체결했다.",
  "summaryLong": "혁신형 소형모듈원자로 기술개발사업단(i-SMR)은 지난달 30일 싱가포르에서 개최된 'Asia Nuclear Energy & SMR 2026' 행사에서 싱가포르 에너지시장청(EMA)과 소형모듈원자로(SMR) 분야 협력 강화를 위한 양해각서(MOU)를 체결했다. 싱가포르 정부는 전력의 90% 이상을 수입 천연가스(LNG)에 의존하고 있으며, 화석연료 의존도를 낮추고 에너지원을 다변화하기 위한 핵심 대안으로 원자력 도입을 검토 중이다. 인구 밀집도가 높은 싱가포르의 환경적 특성을 고려할 때 SMR이 적합한 선택지로 평가되고 있으며, 이번 협력은 양국 간 SMR 기술 협력의 기초를 마련하는 의미를 갖는다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "i-SMR",
  "region": "KR",
  "source": "투데이에너지 - 전체기사",
  "url": "https://www.todayenergy.kr/news/articleView.html?idxno=299812",
  "k": "i smr 사업단 싱가포르 에너지시장청과 smr 협력",
  "ko": 1,
  "id": "23e963b9"
 },
 {
  "date": "2026-06-22",
  "title": "오클로, 우라늄 공급 계약으로 핵분열 사업 강화",
  "summary": "오클로(Oklo)가 우라늄 공급 계약을 체결하며 핵분열 연료 확보에 나섰다.",
  "summaryLong": "오클로는 차세대 SMR 또는 첨단로 운영을 위한 핵연료 공급 계약을 확보함으로써 상용화 단계로의 진전을 도모하고 있다. 우라늄 공급 협약은 실제 원자로 운영 시 필수 요소로, 오클로의 사업화 준비도를 반영한다. 이는 개발 단계를 넘어 실제 운영 단계를 대비하는 계약으로, SMR 산업의 공급망 구축 진행 상황을 보여준다.",
  "cat": "계약",
  "type": "SFR",
  "dev": "Oklo",
  "region": "US",
  "source": "thedailyupside.com",
  "url": "https://www.thedailyupside.com/technology/artificial-intelligence/oklo-may-have-solved-its-uranium-sourcing-problem/",
  "k": "uranium deal powers up nuclear fission firm oklo",
  "id": "1164ecf0"
 },
 {
  "date": "2026-06-22",
  "title": "오클로(Oklo) 주가 최고점 대비 70% 하락…핵심 과제는 규제 승인",
  "summary": "소형모듈원자로·첨단로 개발사 오클로(Oklo)의 주가가 최고점에서 70% 하락했으며, 회사의 성공을 위해서는 규제 진전이 필수적이라는 분석이 제시되고 있다.",
  "summaryLong": "소형모듈원자로(SMR)·용융염로 개발사 오클로(Oklo)의 주가가 최고점 대비 70% 급락했다. 업계 분석에 따르면 오클로를 포함한 뉴스케일(NuScale), 엑스에너지(X-energy), 테라파워(TerraPower), 카이로스(Kairos Power), 롤스로이스 SMR(Rolls-Royce SMR) 등 첨단로 개발사들의 성공을 위해서는 규제 당국의 설계 승인 및 상용화 허가 등 규제 진전이 절대적 조건이다. 현재 낮은 주가에도 불구하고 규제 진전 여부가 이들 회사의 향후 전망을 결정할 핵심 변수로 작용하고 있다.",
  "cat": "인허가",
  "type": "SFR",
  "dev": "Oklo",
  "region": "US",
  "source": "tikr.com",
  "url": "https://www.tikr.com/blog/oklo-stock-has-fallen-70-from-its-peak-here-is-what-it-would-take-for-the-nuclear-bet-to-pay-off",
  "k": "oklo stock has fallen 70 from its peak here is what it would take for the nuclear bet to pay off",
  "op": 1,
  "id": "07b2ef53"
 },
 {
  "date": "2026-06-18",
  "title": "테라파워, 나트륨(Natrium) 원자로 영국 설계인증(GDA) 신청",
  "summary": "테라파워(TerraPower)가 나트륨 고속로 기술에 대한 영국 설계인증을 공식 시작함.",
  "summaryLong": "테라파워(TerraPower)가 자사의 나트륨(Natrium) 고속냉각로에 대해 영국(UK) 설계인증(Generic Design Assessment, GDA) 프로세스를 개시했다. GDA는 영국 원자력규제청(ONR)이 실시하는 신형 원자로 설계에 대한 기술적 평가 단계로, 향후 건설 허가 취득의 전제 조건이 된다. 이는 테라파워의 SFR 기술이 영국 시장 진입을 위한 공식 규제 절차에 진입했음을 의미하며, 설계 검증(Design-led Justifying Design, 'Design-led JDD') 단계의 진전을 보여주는 중요한 마일스톤이다.",
  "cat": "인허가",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "UK",
  "source": "energynews.pro",
  "url": "https://energynews.pro/en/terrapower-launches-uk-generic-design-assessment-for-its-natrium-reactor",
  "k": "terrapower launches uk generic design assessment for its natrium reactor",
  "id": "73397c42"
 },
 {
  "date": "2026-06-03",
  "title": "한국 i-SMRDA, 터키 Nuclean과 SMR 협력 협약 체결",
  "summary": "한국의 i-SMRDA(i-Small Modular Reactor Development Alliance)와 터키의 Nuclean이 소형모듈원자로(SMR) 개발·보급을 위한 협력 양해각서를 체결했다.",
  "summaryLong": "한국의 i-SMRDA와 터키의 Nuclean이 소형모듈원자로(SMR) 분야 협력을 위한 협약을 체결했다. 이는 한국의 SMR 기술과 터키의 시장 진출 의향이 결합된 전략적 파트너십으로, 양국이 SMR 개발과 국제 보급 네트워크 구축에 협력하기로 합의한 것이다. 이 협력은 아시아와 중동 지역의 에너지 안보 강화 및 탄소중립 달성에 기여할 것으로 예상된다.",
  "cat": "계약",
  "type": "PWR",
  "dev": "i-SMRDA",
  "region": "KR",
  "source": "dailysabah.com",
  "url": "https://www.dailysabah.com/business/energy/south-koreas-i-smrda-turkiyes-nuclean-ink-co-op-deal-on-smrs",
  "k": "south korea s i smrda t rkiye s nuclean ink co op deal on smrs daily sabah",
  "id": "5ac4cb01"
 },
 {
  "date": "2026-03-04",
  "title": "미국 원자력규제위원회, 테라파워 건설허가 승인",
  "summary": "미국 원자력규제위원회(NRC)가 테라파워의 나트륨냉각고속로(SFR) 건설허가를 승인했다.",
  "summaryLong": "미국 원자력규제위원회(NRC)는 테라파워의 나트륨냉각고속로 기반 첨단 원자로 프로젝트에 대한 건설허가(Construction Permit)를 승인했다. 이는 테라파워의 상용 원자로 건설을 위한 규제 진입으로, 미국 첨단원자로(Advanced Reactor) 개발의 중요한 이정표를 의미한다.",
  "cat": "인허가",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "US",
  "source": "ans.org",
  "url": "https://www.ans.org/news/article-7818/nrc-approves-terrapower-construction-permit/",
  "k": "nrc approves terrapower construction permit american nuclear society ans",
  "id": "ca0f28bd"
 },
 {
  "date": "2025-12",
  "title": "미국 원자력규제위원회(NRC), 테라파워 나트륨(Natrium) 안전심사 조기 완료",
  "summary": "테라파워(TerraPower)의 나트륨(Natrium) 소형모듈원자로가 미국 원자력규제위원회(NRC) 안전심사를 일정보다 앞서 완료하였으며, 2026년 3월 건설허가(CP) 발급으로 이어질 예정이다.",
  "cat": "인허가",
  "type": "SFR",
  "dev": "TerraPower",
  "region": "US",
  "source": "ANS",
  "url": "https://www.ans.org/news/article-7818/nrc-approves-terrapower-construction-permit/",
  "summaryLong": "미국 원자력규제위원회(NRC)가 테라파워(TerraPower)의 나트륨(Natrium) 소형모듈원자로에 대한 안전심사를 예정일보다 앞서 완료하여 예산 절감 효과를 거두었다. 나트륨은 액체 금속 냉각 기술을 적용한 차세대 소형모듈원자로로, 안전심사 조기 완료는 미국의 SMR 상용화 추진 의지를 반영한다. 2026년 3월 건설허가(CP) 발급이 예정되어 있어 실제 건설 단계로의 진입이 임박한 상황이다. 이는 테라파워와 미국 에너지부(DOE)가 추진 중인 나트륨 시범사업의 경제성과 기술 신뢰도를 높이는 계기가 될 것으로 기대된다.",
  "id": "ca0f28bd"
 },
 {
  "date": "2025-07",
  "title": "ARC-100, 캐나다 캐나다핵안전위원회(CNSC) 벤더설계심사(VDR) Phase 2 완료",
  "summary": "아크클린에너지(ARC)의 ARC-100이 근본적 인허가 장벽이 없는 것으로 판정되었으며, 뉴브런즈윅전력(NB Power)은 부지준비허가 신청을 진행 중이고 2027년 건설허가 신청을 목표로 한다.",
  "cat": "인허가",
  "type": "SFR",
  "dev": "ARC",
  "region": "CA",
  "source": "WNN",
  "url": "https://www.world-nuclear-news.org/articles/arc-100-completes-canadian-regulatory-design-review",
  "summaryLong": "아크클린에너지(ARC)의 ARC-100 소형모듈원자로가 캐나다핵안전위원회(CNSC)의 벤더설계심사(VDR) 2단계를 완료하여 '근본적 인허가 장벽이 없다'는 판정을 받았다. 뉴브런즈윅전력(NB Power)은 이를 토대로 부지준비허가 신청 절차를 진행하고 있으며, 2027년 건설허가 신청을 목표로 하고 있다. 이는 캐나다에서 소형모듈원자로 인허가의 진전을 보여주는 중요한 사례이다. 실제 건설 단계로의 진입이 임박했다.",
  "id": "e5cb9369"
 },
 {
  "date": "2024",
  "title": "카이로스 파워(Kairos Power)–구글, 첨단로 전력공급 계약 체결",
  "summary": "카이로스의 KP-FHR(헤르메스(Hermes) 계열) 첨단로에서 생산한 전력을 구글에 공급하는 전력공급계약(PPA)을 체결했다.",
  "cat": "계약",
  "type": "FHR",
  "dev": "Kairos Power",
  "region": "US",
  "source": "Kairos Power",
  "url": "",
  "summaryLong": "첨단로 개발사 카이로스 파워와 기술 대기업 구글이 전력공급계약(PPA)을 체결했다. 카이로스의 KP-FHR(헤르메스 계열) 용융염냉각로(MSFR)에서 생산한 전력을 구글에 장기 공급하는 계약이다. 이는 빅테크 기업이 첨단로 전력을 직접 구매하는 계약 중 주요 사례로, 데이터센터 운영의 탈탄소화 추진을 보여준다. 구글의 재정 및 기술적 지원은 카이로스의 상용화 추진에 중요한 역할을 할 것으로 전망된다.",
  "id": "811c9dc5"
 },
 {
  "date": "2024-09",
  "title": "SMART100 표준설계인가 취득(한국)",
  "summary": "한국원자력연구원(KAERI)의 SMART100이 한국 표준설계인가를 취득했으며, 사우디 수출과 현대엔지니어링 협력을 추진 중이다.",
  "cat": "인허가",
  "type": "PWR",
  "dev": "SMART/KAERI",
  "region": "KR",
  "source": "KAERI",
  "url": "https://kaeri.re.kr/board/view?linkId=12112&menuId=MENU00326",
  "summaryLong": "한국원자력연구원(KAERI)이 개발한 소형모듈로(SMR) SMART100이 국내 표준설계인가를 취득했다. SMART100은 166 MWth급 통합형 원전으로, 한국 기술의 우수성을 국제적으로 입증하는 의미를 가진다. 이를 통해 사우디아라비아 수출 및 현대엔지니어링과의 협력이 구체화될 것으로 예상되며, 향후 한국의 SMR 해외 수출 전략 추진에 중추적 역할을 할 것으로 전망된다.",
  "id": "5661c65a",
  "ko": 1
 }
];
window.SMR_UPDATED = "2026-07-31 08:44 KST";
window.SMR_TOTAL = 1674;
